### ISSUE TITLE
Even more errors during CLI install

### ISSUE THREAD

**Issue by jabmt** [oracle/oci-cli#101]
Anyone, 

I, too, am having issues installing

Starting here:  https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliinstall.htm
Issueing this:  bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"

This process never prompts me.  I've attached the log.  It appears Python does install correctly.  But,
at the end of the process, I see these errors:

Traceback (most recent call last):
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/ensurepip/__init__.py", line 189, in _main
    default_pip=args.default_pip,
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/ensurepip/__init__.py", line 102, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/opc/dba/oci-cli/Python-3.6.0/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1
Running install script.
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_c3Nk", line 21, in <module>
    import ssl
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
]0;opc@dev-exapho-vtxg82:~/dba/oci-cli[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba/oci-cli]
otmphdb12:>exit
exit

The entire install log file is attached. 

I previously asked for a de-install method (missed the online doc).  But, that assumes a clean install.
If I need to start over, how do I clean up from a failed install?

Regards, 

John 

[oci-install.log](https://github.com/oracle/oci-cli/files/2526084/oci-install.log)

**Comment by paul-hummel-oracle** [comment]
Hi John @jabmt,  I think you are missing zlib. What OS are you running?   Assuming some kind of redhat variant, could you try this?
    **_sudo yum install zlib-devel_**

Before running the install script again, and assuming you don't have a previous CLI installation you care about, you could remove this directory:
**_rm -fr /home/opc/dba/oci-cli_**

thank you
Paul

**Comment by jabmt** [comment]
Paul, 
Thank you for your response.    I removed the directory as you show.  
Though, I am reluctant to run the original install command again as I sense no change in result:

-- Here, verifying that any "zlib" is installed. 
[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>rpm -q zlib
zlib-1.2.3-29.el6.x86_64

-- Here, attempting to install the "zlib-devel"
------------------------------------------------------------------------------------
[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo  yum install zlib-devel
Setting up Install Process
No package zlib-devel available.
Error: Nothing to do

if "zlib-devel" is specifically needed, I will have to see what can be done to get that 
package on the system.  

Just to be clear, here is OS info:

uname -a
Linux dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com 4.1.12-94.8.4.el6uek.x86_64 #2 SMP Sat May 5 16:14:51 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

Regards, 

John

**Comment by paul-hummel-oracle** [comment]
Hi John,

For my test boxes, I have the following in my setup:
	sudo yum -y install patch
	sudo yum -y install gcc libffi-devel python-devel openssl-devel
	sudo yum -y install python-setuptools python-setuptools-devel
	sudo easy_install pip==9.0.3
	sudo yum -y install git-all readline bzip2 sqlite **zlib-devel** bzip2-devel readline-devel sqlite-devel openssl-devel xz xz-devel
	sudo yum -y install make

This works for my CentOS and Oracle Linux boxes.  I'm not suggesting you need to do all that, but just wanted to show that zlib-devel is different from just zlib.

Can you do this and paste the results as well?
cat /etc/redhat-release

Curious that "sudo yum install zlib-devel" did not work.  It looks like you might need to add a repo file to /etc/yum.repos.d.

**Comment by jabmt** [comment]
Paul, 

As you may have guessed, my OS knowledge is limited.  But, here are the results of all the commands you listed:

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo yum -y install patch
Setting up Install Process
No package patch available.
Error: Nothing to do

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo yum -y install gcc libffi-devel python-devel openssl-devel
Setting up Install Process
No package libffi-devel available.
No package python-devel available.
No package openssl-devel available.
Nothing to do

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo yum -y install python-setuptools python-setuptools-devel
Setting up Install Process
No package python-setuptools available.
No package python-setuptools-devel available.
Error: Nothing to do

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo easy_install pip==9.0.3
sudo: easy_install: command not found

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo yum -y install git-all readline bzip2 sqlite zlib-devel bzip2-devel readline-devel sqlite-devel openssl-devel xz xz-devel
Setting up Install Process
No package git-all available.
No package zlib-devel available.
No package bzip2-devel available.
No package readline-devel available.
No package sqlite-devel available.
No package openssl-devel available.
No package xz-devel available.
Nothing to do

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>sudo yum -y install make
Setting up Install Process
Nothing to do

[opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc/dba]
otmphdb12:>cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.9 (Santiago)

otmphdb12:>ls /etc/yum.repos.d
Exadata-computenode.repo.sample

What else can I provide you?

**Comment by paul-hummel-oracle** [comment]
Hi @jabmt, from what you have provided that confirms you will need to setup the yum repos on your instance.  Let me give you some articles to get you started down that path:

This is just a general article and will lack specifics.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-configuring_yum_and_yum_repositories

This may be slightly more helpful, but downloading a DVD ISO seems a bit extreme as most of the stuff should be online.
https://www.digitalocean.com/community/tutorials/how-to-set-up-and-use-yum-repositories-on-a-centos-6-vps

Here is the official mirror for CentOS 6.9 -- you should be able to browse this structure and setup your repo files using these locations.
http://vault.centos.org/6.9/
FYI, here is a zlib-devel package -- 
http://vault.centos.org/6.9/os/x86_64/Packages/zlib-devel-1.2.3-29.el6.x86_64.rpm

I hope this helps.

**Comment by paul-hummel-oracle** [comment]
@jabmt someone shared this example of their repo file with me.  You may find it useful.

[ol6_latest]
name=Oracle Linux $releasever Latest ($basearch)
#baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/latest/$basearch/
baseurl=http://yum.oracle.com/repo/OracleLinux/OL6/latest/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=1

[ol6_addons]
name=Oracle Linux $releasever Add ons ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/addons/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_ga_base]
name=Oracle Linux $releasever GA installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/0/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u1_base]
name=Oracle Linux $releasever Update 1 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/1/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u2_base]
name=Oracle Linux $releasever Update 2 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/2/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u3_base]
name=Oracle Linux $releasever Update 3 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/3/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u4_base]
name=Oracle Linux $releasever Update 4 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/4/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u5_base]
name=Oracle Linux $releasever Update 5 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/5/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u6_base]
name=Oracle Linux $releasever Update 6 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/6/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_u7_base]
name=Oracle Linux $releasever Update 7 installation media copy ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/7/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0


[ol6_UEKR3_latest]
name=Latest Unbreakable Enterprise Kernel for Oracle Linux $releasever ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/UEKR3/latest/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=1

[ol6_UEK_latest]
name=Latest Unbreakable Enterprise Kernel for Oracle Linux $releasever ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/UEK/latest/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=1

[ol6_UEK_base]
name=Unbreakable Enterprise Kernel for Oracle Linux $releasever ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/UEK/base/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_MySQL]
name=MySQL 5.5 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/MySQL/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_gdm_multiseat]
name=Oracle Linux 6 GDM Multiseat ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/gdm_multiseat/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_MySQL56]
name=MySQL 5.6 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/MySQL56/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_spacewalk20_server]
name=Spacewalk Server 2.0 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/spacewalk20/server/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_spacewalk20_client]
name=Spacewalk Client 2.0 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/spacewalk20/client/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

# the following repositories are only available for x86_64 architecture systems
[ol6_ofed_UEK]
name=OFED supporting tool packages for Unbreakable Enterprise Kernel on Oracle L
inux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/ofed_UEK/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0
priority=20

[ol6_playground_latest]
name=Latest mainline stable kernel for Oracle Linux 6 ($basearch) - Unsupported
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/playground/latest/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_spacewalk22_server]
name=Spacewalk Server 2.2 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/spacewalk22/server/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

[ol6_spacewalk22_client]
name=Spacewalk Client 2.2 for Oracle Linux 6 ($basearch)
baseurl=http://public-yum.oracle.com/repo/OracleLinux/OL6/spacewalk22/client/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
gpgcheck=1
enabled=0

**Comment by jabmt** [comment]
Paul, 
Thank you for the info.  It looks like what I need.  I've been sidetracked for the past couple of days.  I will attempt to use this info and update this forum. 

Regards, 
John

**Comment by jabmt** [comment]
Paul. 

Here is an update.  I installed the zlib-devel rpm manual:

as root:   rpm -ivh /home/opc/zlib-devel-1.2.3-29.el6.x86_64.rpm

As my user (opc), I can confirm that it is installed:

  otmphdb12:>rpm -qa | grep zlib
  zlib-1.2.3-29.el6.x86_64
  zlib-devel-1.2.3-29.el6.x86_64
  [opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc]

Trying the install script again (after deleting all subdirectories):
  otmphdb12:>ls
  dba  zlib-devel-1.2.3-29.el6.x86_64.rpm

Results:

  [opc@dev-exapho-vtxg82.pho1pub.otmdevpho.oraclevcn.com:/home/opc]
  otmphdb12:>bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100  6226  100  6226    0     0  21348      0 --:--:-- --:--:-- --:--:-- 47892
  Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci cli/6dc61e3b5fd2781c5afff2decb532c24969fa6bf/scripts/install/install.py to /tmp/oci_cli_install_tmp_h1Wf.
  ######################################################################## 100.0%
  System version of Python must be either a Python 2 version >= 2.7.5 or a Python 3 version >= 3.5.0.
  Running install script.
  Traceback (most recent call last):
    File "/tmp/oci_cli_install_tmp_h1Wf", line 21, in <module>
      import ssl
    File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
      import _ssl             # if we can't import it, let the error propagate
  ModuleNotFoundError: No module named '_ssl'

I have found references to this problem on the internet.   A common response is:

   "It looks like maybe you don't have the SSL libs installed on the machine running python 3.6."

This is the only thing I know how to check:

  otmphdb12:>rpm -qa | grep ssl
  openssl-1.0.1e-57.0.1.el6.x86_64

It appears to be installed.   

Can you offer any advice?

Note, I will be getting my SysAdmin to address some of these issues.

Regards, 

John

**Comment by paul-hummel-oracle** [comment]
@jabmt You will also need openssl-devel.

Perhaps you can tell your SysAdmin to install CLI, and let them fight through the dependencies.
Hope this helps.

**Comment by jabmt** [comment]
@viralmodi , thank you for your response.  

I am stuck at a point that I need my system admin to help with the configuration of the yum repository. 
As detailed above, the DB servers do not have requisite packages required by the CLI software.  

This task has temporarily taken on a lower priority.   I will try to get back to it.

**Comment by jabmt** [comment]
If it a problem with this as an "open" issue, I am glad to close an start again when I get back to it.

**Comment by craigcarl-oracle** [comment]
@jabmt re: 
> ...the DB servers do not...
are you trying to install the CLI on an OCI DBaaS instance? I don't believe this is currently supported. If you need the CLI on a DBaaS instance please get in touch via email (in my profile) and we will find a solution.

**Comment by viralmodi** [comment]
@jabmt Thanks for your response. It is okay to keep it as an open issue as long as there is a timeline to it. I was just checking if you had any updates on it. I see that you closed the issue. If you open a new issue for the same in future, you can refer this one to give some context.
