### ISSUE TITLE
CLI installation fails on MacOS Mojave (due to cryptography install failure)

### ISSUE THREAD

**Issue by viralmodi** [oracle/oci-cli#103]
Issue:
CLI installation fails on MacOS Mojave (due to cryptography install failure). 
Error message is as below:
"Failed building wheel for cryptography"

**Comment by viralmodi** [comment]
This is a known issue with a workaround. We are also working on a long time solution. Below is the summary of the issue and workaround:

Description:
Mojave OS comes with SSL version - LibreSSL 2.6.4
Mojave OS has Python 3.7 as the system python.

There is no pre-built wheel for python3.7 for the cryptography version we use so pip CLI install is building it and then we're hitting this build failure since Mojave doesn't come with OpenSSL version 1.0.2 installed and even after installing it is not present in default lib location. 
More details of the issue: https://github.com/pyca/cryptography/issues/2692 and https://github.com/pyca/cryptography/issues/3489

Possible Solutions:
We need to install openssl using homebrew and use some C compiler flags to enable pip install to find the openssl libs to link to.

Workaround:
Execute below commands/instructions in your shell:
1) `brew install openssl (- installs openssl version 1.0.2p, populates /usr/local/opt/openssl/lib)`
2) `export CPPFLAGS=-I/usr/local/opt/openssl/include`
    `export LDFLAGS=-L/usr/local/opt/openssl/lib`
3) Download CLI script from https://github.com/oracle/oci-cli/blob/master/scripts/install/install.sh and run it to install CLI


https://cryptography.io/en/latest/changelog/ shows cryptography v2.3 added support for Python 3.7.
In near future, we will work on upgrading to a more recent version of cryptography which has a wheel built for higher versions of Python as well.

**Comment by MadalinaPatrichi** [comment]
I can confirm that this works for me too. Thanks a lot for the workaround!

**Comment by mattbordonne** [comment]
Hi. 
I'm running MacOS 10.13 (not Mojave) and had the same issue.
This workaround worked for me too, but I also had to install python using Homebrew and not use the one provided by the OS.
Thanks!
