### ISSUE TITLE
NAT Gateway listing function not returning anything

### ISSUE THREAD

**Issue by dbarj** [oracle/oci-cli#105]
Just tried several times running the nat-gateway list function and the output is always empty.

$ oci --region us-ashburn-1 --cli-rc-file /dev/null network nat-gateway list --compartment-id xxxx

If I use the optional vcn-id parameter, it makes no difference.

**Comment by viralmodi** [comment]
@dbarj Can you ensure you do have a nat-gateway created in the tenancy and compartment of your default profile as well as region given in your command (you can check by logging to console once)? Also, if you do any other command like 'vcn list' or 'bucket list', does it work?

**Comment by dbarj** [comment]
Yes I have. All network commands work but this one. Also, if I use the "oci network nat-gateway get"  giving the OCID it returns, instead of "list", it returns.
Tks.

**Comment by paul-hummel-oracle** [comment]
Hi @dbarj -- perplexing.  I just created a nat-gateway this morning and was able to get and list it.
oci network nat-gateway create --compartment-id $COMPARTMENT_ID --vcn-id ocid1.vcn.oc1.iad.XXXXXX --region us-ashburn-1 
oci network nat-gateway list --compartment-id $COMPARTMENT_ID --cli-rc-file /dev/null --region us-ashburn-1 

What version of CLI are you using? 
"oci --version"

Did you perhaps create the NAT Gateway in a different region?

**Comment by dbarj** [comment]
After removing and creating a new NAT Gateway with OCI Cli 2.4.37, I could list it! I was always using the right compartment and region in parameters.

When I created the previous NAT Gateway, this feature was just released, so maybe something was missing that the oci-cli list command could not list it.

Anyway, now it's working. Thank you Paul.
