### ISSUE TITLE
Feat: A Docker Image with the OCI CLI 

### ISSUE THREAD

**Issue by jpoon** [oracle/oci-cli#106]
I recently had the need to run the OCI CLI in an isolated environment (e.g. on a CI/CD build machine), it would be great if there was official support for running the OCI CLI in a Docker container. 

I ended up creating one here: https://github.com/jpoon/oci-cli-docker such that one could simply run:

```
$ docker run -it -v ${HOME}/.oci:/root/.oci jpoon/oci-cli <OCI Command Here>
```

without having the need to download and install the OCI CLI. I can submit a PR to this repo to add the Dockerfile if interested. 

Similar:
* Azure: https://docs.microsoft.com/en-us/cli/azure/run-azure-cli-docker
* GCP: https://hub.docker.com/r/google/cloud-sdk/

**Comment by viralmodi** [comment]
@jpoon Thanks for initiating this. We do have docker support for internal use. We will internalize and check on making the support official.

**Comment by AdityaVishwekar** [comment]
@viralmodi I'm getting following error 

[opc@devqa-instance ~]$ docker run -it -v $HOME/.oci:/root/.oci jpoon/oci-cli db autonomous-data-warehouse start --autonomous-data-warehouse-id ocid1.autonomousdwdatabase.## --wait-for-state AVAILABLE
**ERROR: Could not find config file at /root/.oci/config**

Config file is present on host. Still its not able to find inside the container

[opc@devqa-instance ~]$ cd $HOME/.oci
[opc@devqa-instance .oci]$ ls -l
total 16
-rwxrwxr-x. 1 opc opc  346 May 25  2018 config
-rwxrwxr-x. 1 opc opc 1675 Apr 29  2018 oci_api_key.pem

**Comment by paul-hummel-oracle** [comment]
@AdityaVishwekar this is not an officially supported feature yet and was not developed by our team.

**Comment by jpoon** [comment]
@AdityaVishwekar you may want to move this issue over to https://github.com/jpoon/oci-cli-docker.

Unable to repro on my machine, this works fine:

```
docker run -it -v ${HOME}/.oci:/root/.oci jpoon/oci-cli iam compartment list
```

* Is your `config` well-formed and valid?
* You can run bash inside and debug from within the container to see why your configs are not being mounted properly. The instruction for doing so is on the README: `docker run --rm -it -v ${HOME}/.oci:/root/.oci --entrypoint bash jpoon/oci-cli`

**Comment by hiranp** [comment]
Did you guys every decide on making an official docker image? I don't see anything here.
https://github.com/oracle/docker-images

**Comment by TajMahPaul** [comment]
This would be super useful for us in a CI environment. Currently using a custom image. Would be nice to use one officially supported by Oracle.

**Comment by MPV** [comment]
This one at least seems created by someone (currently) working at Oracle (@stephenpearson): https://github.com/stephenpearson/oci-cli

**Comment by stephenpearson** [comment]
I beleive that at least one of the problems with using Docker to run oci-cli is that although most things work, using session authentication doesn't currently work, and that might explain why official support hasn't materialized yet.

Maybe for Linux users, and certainly for MacOS (or Windows) users running Docker Desktop it sounds a bit complicated to get this working in theory, because the docker container running inside xhyve would have to somehow open a browser window on your desktop.  The problem is around here:
https://github.com/oracle/oci-cli/blob/8efd69e8c26b15be739a4ed010baa0574351d2b6/src/oci_cli/cli_setup_bootstrap.py#L170

**Comment by TajMahPaul** [comment]
The workflow I had with the aws cli was to log-in outside of docker and then mount the ~/.aws directory inside the docker image. That way we can do auth and still run in the container. However, with the oci-cli if I'm on windows and I sign in and then run a linux container the paths in ~/.oci/config are not correct. That might be an easier fix, not sure.

**Comment by MPV** [comment]
>The problem is around here:
> https://github.com/oracle/oci-cli/blob/8efd69e8c26b15be739a4ed010baa0574351d2b6/src/oci_cli/cli_setup_bootstrap.py#L170

Looks like it supports giving you a link to log in though (in the lines just below that), I suppose that would work, no?

**Comment by KartikShrikantHegde** [comment]
Hi @jpoon ,

We have officially released the support for OCI CLI Docker images. Please check this official doc page for more info:

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/clicontainer.htm

Hope this helps!

Thanks,
Kartik
