### ISSUE TITLE
jmespath to print without returing quotes 

### ISSUE THREAD

**Issue by pranay-oracle** [oracle/oci-cli#111]
do we have a an option in oci-cli like one mentioned for AWS 
https://github.com/aws/aws-cli/issues/1961 .
We need the json output without  quotes

**Comment by viralmodi** [comment]
@pranay-oracle You can use `--raw-output` option with OCI CLI command to get output without quotes. Note this only works when the result of JMESPath query is a single string value.

**Comment by pranay-oracle** [comment]
unfortunately most of the times return value is a list for almost all the OCI resource and --raw-output is not much of use, I end up doing a awk/grep or sed  on top to achieve.

**Comment by paul-hummel-oracle** [comment]
@pranay-oracle thanks for your inquiry.  Glad you were able to work around the issue with some post processing through awk/grep/sed.
