### ISSUE TITLE
Fails to install on Windows10 if $env:USERPROFILE has a space

### ISSUE THREAD

**Issue by simonpane** [oracle/oci-cli#115]
If the user's profile directory ($env:USERPROFILE) has a space (i.e. "C:\Users\John Doe") then the installation fails.

Call to **$PythonExecutable** in **install.ps1** will fail with error:

`C:\Users\John Doe\AppData\Local\Programs\Python\Python37\python.exe: can't open file 'C:\Users\John': [Errno 2] No such file or directory`

The Python executable file does exist (path is correct) and can be manually run.  Issue is clearly the space in the path name and running from the ps1 file.

Powershell scripts will been to be adjusted to handle spaces in path names.

(Windows 10; Python 3.7.2 64-bit)

**Comment by paul-hummel-oracle** [comment]
@simonpane Thank you for reporting this bug. 
We will update this issue when work progresses.

**Comment by mross22** [comment]
@simonpane this issue was fixed as of the following commit:
https://github.com/oracle/oci-cli/commit/617f1fbb43dba7603e988dd6aa786f85ddb34867#diff-0e63e24940bebd5f508dbbd3444c01cb
