### ISSUE TITLE
Linux Install Fails

### ISSUE THREAD

**Issue by jtpereyda** [oracle/oci-cli#117]
Running the recommended install script (see https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliinstall.htm) fails on Ubuntu 18.04 with all updates applied as of today:
```
> sudo bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6283  100  6283    0     0  21591      0 --:--:-- --:--:-- --:--:-- 21591
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/6dc61e3b5fd2781c5afff2decb532c24969fa6bf/scripts/install/install.py to /tmp/oci_cli_install_tmp_LVYu.
############################################################################################################################################################################################################## 100.0%
Running install script.
python3 /tmp/oci_cli_install_tmp_LVYu  < /dev/tty
-- Verifying Python version.
-- Python version 3.6.7 okay.
-- Verifying native dependencies.
-- Unable to verify native dependencies. dist=ubuntu, version=18.04. Continuing...

===> In what directory would you like to place the install? (leave blank to use '/home/jpereyda/lib/oracle-cli'):
-- We will install at '/home/jpereyda/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/home/jpereyda/bin'):
-- The executable will be in '/home/jpereyda/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/home/jpereyda/bin/oci-cli-scripts'):
-- The scripts will be in '/home/jpereyda/bin/oci-cli-scripts'.
-- Downloading virtualenv package from https://github.com/pypa/virtualenv/archive/15.0.0.tar.gz.
-- Downloaded virtualenv package to /tmp/tmpw52m8ytd/15.0.0.tar.gz.
-- Checksum of /tmp/tmpw52m8ytd/15.0.0.tar.gz OK.
-- Extracting '/tmp/tmpw52m8ytd/15.0.0.tar.gz' to '/tmp/tmpw52m8ytd'.
-- Executing: ['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/jpereyda/lib/oracle-cli']
Traceback (most recent call last):
  File "virtualenv.py", line 25, in <module>
    import distutils.sysconfig
ModuleNotFoundError: No module named 'distutils.sysconfig'
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_LVYu", line 541, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_LVYu", line 497, in main
    create_virtualenv(tmp_dir, install_dir)
  File "/tmp/oci_cli_install_tmp_LVYu", line 170, in create_virtualenv
    exec_command(cmd, cwd=working_dir)
  File "/tmp/oci_cli_install_tmp_LVYu", line 108, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'virtualenv.py', '--python', '/usr/bin/python3', '/home/jpereyda/lib/oracle-cli']' returned non-zero exit status 1.

```

**Comment by jtpereyda** [comment]
Workaround: Works when I run the downloaded script directly, e.g.:
```
 /tmp/oci_cli_install_tmp_LVYu
```

**Comment by paul-hummel-oracle** [comment]
@jtpereyda 
I'm glad you were able to work around this problem and thank you for the workaround.
We have installation test automation for ubuntu 14 and 16 and are adding 18 now.  We are also seeing failures.

**Comment by paul-hummel-oracle** [comment]
I have not been able to reproduce the issue @jtpereyda was observing in our automated testing.

Here are some of the steps we use to prep our Ubuntu boxes prior to CLI install:
    sudo apt-get update
    sudo apt-get --assume-yes install python3-pip
    sudo pip3 install --upgrade pip
    sudo apt-get --assume-yes install build-essential libssl-dev libffi-dev python-dev

However, I did observe that installing older versions of python (<=2.7.12, <=3.5) on Ubuntu 18 would fail unless you install libssl1.0-dev instead of libssl-dev.

**Comment by jtpereyda** [comment]
@paul-hummel-oracle The installer works after I install all those packages. If those are prerequisites, seems like they should be added to the install instructions, or maybe to the script itself.

I was running this on an OCI cloud instance using the provided Ubuntu 18.04 image -- seems like a use case that would be applicable here.

**Comment by paul-hummel-oracle** [comment]
@jtpereyda that is a fair comment.  I will open an internal ticket to improve our docs for that.
I probably won't ever get it in our installer b/c Debian family and RedHat families of linux have different package management and even Ubuntu 16 to 18 we are now seeing diffs.

**Comment by paul-hummel-oracle** [comment]
On closer inspection, we should probably just fix the installer.  Thanks again for bringing this to our attention.

**Comment by narayanaa** [comment]
sudo apt-get update
sudo apt-get --assume-yes install python3-pip
sudo pip3 install --upgrade pip
sudo apt-get install libssl1.0-dev
sudo apt-get --assume-yes install build-essential libssl-dev libffi-dev python-dev

this order worked for me in setting up on WSL Ubuntu 18.04

**Comment by bkashyapgithub** [comment]
Hmm, I tried it today, the folloiwng didnt help
sudo apt-get update
sudo apt-get --assume-yes install python3-pip
sudo pip3 install --upgrade pip
sudo apt-get --assume-yes install build-essential libssl-dev libffi-dev python-dev

However w/a to run /tmp/oci_cli_install_tmp_FO1Y helped installation to complete successfully.

**Comment by HamadaGabrIbrahim** [comment]
@bkashyapgithub I tried installing OCI CLI using the installation script on Ubuntu 18.04 and it works fine without any issue.
https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm
Could you please let me know what error are you getting so we can investigate and fix?
