### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by carlossg** [oracle/oci-cli#119]
```
$ oci ce node-pool-options get --node-pool-option-id all
RequestException: ('Connection broken: IncompleteRead(0 bytes read, 109 more expected)', IncompleteRead(0 bytes read, 109 more expected))

$ oci -v
2.4.42
```

**Comment by carlossg** [comment]
I got it to work after adding the OKE policy but the error is very confusing

```
Your tenancy must also have the following required policy statement defined in the root compartment of your tenancy here by a user with administrative privileges:

allow service OKE to manage all-resources in tenancy
```

**Comment by paul-hummel-oracle** [comment]
Thank you for the feedback and observations @carlossg.  I'm glad you were able to get over that hump.
As we work on improving docs and error messages for this problem, we will update here.

**Comment by paul-hummel-oracle** [comment]
Issue should be resolved. We now have a meaningful message:
 
oci ce node-pool-options get --node-pool-option-id all
Response:
    "code": "RelatedResourceNotAuthorizedOrNotFound",
    "message": "Unable to retrieve required tenancy details - please ensure OKE service policy is set up correctly.",
