### ISSUE TITLE
Installation fails with unexpected keyword argument 'allow_abbrev'

### ISSUE THREAD

**Issue by gotochkin** [oracle/oci-cli#130]
Trying to install it on OL 7.6 with Python 2.7.5 and getting error.

Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_mF5w", line 566, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_mF5w", line 496, in main
    parser = argparse.ArgumentParser(description='Install Oracle Cloud Infrastructure CLI.', allow_abbrev=False)
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'

**Comment by shinystar93** [comment]
I get the same Error on WIN10:
At line:330 char:9
+         Write-Error "Executing $PythonExecutable $ArgumentList return ...
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
python --version
Python 3.7.3

Any Ideas or Workarounds ?

**Comment by paul-hummel-oracle** [comment]
Confirmed problem on MacOS with python 2.7.13 as well.  Investigating. . .

**Comment by shinystar93** [comment]
On ubuntu 18 we had a different error: package "distutlis.sysconfig" missing
we managed to install it on ubuntu 18 by executing at first:
   sudo apt-get install python3-distutils

**Comment by paul-hummel-oracle** [comment]
@gotochkin 
Here is a workaround as we work on a fix.  This will involve downloading and editing the install.sh script.

curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh

**Edit install.sh and replace change "INSTALL_SCRIPT_URL"**:
#INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/oracle/oci-cli/v2.5.6/scripts/install/install.py"
INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/oracle/oci-cli/6dc61e3b5fd2781c5afff2decb532c24969fa6bf/scripts/install/install.py"

bash -c ./install.sh

**Comment by gotochkin** [comment]
Thanks Paul. It is good to have workaround and I was able to make it working using two different ways but it is more about other users and fixing the problem.

**Comment by packer-workshop** [comment]
We are working around this same issue on base OL7.6 (Feb22) OCI Base images with:

**Comment by paul-hummel-oracle** [comment]
@packer-workshop thanks for that too.

**Comment by viralmodi** [comment]
The issue has been now fixed on the github master branch tip. It has gone through our internal tests and CLI installation now works on different OSes (Windows and various flavors of Linux) with python 2 and 3. You should be able to use the CLI installer (install.sh) the same way as before and it should work correctly.
FYI @gotochkin @packer-workshop @shinystar93 @paul-hummel-oracle
