### ISSUE TITLE
Honor "Content-Encoding" header for os download operations

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-cli#133]
The Object Storage Service allows specifying a `Content-Encoding` header so objects can be stored in a compressed format. Web browsers honor content encodings (deflate and gzip), so when viewing a URL for a stored object, the contents are decompressed. The `oci os` subsystem ignores the header and doesn't have an option to configure that behavior, so the objects are always fetched as a compressed binary file.

I think a raw object fetch (the current behavior) is a good default. However, it would be incredibly helpful if there were a flag to also allow decompressing objects as they are fetched. Unfortunately, just doing it via piping to a compression utility isn't practical because at that point the header information is lost. A bucket may have a mixture of both compressed and non-compressed files and the `Content-Encoding` header is the only way to determine which any given object is.

**Comment by paul-hummel-oracle** [comment]
@nirvdrum Thank you for your suggestion.
Having parity of functionality with a web browser sounds like a good idea for compressed objects. 
We will update this issue as work progresses.

**Comment by fangerer** [comment]
@paul-hummel-oracle What's the status of this issue? I would also benefit from this feature.

**Comment by kernleee** [comment]
@fangerer @nirvdrum What type of use cases do you expect with this feature? Also what types of content encodings? We are discussing internally on how much support this feature would need since object storage allows you to put in any string in the `Content-Encoding` header.

**Comment by fangerer** [comment]
Our use case is as follows: We do a `bulk-download` of some files to a Linux file system. As Kevin initially described, the download is a _raw fetch_. Since the object storage is serving the files compressed (using deflate), we also end up having compressed files in our download destination. Also, afaik, the downloaded files do not provide any meta data nor magic words. Using the `file` command on the downloaded objects usually just says `data`.
It would be nice if the `oci` client would uncompress on-the-fly.

**Comment by kernleee** [comment]
@fangerer We discussed this feature internally and decided not to implement it. We'd only be able to support a limited number of compression types and introduce a lot of bloat into our code. I'd recommend to write a script to post-process the downloaded objects instead. If you wrote a script for that we'd more than welcome you to submit it into our project as an example for others.

**Comment by nirvdrum** [comment]
As I noted in my original issue, doing this as a post-process step isn't exactly straightforward. oci-cli is handling all the HTTP interaction, so by the time the object is retrieved and accessible by any such script, all of that header information is gone. Adding a file extension isn't appropriate, since that basically unwinds the entire point of the Content-Encoding header in the first place.

Can you sketch out in broad strokes how you think this can be done with a post-processing script? The only thing I can think of is to issue HEAD requests against every object and cache which ones have which Content-Encoding applied. And then referencing that after fetching each file. It feels like the sledgehammer approach though. Being able to hook into the correct rendering phase would help considerably.

As is, it'd probably be more straightforward to just write my own client using the SDK at that point. I've done so in Ruby previously and it required about 10 lines of code, using the standard library's zlib implementation, to handle deflate compression properly. But, distributing a non-official tool introduces its own headaches.

**Comment by paul-hummel-oracle** [comment]
@kernleee 
Python also supports zlib.  
Is there anything that could be hooked into the Python SDK, https://github.com/oracle/oci-python-sdk?  Then just have CLI pass a flag to turn it on?

As for CLI, we have to make sure this will work on windows, linux, macOS. Also I wonder if this would place nicely with the multipart stuff too.

@nirvdrum I'm not sure if you've poked around the CLI and Python SDK code bases. If you have, and also have 10 lines that could be added to make this happen, we would be grateful to evaluate.

**Comment by nirvdrum** [comment]
@paul-hummel-oracle I'd love to help, but I no longer have access to an OCI environment. I've changed companies since I originally reported the issue and that brought along a change in cloud providers. When I get some time, I'll try to set up a dev account and go from there.
