### ISSUE TITLE
Support opc-multipart-md5 checking

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/oci-cli#134]
The CLI should support md5 checksumming for multi-part uploaded objects. By default the CLI uses the multi-part upload feature of the Object Store to improve upload speeds. When the upload is complete the CLI returns the `opc-multipart-md5` value - 
```
...
Split file into 9 parts for upload.
Uploading object  [####################################]  100%
{
  "etag": "167aa4d7-2abc-4341-aaa6-3c176e923ee5",
  "last-modified": "Mon, 08 Apr 2019 21:03:49 GMT",
  "opc-multipart-md5": "JSka2OAb6/CxPOXCOLY4FA==-9"
}
``` 
With the CLI in its current state it's impossible to use the `opc-multipart-md5` checksum to verify that the object was successfully uploaded. The `opc-multipart-md5` is calculated by - 

1. Calculating the md5sum of each part (binary). 
2. Base64 encoding each md5sum independently. 
3. Concatenating the base64 values in order of part #. 
4. Calculate the md5sum of that string. 
5. Append a `-` and the count of parts to that string. 

This checking should be optional and disabled by default. We don't need to ship a complete solution in the first release, we can iterate.  As a MVP the CLI should support an option to output the range of each part and its part number, i.e -  
```
...
{ "etag": "167aa4d7-2abc-4341-aaa6-3c176e923ee5",
  "last-modified": "Mon, 08 Apr 2019 21:03:49 GMT",
  "opc-multipart-md5": "JSka2OAb6/CxPOXCOLY4FA==-9",
  "Parts": {
    "1": [
      "0-50000"],
    "2": [
      "50001-100000"],
    "3": [
      "100001-150000"],
    ...}}
```
This enables the user to manually implement checksumming while minimizing effort to add the feature. Subsequent releases can build on this foundation.

**Comment by vish1** [comment]
Hi @craigcarl-oracle,

Thanks for the enhancement suggestion. 

User can use the following script to calculate the multipart md5 for the file to verify the upload: https://gist.github.com/itemir/f5bc9fded6483cd79c89ebf4ca1cfd30

Sample output: 
```
$ oci os object put --bucket-name Temp --namespace test --part-size 100 --file test.txt
Upload ID: 9518de76-4fe1-e808-6a05-7e03243c21d0
Split file into 4 parts for upload.
Uploading object  [####################################]  100%
{
  "etag": "694629744A6550BFE053C210C10A783B",
  "last-modified": "Sat, 7 Apr 2018 17:51:51 GMT",
  "opc-multipart-md5": "JLqULqTXDMduCddxaaTeQg==-4"
}
$ ./md5multipart.py test.txt 100 --base64
JLqULqTXDMduCddxaaTeQg==-4
```

**Comment by craigcarl-oracle** [comment]
@vish1 This is great, let's get it built into the CLI. It should be optional, `--multipart-checksum`.

**Comment by vish1** [comment]
This feature is part of the latest release 2.6.6 - see [https://github.com/oracle/oci-cli/blob/master/CHANGELOG.rst#266---2019-09-24](release notes)

**Comment by matthewshannon** [comment]
I've created Java code here to do similar multipart upload opc-multipart-md5 header verification/validation.  

https://gist.github.com/matthewshannon/891ac1359a540fd8322e6049f153c1b7
