### ISSUE TITLE
oci network public-ip list with AVAILABILITY_DOMAIN scope requires --compartment-id

### ISSUE THREAD

**Issue by luguoxiang** [oracle/oci-cli#136]
When I try to run "oci network public-ip list --scope AVAILABILITY_DOMAIN --availability-domain XXX", the command failed with 
'''
Error: Missing option(s) --compartment-id.
'''
Which compartment-id should I use, input tenancy id seems not work

**Comment by viralmodi** [comment]
@luguoxiang It should be the compartment-id whose public-ip objects you want to list. I tried the same command with root compartment (tenancy -id) and it works for me. When you used tenancy-id, what error did you get?

**Comment by luguoxiang** [comment]
It seems --availability-domain should using availability-domain name instead of id, after changed to availability-domain name, the command success,
