### ISSUE TITLE
CLI installation fails on macOS with SSL Certificate failure

### ISSUE THREAD

**Issue by viralmodi** [oracle/oci-cli#137]
The issue has been reported by macOS CLI users with Python 3.5, 3.6 and 3.7. Below is the stack trace of the failure with python 3.7:
Traceback (most recent call last):
File “/var/folders/wq/xklj9dpj0dx_9q5q2ymjbfww0000gn/T/oci_cli_install_tmp_XXXX.Se780l5u”, line 135, in create_virtualenv
response = urlopen(VIRTUALENV_DOWNLOAD_URL)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 222, in urlopen
return opener.open(url, data, timeout)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 525, in open
response = self._open(req, data)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 543, in _open
‘_open’, req)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 503, in _call_chain
result = func(*args)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 1360, in https_open
context=self._context, check_hostname=self._check_hostname)
File “/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py”, line 1319, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
ERROR: Failed to download virtualenv package. Please check that your trusted certificates are up to date and include the certificates necessary to verify github.com

**Comment by viralmodi** [comment]
This issue has been root-caused. It is due to OpenSSL certificates not being installed while installing latest versions of Python. This is not a CLI error as such but improper installation of Python on macOS.
Below is excerpt from python.org relevant to this issue:
This variant of Python 3.7 includes its own private copy of OpenSSL 1.1.0.  The deprecated Apple-supplied OpenSSL libraries are no longer used.  This means that the trust certificates in system and user keychains managed by the Keychain Access application and the security command line utility are no longer used as defaults by the Python ssl module.  A sample command script is included in /Applications/Python 3.7 to install a curated bundle of default root certificates from the third-party certifi package (https://pypi.org/project/certifi/).  If you choose to use certifi, you should consider subscribing to the project's email update service to be notified when the certificate bundle is updated.

Based on above, the resolution to this issue is to run 
/Applications/Python 3.7/Install Certificates.command (Use your installed python version in the path)
followed by running CLI Installer. This solution has been tested and known to work.

**Comment by SteveMayze** [comment]
I am facing the same issue. Before I go down the route of this workaround, I was wondering why the install script must download another version of Virtualenv when I already have it installed? The script can successfully detect that I have python3 but does not consider that I could already have virtualenv.

virtualenv --version
15.1.0

**Comment by jdavies** [comment]
Double clicking the file at /Applications/Python 3.8/Install Certificates did the trick for me. Thanks a ton Viralmodi !

**Comment by PeterMerkert** [comment]
For optimizing finding this issue for others, it solved for me the following error as well: `ibrary not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib`

The full error stack (when simply running the curl to install OCI CLI):
```
Traceback (most recent call last):
  File "/Users/petermerkert/bin/oci", line 6, in <module>
    from oci_cli.cli import cli
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci_cli/__init__.py", line 10, in <module>
    from oci import fips
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/__init__.py", line 4, in <module>
    from . import announcements_service, audit, autoscaling, budget, container_engine, core, database, dns, dts, email, events, file_storage, functions, healthchecks, identity, key_management, limits, load_balancer, monitoring, object_storage, oce, ons, resource_manager, resource_search, streaming, waas, work_requests
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/announcements_service/__init__.py", line 7, in <module>
    from .announcement_client import AnnouncementClient
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/announcements_service/announcement_client.py", line 10, in <module>
    from oci.base_client import BaseClient
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/base_client.py", line 24, in <module>
    from .auth import signers
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/auth/__init__.py", line 6, in <module>
    from . import federation_client  # noqa: F401
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/oci/auth/federation_client.py", line 7, in <module>
    from OpenSSL import crypto
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 172, in <module>
    Binding.init_static_locks()
  File "/Users/petermerkert/lib/oracle-cli/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 142, in init_static_locks
    __import__("_ssl")
ImportError: dlopen(/Users/petermerkert/lib/oracle-cli/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/petermerkert/lib/oracle-cli/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
```
