### ISSUE TITLE
inline_help_dump.txt

### ISSUE THREAD

**Issue by gelpenaddict** [oracle/oci-cli#141]
There are several broken links in the documentation or comments to "inline_help_dump.txt".
What happened to this file?

**Comment by paul-hummel-oracle** [comment]
Hi @gelpenaddict , yikes I refactored that into separate files in directory tests/output/inline-help/ back in September 2018.
I did not realize it was used in documentation.

Would you be able to share a couple of documentation references that are now broken b/c of that change?

thank you!
Paul

**Comment by gelpenaddict** [comment]
Sure, I actually found the pieces later. It's a good idea.
I just put "inline_help_dump.txt" in github Search "in this repository" and it found 2, the 2nd is in changelog so probably ok:
scripts/examples/tagging_example.sh
CHANGELOG.rst

**Comment by paul-hummel-oracle** [comment]
Hey, thanks for doing that and pointing out the problem.  I'll get that file updated, and run my own search/grep.
I was afraid there were some Oracle Docs somewhere I did not know about.

**Comment by paul-hummel-oracle** [comment]
The text in tagging_example.sh was updated to reflect the new location of the txt files.
