### ISSUE TITLE
Can't create regional subnet

### ISSUE THREAD

**Issue by manraog** [oracle/oci-cli#142]
When I try to create a regional subnet omiting the argument _--availability-domain_ as is especified [on the docs](https://docs.cloud.oracle.com/iaas/tools/oci-cli/latest/oci_cli_docs/cmdref/network/subnet/create.html) 
```
oci network subnet create --compartment-id ocid1.compartment.oc1.XXXX --vcn-id ocid1.vcn.oc1.XXXX --cidr-block 10.0.0.0/24 --display-name test --prohibit-public-ip-on-vnic false --route-table-id ocid1.routetable.oc1.XXXX --dns-label test
```

 It returns:
```
Usage: oci network subnet create [OPTIONS]

Error: Missing option(s) --availability-domain.
```

On the cli help `oci network subnet create -h`  the argument --availability-domain argument is defined as required.

I don't think this is an issue on the OCI Python SDK since I have created regional subnets with the Ansible modules just by omitting the availability domain argument

**Comment by mross22** [comment]
Hi @manraog can you check which version of the CLI you are using (`oci --version`)? The regional subnets feature was added in version [2.5.1](https://github.com/oracle/oci-cli/blob/master/CHANGELOG.rst#251---2019-02-21) (released in Feb 2019)

**Comment by manraog** [comment]
Thanks I updated the pip module but I didn't realize that I have in my path the version installed by the script, I just updated the script installation following [this instructions](https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliupgrading.htm) and I can create regional subnets.
