### ISSUE TITLE
NewConnectionError('<oci._vendor.urllib3.connection.

### ISSUE THREAD

**Issue by Antic5** [oracle/oci-cli#144]
I cannot upload to the object store. I can ping objectstorage.us-ashburn-1.oraclecloud.com, but cannot upload as I get the error below. I have tried both Mac and Windows and separate networks with the same issue. I have a colleague using the same exact API keys and config that it works fine for. At a bit of a loss here...

The error is as follows from Win PowerShell and same from Mac OS:

oci os object put -ns testground -bn images --file image.ISO
RequestException: HTTPSConnectionPool(host='objectstorage.us.ashburn-1', port=443): Max retries exceeded with url: /n/testground/b/images/o/image.ISO (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000248E714FA20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

**Comment by Antic5** [comment]
Nevermind, the config I was sent had the wrong URL in it: objectstorage.us-ashburn-1.oraclecloud.com instead of objectstorage-us-ashburn-1.oraclecloud.com

**Comment by paul-hummel-oracle** [comment]
Glad you were able to figure it out!
