### ISSUE TITLE
Missing type “emulated” for volume-attachment for CLI

### ISSUE THREAD

**Issue by paul-hummel-oracle** [oracle/oci-cli#146]
https://stackoverflow.com/questions/56139015/missing-type-emulated-for-volume-attachment-for-oracle-cloud-cli

Using the GUI there seems to be three different types of volume attachment, ISCSI, paravirtualized and emulated. However, in the documentation, and the Oracle Cloud CLI, it only offers ISCSI and paravirtualized.

$ oci --version
2.5.10

oci compute volume-attachment attach --help
   --type [service_determined|emulated|iscsi|paravirtualized]
       The  type of volume. The only supported value are "iscsi" and "paravir-
       tualized". [required]

$ oci compute volume-attachment attach --type emulated
Usage: oci compute volume-attachment attach [OPTIONS]

Error: Invalid value for "--type": invalid choice: emulated. (choose from iscsi, paravirtualized)

**Comment by craigcarl-oracle** [comment]
Emulated attachments are only supported as the root volume of instances created from images imported into OCI in emulated mode. The type is set automatically when the image is imported and cannot be changed. Emulated attachments are not supported for data volumes and as a result the AttachVolume API call doesn't support an "emulated" option. See https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/VolumeAttachment/AttachVolume.

**Comment by doggydogworld1** [comment]
Hey Craig, I'm the original poster on stackoverflow.  You say that data volumes do not support emulated type, but this is 100% possible through the GUI.

**Comment by craigcarl-oracle** [comment]
@doggydogworld1 can you attach a screenshot? Here's what I'm seeing - 
![image](https://user-images.githubusercontent.com/20448499/57801585-e233cc80-7708-11e9-8c85-f491b8feea1c.png)

**Comment by doggydogworld1** [comment]
![image](https://user-images.githubusercontent.com/50677328/57806296-af430600-7713-11e9-8960-15a28602cb7f.png)

**Comment by craigcarl-oracle** [comment]
@doggydogworld1 I've confirmed this should work. I can make an emulated attachment to an emulated instance using an older version of the CLI (2.4.4) but not 2.5. 

```
$ oci --version
2.4.4 

$ oci compute volume-attachment attach \
--instance-id ocid1.instance.oc1.phx.abyhqljset66swzctevqobv2t2exfyejjuwzudfhuwlcezrjqugiukti3coq \
--volume-id ocid1.volume.oc1.phx.abyhqljs5cpcbr2liph6yparrfbcugd3n2flkzul3hxrng3hjodyykflr5hq \
--type emulated \
--region us-phoenix-1

{
  "data": {
    "attachment-type": "emulated",
    "availability-domain": "Uocm:PHX-AD-1",
    "compartment-id": "ocid1.tenancy.oc1..aaaaaaaa7wdgkzk6am4qxann4rclbaurqy7wlbcbowyqchmewjbzdc2uc6fq",
    "device": null,
    "display-name": "volumeattachment20190516165306",
    "id": "ocid1.volumeattachment.oc1.phx.abyhqljs6ffx74lsrjcdj2pkpg23jizk7z36qhdzsvodrrxdr6welihndria",
    "instance-id": "ocid1.instance.oc1.phx.abyhqljset66swzctevqobv2t2exfyejjuwzudfhuwlcezrjqugiukti3coq",
    "is-pv-encryption-in-transit-enabled": false,
    "is-read-only": false,
    "lifecycle-state": "ATTACHING",
    "time-created": "2019-05-16T16:53:07.042000+00:00",
    "volume-id": "ocid1.volume.oc1.phx.abyhqljs5cpcbr2liph6yparrfbcugd3n2flkzul3hxrng3hjodyykflr5hq"
  },
  "etag": "18e3fefc898b76a15f3cdddf56d136d5f5d9380e5964148325ae946e14b08825"
}
```
detached volume...
```
$ oci --version
2.5.10

$ oci compute volume-attachment attach \
--instance-id ocid1.instance.oc1.phx.abyhqljset66swzctevqobv2t2exfyejjuwzudfhuwlcezrjqugiukti3coq \
--volume-id ocid1.volume.oc1.phx.abyhqljs5cpcbr2liph6yparrfbcugd3n2flkzul3hxrng3hjodyykflr5hq \
--type emulated \
--region us-phoenix-1

Usage: oci compute volume-attachment attach [OPTIONS]
Error: Invalid value for "--type": invalid choice: emulated. (choose from iscsi, paravirtualized)
```

**Comment by paul-hummel-oracle** [comment]
The fix was released today.
