### ISSUE TITLE
Use correct endpoints for `oci monitoring metric-data post`

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/oci-cli#148]
When attempting to post a metric - 
```
oci monitoring metric-data post \
--auth instance_principal \
--batch-atomicity "ATOMIC" \
--metric-data "$body" ```
```
I receive an error - 
```
ServiceError:
{
    "code": "NotAuthorizedOrNotFound",
    "message": "Incorrect Telemetry endpoint is being used for posting metrics. Please correct the endpoint and retry the request.",
    "opc-request-id": "6902C490C5CE5D9/57BFA006CB/88E644DF73FD",
    "status": 404
}
```
Per the documentation there is no option to change the endpoint - https://docs.cloud.oracle.com/iaas/tools/oci-cli/latest/oci_cli_docs/cmdref/monitoring/metric-data/post.html. Also,
```
$ oci monitoring metric-data post --help
Usage: oci monitoring metric-data post [OPTIONS]

Options:
  --metric-data COMPLEX TYPE 
  --batch-atomicity [ATOMIC|NON_ATOMIC]
  --from-json TEXT
  -?, -h, --help 
```
There is an example (https://github.com/oracle/oci-cli/blob/2ab654c639a50431903dd6b81b0143fb602b0864/scripts/examples/monitoring_metrics_example.sh) that includes an otherwise undocumented `--endpoint` option. 

The endpoints for posting telemetry are documented here - https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apiref.htm
```
https://telemetry-ingestion.ca-toronto-1.oraclecloud.com
https://telemetry-ingestion.eu-frankfurt-1.oraclecloud.com
https://telemetry-ingestion.uk-london-1.oraclecloud.com
https://telemetry-ingestion.us-ashburn-1.oraclecloud.com
https://telemetry-ingestion.us-phoenix-1.oraclecloud.com
```
The endpoints are documented and predictable, customers should not have to manually specify them.

**Comment by vish1** [comment]
Hi @craigcarl-oracle, --endpoint is a CLI specific option available on all CLI commands. It is documented under the top level CLI help (oci --help). I agree that for telemetry the current way of specifying the endpoints is extra work for users. We will take an item to work on improving this command and provide an update soon.

**Comment by kernleee** [comment]
The error response from the service includes a correct endpoint and region to smoothen command usage.
I'll be closing this since there is a decent workaround and we won't be implementing a way to resolve the endpoints.
