### ISSUE TITLE
Metrics example does not run -

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/oci-cli#149]
The post metrics example [here](https://github.com/oracle/oci-cli/blob/2ab654c639a50431903dd6b81b0143fb602b0864/scripts/examples/monitoring_metrics_example.sh) does not run on Oracle Linux 7.6 -
```
$ ./metrics_example_github.sh ocid1.tenancy.oc1..aaaaaaaa7wdgkzk6am4qxann4rclbaurqy7wlbcbowyqchmewjbzdc2uc6fq testns testmet
/usr/bin/env: bash -e: No such file or directory
```
Repro:

- [ ] Launch an OCI instance using the current OL 7.6 image (Oracle-Linux-7.6-2019.05.14-0).
- [ ] SSH to the instance.
- [ ] Install the OCI CLI, `sudo yum install -y  python-oci-cli`.
- [ ] Create a file, `vi metrics_example_github.sh`.
- [ ] Copy and paste the example into the file, save and quit.
- [ ] Make the file executable, `chmod +x metrics_example_github.sh`
- [ ] Run the script as documented (above).

Expected behaviour:
The example should run on all OCI native images; OL 6&7, CentOS 6&7, Ubuntu 16&18.

**Comment by paul-hummel-oracle** [comment]
Hello @craigcarl-oracle ,

Confirmed that the script, monitoring_metrics_example.sh, is not correct.
https://github.com/oracle/oci-cli/blob/2ab654c639a50431903dd6b81b0143fb602b0864/scripts/examples/monitoring_metrics_example.sh#L97

Should be 
oci monitoring metric-data  summarize-**metrics**-data

not
oci monitoring metric-data  summarize-**metric**-data

**Comment by paul-hummel-oracle** [comment]
FYI, This was not a problem on MacOS:
/usr/bin/env: bash -e: No such file or directory

Unfortunately, we do not have a testbed for validating the examples.

**Comment by craigcarl-oracle** [comment]
@paul-hummel-oracle I validated it for you. It doesn't work. What's the plan to make it work?

**Comment by paul-hummel-oracle** [comment]
The fix is in progress.

**Comment by paul-hummel-oracle** [comment]
This was released today.
