### ISSUE TITLE
Metrics example `summarize-metric-data` returns an error -

### ISSUE THREAD

**Issue by craigcarl-oracle** [oracle/oci-cli#150]
Using the metrics example [here](https://github.com/oracle/oci-cli/blob/2ab654c639a50431903dd6b81b0143fb602b0864/scripts/examples/monitoring_metrics_example.sh), after correcting for #149, the script returns an error -
```
$ ./metrics_example_github.sh ocid1.tenancy.oc1..aaaaaaaa7wdgkzk6am4qxann4rclbaurqy7wlbcbowyqchmewjbzdc2uc6fq testns testmet
...
##########################################
# summarize metrics
>>> oci monitoring metric-data summarize-metric-data --compartment-id ocid1.tenancy.oc1..aaaaaaaa7wdgkzk6am4qxann4rclbaurqy7wlbcbowyqchmewjbzdc2uc6fq --namespace testns --query-text testmet[1m].sum() --auth instance_principal
Usage: oci monitoring metric-data [OPTIONS] COMMAND [ARGS]...

Error: No such command "summarize-metric-data".
```
Repro:
- [ ] As in #149 with an added set, replace the first line with `#!/bin/bash -e` before executing the script.
- [ ] Execute the script 

Expected behavior:
The script should return a working example of the summarize metric functionality as well as a summary of any metrics.

**Comment by paul-hummel-oracle** [comment]
Hello @craigcarl-oracle ,

Confirmed that the script, monitoring_metrics_example.sh, is not correct.
https://github.com/oracle/oci-cli/blob/2ab654c639a50431903dd6b81b0143fb602b0864/scripts/examples/monitoring_metrics_example.sh#L97

Should be 
oci monitoring metric-data  summarize-**metrics**-data

not
oci monitoring metric-data  summarize-**metric**-data

**Comment by paul-hummel-oracle** [comment]
This was released today.
