### ISSUE TITLE
Error: Got unexpected extra arguments (–-compartment-id

### ISSUE THREAD

**Issue by wggit** [oracle/oci-cli#155]
Hello,

following commands fails with error: 

 oci resource-manager stack list –-compartment-id "compartment id" --config-file "file path" --profile "profile name"

Error: Got unexpected extra arguments (–-compartment-id <compartment id>)

Appreciate help.

Thank you.

**Comment by srikanthkumbham** [comment]
@wggit I verified this command and it works fine for me. Seems like there's some issue in your `–-compartment-id` option. The first character is not a hyphen so CLI is not recognizing it.

Could you please type(instead of copy-paste) the entire command and let us know if the command is working?

**Comment by wggit** [comment]
Thank you Srikanth. That worked.

**Comment by wggit** [comment]
Thank you

**Comment by erankiraghavendra** [comment]
Hi Team,

I'm working on OCI CLI with resource manager and I'm getting below error while executing the below command. 

oci resource-manager stack create --compartment-id $C --config-source vcn.zip --display-name "My Example Stack" --description "My Tutorial to Create a VCN" --working-directory ""



ServiceError:
{
    "code": "InvalidParameter",
    "message": "Parameter 'configSource' is not valid. Terraform config file is missing in zip file.",
    "opc-request-id": "7754505F3B4C49F2A757C3F74E904A91/9BE9F81756EFBF9D8F22DA50F36D9306/0D57C5F55799B2982F645ADC28A96E11",
    "status": 400
}

Thanks,
Raghavendra Eranki

**Comment by arunmc05** [comment]
Hi,

I have installed the OCI to my local windows PC and running the following command in command prompt.
-------------------------------------------------------------------------------------
Microsoft Windows [Version 10.0.16299.1686]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\mca>oci os object put -ns bmhe7fzgl3tr -bn INVOICES -file C:\Users\mca\Desktop\Holidays.pdf
Error: no such option: -f

C:\Users\mca>
-------------------------------------
can you please what is  the issue.


bmhe7fzgl3tr is the Namespace in the Bucket details
INVOICES is the Bucket name

is this correct.

Thank You,
Arun

**Comment by vish1** [comment]
@arunmc05 Can you please open a new issue - we usually do not follow closed issues and your comment might get lost.

**Comment by vish1** [comment]
@erankiraghavendra Same as above, please open a new issue for your observation.
