### ISSUE TITLE
Broken link "Command Line Reference."

### ISSUE THREAD

**Issue by skydreamerr** [oracle/oci-cli#156]
On the page https://docs.cloud.oracle.com/iaas/Content/API/Concepts/cliconcepts.htm
click on "Command Line Reference"

**Comment by paul-hummel-oracle** [comment]
Hi @skydreamerr ,
we have notified our docs team to get this fixed.
As a work around you can try this link:
 https://docs.cloud.oracle.com/iaas/tools/oci-cli/latest/oci_cli_docs/

Seems that it needs the trailing slash.

**Comment by vish1** [comment]
@skydreamerr Issue has been fixed.
