### ISSUE TITLE
oci bv volume delete -volume-id does not delete volume and return ocicli version

### ISSUE THREAD

**Issue by kennymu** [oracle/oci-cli#159]
Running an oci bv volume delete --volume-id and specifying the volume ID does not delete a volume and only returns the ocicli version.

**Comment by paul-hummel-oracle** [comment]
Can you share your output?

I just tried this and it looked ok to me:

$  oci bv volume delete --volume-id x
Are you sure you want to delete this resource? [y/N]:

**Comment by kennymu** [comment]
Weird.  I updated to version 2.5.14 yesterday to see if that corrected the issue and it still didn’t work.  I hadn’t tried it yet today as I was waiting for the Github email validation to get through our spam filter.  Sorry for wasting your time. It looks to be working 😊  Here's CLI output with compartment and disk IDs removed.

[root@:~/] # oci bv volume create --size-in-gbs 200 --availability-domain 'iRhP:US-ASHBURN-AD-2' --compartment-id ocid1.compartment.oc1 --display-name "testvol"
{
  "data": {
    "availability-domain": "iRhP:US-ASHBURN-AD-2",
    "compartment-id": "ocid1.compartment.oc1 ",
    "defined-tags": {},
    "display-name": "testvol",
    "freeform-tags": {},
    "id": "ocid1.volume.oc1 ",
    "is-hydrated": null,
    "kms-key-id": null,
    "lifecycle-state": "PROVISIONING",
    "size-in-gbs": 200,
    "size-in-mbs": 204800,
    "source-details": null,
    "time-created": "2019-06-19T16:59:43.695000+00:00",
    "volume-group-id": null
  },
  "etag": "092ad44fa0354b38d6a1c51cde562f8a"
}

[root@:~/] # oci bv volume get  --volume-id ocid1.volume.oc1.
{
  "data": {
    "availability-domain": "iRhP:US-ASHBURN-AD-2",
    "compartment-id": "ocid1.compartment.oc1 ",
    "defined-tags": {},
    "display-name": "testvol",
    "freeform-tags": {},
    "id": "ocid1.volume.oc1.iad. ",
    "is-hydrated": true,
    "kms-key-id": null,
    "lifecycle-state": "AVAILABLE",
    "size-in-gbs": 200,
    "size-in-mbs": 204800,
    "source-details": null,
    "time-created": "2019-06-19T16:59:43.695000+00:00",
    "volume-group-id": null
  },
  "etag": "70c5cbb75005610d18d5e2116bf42e7c"
}

[root@:~/] # oci bv volume delete --volume-id ocid1.volume.oc1.
 Are you sure you want to delete this resource? [y/N]: y
PRODUCTION
[root@:~/] # oci bv volume get  --volume-id ocid1.volume.oc1
{
  "data": {
    "availability-domain": "iRhP:US-ASHBURN-AD-2",
    "compartment-id": "ocid1.compartment.oc1 ",
    "defined-tags": {},
    "display-name": "testvol",
    "freeform-tags": {},
    "id": "ocid1.volume.oc1.iad ",
    "is-hydrated": true,
    "kms-key-id": null,
    "lifecycle-state": "TERMINATED",
    "size-in-gbs": 200,
    "size-in-mbs": 204800,
    "source-details": null,
    "time-created": "2019-06-19T16:59:43.695000+00:00",
    "volume-group-id": null
  },
  "etag": "99b55bdd63a8806105ec8f71a5e99784"
}
