### ISSUE TITLE
oci-cli install failing because of spacing on Windows

### ISSUE THREAD

**Issue by andrewtvuong** [oracle/oci-cli#162]
```
===> In what directory would you like to place the install? (leave blank to use 'D:\My Data\Desktop\lib\oracle-cli'):
-- The install directory 'D:\My Data\Desktop\lib\oracle-cli' cannot contain spaces.
```

Fails on both the install.ps1 and install.py scripts found inside ~/oci-cli/scripts/install

Fairly new to Windows syntax, I've tried \(\space), regular expression, quotes. Surprised this isn't a problem for more users.

**Comment by paul-hummel-oracle** [comment]
Hi @andrewtvuong , thank you for reporting this issue.
We will investigate and update the status when more is known.

**Comment by paul-hummel-oracle** [comment]
The message "The install directory 'D:\My Data\Desktop\lib\oracle-cli' cannot contain spaces."  is a validation message returned from CLI setup.
This is not a failure per say but rather it is working how designed.

I will create a ticket to consider supporting this in the future.

**Comment by andrewtvuong** [comment]
@paul-hummel-oracle thanks! The reason I raised the issue is because a lot of the standard Windows images issued include default paths with spaces. 

Maybe I can create a pull request too.

**Comment by paul-hummel-oracle** [comment]
Would be happy to have your contribution.  thank you
