### ISSUE TITLE
requirement for httpsig_cffi

### ISSUE THREAD

**Issue by linqing2004** [oracle/oci-cli#166]
Do you really need this running requirement for httpsig_cffi?
I didn't see anywhere you need it for oci cli. 
Remove the unnecessary requirements please.

**Comment by paul-hummel-oracle** [comment]
Hi @linqing2004, thank you for identifying this. We will check and test whether we can remove this requirement and update this issue with our progress.

**Comment by vish1** [comment]
hi @linqing2004, We have removed this dependency in Version 2.5.22.
