### ISSUE TITLE
Unable to attach / detach volume

### ISSUE THREAD

**Issue by MarcinZablocki** [oracle/oci-cli#17]
It seems that availability-domain value is not passed correctly: 

ServiceError:
{
    "code": "InvalidParameter",
    **"message": "Invalid AD: phx-ad-1",**
    "opc-request-id": "614F756F61E84494BF3732D205FCBEE2/AF47688F2E89823025FB4D6648BEE11B/67B1E71EB5E7C06E09FDE2A318EC62AF",
    "status": 400
}

**Comment by mross22** [comment]
The CLI is just passing through the availability-domain value you supply which needs to be one of the values returned by the following command: (where $C is the compartment id you are in)
`oci iam availability-domain list -c $C`

At first glance it looks like you are missing the compartment specific prefix in the value for availability-domain. An example of a correctly specified AD would look something like this: kIdk:PHX-AD-1 (note: yours will have a different prefix so make sure to find it by using the list command above)

**Comment by mross22** [comment]
Also can you make sure that the region you are targeting with the CLI (either through the region value in your config or with the --region parameter) is the same region which contains the instance and block volume you are trying to attach/detach.  This error can occur if you are targeting one region with the CLI and trying to attach an instance / block volume in another region.

**Comment by MarcinZablocki** [comment]
I made sure. Same config file seems to be working fine with Python SDK. 

The region is set to  us-phoenix-1 in the configuration file, but for some reason, it's incorrect when executing the command.

**Comment by MarcinZablocki** [comment]
Ok. So it's a user error. API call targeting IAD, to manage request in PHX. 
Using --debug helps!
