### ISSUE TITLE
oci waas access-rule update  --generate-param-json-input access-rules fails

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-cli#171]
oci waas access-rule update  --generate-param-json-input access-rules fails :

Option access-rules is not a recognized complex type, so no example JSON can be produced. Invoke help for this command (--help/-h/-?) to see available documentation on this option

from the docs :

oci waas access-rule update [OPTIONS]

Required Parameters

--access-rules [complex type]

This is a complex type whose value must be valid JSON. The value can be provided as a string on the command line or passed in as a file using the file://path/to/file syntax.

The --generate-param-json-input option can be used to generate an example of the JSON which must be provided. We recommend storing this example in a file, modifying it as needed and then passing it back in via the file:// syntax.

Please provide solution

**Comment by kumbham** [comment]
@eugsim1 this issue has been fixed in `2.5.20` version. Could you please upgrade the CLI to the latest version and confirm if this is still an issue?

**Comment by eugsim1** [comment]
Hi now it works with  oci -v
2.5.21

It would be useful to have a warning from the oci that a new version is available 

I m hitting now a new issue i will open another case but FYI now the compartemt-id is not taken from the config DEFAULT section any more

 oci waas waas-policy list --output table --query "data [?\"lifecycle-state\"== 'ACTIVE'].{OCID:\"id\",DISPLAY:\"display-name\",RUNNING:\"lifecycle-state\"}"
Usage: oci waas waas-policy list [OPTIONS]

Error: Missing option(s) --compartment-id.
