### ISSUE TITLE
Not getting all the results back from query

### ISSUE THREAD

**Issue by andrew80k** [oracle/oci-cli#174]
I've got nearly 250 instances in this compartment, yet it is only giving me less than 10 back.  Maybe it's something I'm doing wrong, but if it is, it seems I wouldn't get any results back.

`oci --version
2.5.20`

`oci compute instance list -d --compartment-id=${COMPARTMENT_OCID} --all | grep display`

```
INFO:oci.base_client.4516308432:Request: GET https://iaas.us-phoenix-1.oraclecloud.com/20160918/instances/
DEBUG:oci.base_client.4516308432:Response status: 200
DEBUG:oci.base_client.4516308432:python SDK time elapsed for deserializing: 0.0026374919999998525
DEBUG:oci.base_client.4516308432:time elapsed for request: 1.0924140489999998
time elapsed calling to_dict from render: 0.0012368550000001477
total memory usage before printing: 79.8MiB (83628032)
Time elapsed printing response data: 0.0014692420000002038
total memory usage after printing: 79.8MiB (83673088)
      "display-name": "host2",
      "display-name": "node1",
      "display-name": "node3",
      "display-name": "host3",
      "display-name": "node2",
      "display-name": "host1",
      "display-name": "host4",
```

I've tried pagination and it still just gives the above host list.  If I get an instance OCID of a host that's not in the list, it will return the details of the host with an instance query.  Not sure where I'm going wrong, but I'm hoping you can help me work through it.

Let me know if you need something else.

**Comment by vish1** [comment]
Hi @andrew80k, That is unusual. I am able to get more than 10 results with the same command. Can you check if you have any default settings in the oci_cli_rc file (https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliconfigure.htm)?

**Comment by eugsim1** [comment]
Have you tried with the -d flag to see what the cli is doing ?

**Comment by andrew80k** [comment]
> Have you tried with the -d flag to see what the cli is doing ?

Thanks for jumping in @eugsim1, however, the output above is using the -d flag.

**Comment by andrew80k** [comment]
@vish1,

Thanks for the suggestion, there is almost nothing in my config though, just a region, and my creds.  Not sure how that would cause the behavior above.

**Comment by paul-hummel-oracle** [comment]
@andrew80k I noticed you have "grep display".  Is it possible that some of these instances don't have a display name?

**Comment by joekr** [comment]
@andrew80k can you post the output of 
`oci compute instance list -d --compartment-id=${COMPARTMENT_OCID} --all` like Paul suggested.

**Comment by andrew80k** [comment]
Unfortunately, I no longer have access to the environments I once did as I have left Oracle.  I appreciate those who have chimed in, and I did try this a number of different ways, and the "grep display" was just to shorten the output for the creation of this issue and the results didn't really change without it.  Since I can no longer contribute anything of value to this issue, I will close it.

Thanks everyone.
