### ISSUE TITLE
 oci waas threat-feed update --threat-feeds  --waas-policy-id $waf_policy_id --from-json file://tread-1.json Parameter 'from-json' must be in JSON format.

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-cli#177]
Hello
I have created the json file from the output of the command :

oci waas threat-feed update --generate-param-json-input threat-feeds

[
{
"action": "DETECT",
"key": "bb4d6030-9866-4b76-95a6-88af857c1d7f"
},
{
"action": "DETECT",
"key": "cb24b9d5-eed1-4255-be21-1f218270fb08"
}
]

its a valid json file

jslint confirm this as well but the command fails
the oci waas threat-feed update fails

Why ?

**Comment by kumbham** [comment]
@eugsim1 `--from-json` accepts JSON object and the file contents should be something like this:

```
{
  "threatFeeds": [
    {
      "action": "string",
      "key": "string"
    },
    {
      "action": "string",
      "key": "string"
    }
  ]
}

```

If you are only reading `threat-feeds` from the file, you can directly read it from the file(without using from-json option) something like this:
```
oci waas threat-feed update --waas-policy-id <<id>> --threat-feeds file:///location
```

More info on JSON input can be found here: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/cliusing.htm#AdvancedJSONOptions

**Comment by eugsim1** [comment]
thanks a lot
