### ISSUE TITLE
Show fingerprints after creating key with `oci setup config`

### ISSUE THREAD

**Issue by xtoddx** [oracle/oci-cli#18]
Since the web console uses the fingerprint to identify keypairs, it would be nice to have it echoed after a key is created, with the instructions on uploading a key.

I know it is in the config file, but if the CLI is coaching users on how to upload a keypair, it should also give them the validation information.

**Comment by jodoglevy** [comment]
Fair point, we'll take a look at this and get back to you

**Comment by nathan-vu** [comment]
We're working on this for our next release (actually we seem to be outputting the fingerprint if you supply your own key but not for the one we generate, so this'll close the loop there).

**Comment by nathan-vu** [comment]
We released v2.4.10 of the CLI yesterday (12 October) and we now output the fingerprint when the CLI generates the key.
