### ISSUE TITLE
cant update settings with the oci cli on the waf protection policies

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-cli#181]
i m trying to update just a field in the json file 
{
    "allowedHttpMethods": [
        "GET",
        "POST",
        "HEAD",
        "OPTIONS"
    ],
    "blockAction": "SET_RESPONSE_CODE",
    "blockErrorPageCode": "403",
    "blockErrorPageDescription": "Access blocked by website owner. Please contact support.",
    "blockErrorPageMessage": "Access to the website is blocked.",
    "blockResponseCode": 403,
    "isResponseInspected": true,
    "maxArgumentCount": 4,
    "maxNameLengthPerArgument": 400,
    "maxResponseSizeInKiB": 1024,
    "maxTotalNameLengthOfArguments": 64000,
    "mediaTypes": [
        "text/html",
        "text/plain"
    ],
    "recommendationsPeriodInDays": 5
}

the field isResponseInspected is replace to true

the call 
oci waas waf-config update --waas-policy-id $waf_policy_id  \
--protection-settings           file://protection-settings.json

just gives me a work-oci, but seeing the content it seems to be failed 

{
  "data": {
    "compartment-id": "ocid1.compartment.oc1..aaaaaaaa375sfgxnc24b3rmxjju6ttxv264t6ukiyv42txxfxs3zj2difroa",
    "errors": [
      {
        "code": "0",
        "message": "work request failed, retries exceeded (Aborting, operation result has been marked as failed. Operation is blocking.: UpdateWafSettings failed: {\"errors\":{\"enable_responsebody_inspection\":[\"Response body inspection cannot be enabled due to \u201cGZIP compression\u201d\\n         enabled for the origin servers at the Origin Servers settings.\"]}})",
        "timestamp": "2019-08-07T11:46:57.007000+00:00"
      },
      {
        "code": "FAILED",
        "message": "operation Result error (Aborting, operation result has been marked as failed. Operation is blocking.: UpdateWafSettings failed: {\"errors\":{\"enable_responsebody_inspection\":[\"Response body inspection cannot be enabled due to \u201cGZIP compression\u201d\\n         enabled for the origin servers at the Origin Servers settings.\"]}})",
        "timestamp": "2019-08-07T11:46:57.005000+00:00"
      }
    ],
    "id": "ocid1.waasworkrequest.oc1..aaaaaaaatn7cd5kiaspqlm3ti6gcz7eiikjd576izjhjfvkaufq6gf35pb7q",
    "logs": [
      {
        "message": "updateAddressRateLimitingOp: start",
        "timestamp": "2019-08-07T11:46:56.752000+00:00"
      },
      {
        "message": "updateAddressRateLimitingOp: update start",
        "timestamp": "2019-08-07T11:46:56.752000+00:00"
      },
      {
        "message": "updateAddressRateLimitingOp: finished (16% of request completed)",
        "timestamp": "2019-08-07T11:46:56.752000+00:00"
      },
      {
        "message": "Starting Work Request",
        "timestamp": "2019-08-07T11:46:56.481000+00:00"
      }
    ],
    "operation-type": "UPDATE_WAAS_POLICY",
    "percent-complete": 16,
    "resources": [
      {
        "action-type": "UPDATED",
        "entity-type": "waas",
        "entity-uri": "/20181116/waasPolicies/ocid1.waaspolicy.oc1..aaaaaaaa5fvhdrh3ikem24o3xfkl3ke57m5f6bhch662a4fszaubx6rgvvzq",
        "identifier": "ocid1.waaspolicy.oc1..aaaaaaaa5fvhdrh3ikem24o3xfkl3ke57m5f6bhch662a4fszaubx6rgvvzq"
      }
    ],
    "status": "SUCCEEDED",
    "time-accepted": "2019-08-07T11:46:51.317000+00:00",
    "time-finished": "2019-08-07T11:46:57+00:00",
    "time-started": "2019-08-07T11:46:56+00:00"
  },
  "etag": "W/\"2019-08-07T11:46:51.154Z\""
}

**Comment by paul-hummel-oracle** [comment]
Hi @eugsim1 , we engaged the team responsible for maintaining the backend service and they pointed-out this part of the error message:

_Response body inspection cannot be enabled due to GZIP compression enabled for the origin servers at the Origin Servers settings_.

**Comment by paul-hummel-oracle** [comment]
Internally tracking as WAF-419.

**Comment by srikanthkumbham** [comment]
@eugsim1 It seems like this issue has been fixed recently. Could you please verify if the command works now?

**Comment by eugsim1** [comment]
thanks i will try it later as the deployment might take some hours

**Comment by HamadaGabrIbrahim** [comment]
@eugsim1 Please confirm it works with you so I can close the issue.

**Comment by eugsim1** [comment]
it works for me please close the issue
