### ISSUE TITLE
volume-attachment list is not picking up the compartment-id setting from config

### ISSUE THREAD

**Issue by slmjy** [oracle/oci-cli#185]
**Steps to reporoduce:**

Have a valid `compartment-id=` setting in `~/.oci/config`
Get and instance from this compartment works.
```
oci compute instance get --instance-id <ocid>
```
Getting *the same instance* volume-attachments
```
oci compute volume-attachment list --instance-id <ocid>
```
Gives an error 😿 :
```
Usage: oci compute volume-attachment list [OPTIONS]

Error: Missing option(s) --compartment-id.
```

**Comment by paul-hummel-oracle** [comment]
The first command does not require compartment-id.
`$ oci compute instance get
Usage: oci compute instance get [OPTIONS]
Error: Missing option(s) --instance-id.`

Regarding the second command which does require compartment-id, it should go in ~/.oci/oci_cli_rc and not ~/.oci/config.

`[DEFAULT]
compartment-id=ocid1.compartment.oc1.. . . . . .`

**Comment by slmjy** [comment]
@paul-hummel-oracle Thank you for the clarification, my bad...then the issue is almost invalid. Although I'm still confused, if the cli can get the instance information having just `instance-id`, getting the `compartment-id` seems trivial, so why require `--compartment-id` when `--instance-id` is provided

**Comment by slmjy** [comment]
@paul-hummel-oracle It is required for `oci compute volume-attachment list` even if `--instance-id` is supplied. I understand now that it's just a filter, that seems to be applied after volume attachments were retrieved for the compartment. I guess it could be an enhancement to detect the compartment automatically when the `--instance-id` parameter was supplied

**Comment by slmjy** [comment]
Should I change the issue to properly reflect the outcome of our discussion?

**Comment by HamadaGabrIbrahim** [comment]
@slmjy This issue has been fixed in version 2.9.2 you can only pass the --instance-id and CLI will get --compartment-id by --instance-id

**Comment by againagainst** [comment]
Hi! I believe I am having the same issue with `oci compute image list`, oci-cli v3.3.2 (MacOS).

**Steps to reproduce**: 

- Add the `compartment-id = ...` entry to `~/.oci/config`
- Run `oci compute image list`
- Get the error: `Error: Missing option(s) --compartment-id.`

**Comment by harshkumar-dev** [comment]
You cant specify param values in ~/.oci/config. You can specify compartment-id in a oci-cli-rc file and use --cli-rc-file <File Path> along with your CLI command. 

Please visit this for more detail: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm

use this link to create oci-cli-rc file: https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.9.7/oci_cli_docs/cmdref/setup/oci-cli-rc.html
