### ISSUE TITLE
oci-cli is incompatible with click 7.0

### ISSUE THREAD

**Issue by glaubitz** [oracle/oci-cli#189]
While packaging ```oci-cli``` for openSUSE/SLE I noticed that the package is incompatible with ```click``` 7.0.

Running the ```oci``` will produce the following backtrace when ```click``` 7.0 is installed:

```
glaubitz@suse-laptop:~> oci
Traceback (most recent call last):
  File "/usr/bin/oci", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'cli_rc_file'
glaubitz@suse-laptop:~>
```

Downgrading ```click``` to 6.7 fixes the problem. However, openSUSE Tumbleweed already ships ```click``` 7.0, so ```oci-cli``` should be updated to support the new API.

**Comment by glaubitz** [comment]
> As a note, we typically install CLI as part of a virtualenv. This isolates CLI from package version conflicts as you have pointed out.

Yes, I'm aware of that. However, we can only support software in SUSE Linux Enterprise for our paying customers which we are shipping in the form of RPM packages. So, virtual environments are unfortunately not an option here. Of course, SLE customers can and will sometimes use virtual environments, but usually we are expected to provide RPM packages which receive support from SUSE.

**Comment by smak-oracle** [comment]
The new Click library doesn't support python 2. we can't upgrade it until we decide no longer support python 2. We have to balance customer needs.

**Comment by smak-oracle** [comment]
and we will upgrade Click when we deprecate Python2 at the end of year.

**Comment by smarlowucf** [comment]
There may be other unknown issues related to Click 7.0 however this issue with `cli_rc_file` has an easy fix that works for both Click 7.0 and 6.7.

```
--- /usr/lib/python3.7/site-packages/oci_cli/cli_root.py.orig
+++ /usr/lib/python3.7/site-packages/oci_cli/cli_root.py
@@ -198,7 +198,7 @@
-@click.option('--cli-rc-file', '--defaults-file',
+@click.option('defaults_file', '--cli-rc-file', '--defaults-file',
```

Explicitly setting the parameter name is documented here https://click.palletsprojects.com/en/master/parameters/#parameter-names.

**Comment by ajtvsv07** [comment]
While running `oci-cli commands` inside docker. it throws error the above specified error.
I am using 2.21.0 version of oci-cli
```

Traceback (most recent call last):
  File "/usr/local/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: cli() got an unexpected keyword argument 'cli_rc_file'
```

**Docker base image** is `ubuntu:18.04`
The below commands i use to install oci-cli in docker.

```
ARG CLI_VERSION=2.21.0
RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip
RUN set -ex \
    && wget -qO- -O oci-cli.zip "https://github.com/oracle/oci-cli/releases/download/v${CLI_VERSION}/oci-cli-${CLI_VERSION}.zip" \
    && unzip oci-cli.zip -d . \
    && rm oci-cli.zip \
    && cd oci-cli \
    && pip install oci_cli-2.21.0-py2.py3-none-any.whl
RUN yes | oci setup autocomplete
```

I have installed oci-cli in my local machine and i have done `oci setup config` also.
i use this docker command to run : `docker run --rm -p 8000:8000 -v ~/.oci:/root/.oci -tid cpu_docker_container`

**Comment by vish1** [comment]
OCI CLI now uses click 7.0 from release version 3.0.0.
