### ISSUE TITLE
Use full path when writing `key_file` in `setup config`

### ISSUE THREAD

**Issue by xtoddx** [oracle/oci-cli#19]
I wanted my config and key files to live in the directory where I created my virtualenv, instead of in ~/.oci (so that I could experiment in a directory instead of writing more global state). When asked for my key directory I typed `.` for the current directory. Now when I run `oci` form a different directory I get configuration failures and my commands don't work, eg: `IOError: [Errno 2] No such file or directory: './iad_key.pem'`

It would be great for the setup process to always expand the full path of the key file when it writes the config setting.

**Comment by jodoglevy** [comment]
Thanks, we're working on this for our next release

**Comment by mross22** [comment]
This is fixed in our latest release: https://github.com/oracle/oci-cli/releases/tag/v2.4.10
