### ISSUE TITLE
Marketplace images

### ISSUE THREAD

**Issue by Erniemoore** [oracle/oci-cli#193]
Is there a way to pull marketplace image and other data out of OCI

**Comment by mattiarossi** [comment]
A little late to the party, but you can use oci-cli and raw-http requests
Here is an example script that fetches an image listing and id from using the marketplace description and resource version:
https://gist.github.com/mattiarossi/a7e5ceff8de0da0a12393a27ffc5c6e8

```
./getMarketplaceImageId 'FortiGate Next-Gen Firewall (BYOL)' '6.4.0'
{
  "listingId": "ocid1.appcataloglisting.oc1..aaaaaaaam7ewzrjbltqiarxukuk72v2lqkdtpqtwxqpszqqvrm7likfnpt5q",
  "listingResourceId": "ocid1.image.oc1..aaaaaaaaa5u7qtj3j3um4zryg3qkn6if2sqctqjfh46pdq5z56kq6zagg4va",
  "listingResourceVersion": "6.4.0_SR-IOV_Paravirtualized_Mod",
  "timePublished": "2020-04-14T01:05:07.615Z"
}
```
