### ISSUE TITLE
Using the Powershell script and Getting error calling LaunchInstance to create new instance

### ISSUE THREAD

**Issue by Noam-T** [oracle/oci-cli#195]
Hi,

I know this is the CLI area but I think it could be similar enough.
I am using the PowerShell script to call the OCI REST API's.
The GET and some POST are working fine.
The LaunchInstance returns a generic error (400) Bad Request without any details.

Thanks,
Noam

The PS Command line: .\oci-rest.ps1 -method post -ocihost iaas.eu-frankfurt-1.oraclecloud.com -target "/20160918/instances" -body C:\Oracle\request1.json

The json body:
{
  "availabilityDomain":  "LxSR:EU-FRANKFURT-1-AD-1",
  "compartmentId":  "ocid1.compartment.oc1..aaaaaaaaypdpv2aq.......",
  "dedicatedVmHostId":  null,
  "definedTags":  {},
  "displayName":  "NoamTest1",
  "extendedMetadata":  {},
  "faultDomain":  "FAULT-DOMAIN-2",
  "freeformTags":  {},
  "imageId":  "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaa7gj6uot.......",
  "ipxeScript":  null,
  "launchMode":  "NATIVE",
  "metadata":  {},
  "shape":  "VM.Standard2.1",
  "sourceDetails":  {
						"sourceType":  "image"
					},
  "agentConfig":  {
					  "isMonitoringDisabled":  false,
					  "isManagementDisabled":  null
				  }
}

**Comment by paul-hummel-oracle** [comment]
I am also experiencing a problem with this API. I tried to reduce the values being passed to narrow down the problem, but still had no luck.

{
"availabilityDomain": "Iocq:PHX-XX-1",
"compartmentId": "ocid1.compartment.oc1..aaaaaaaa......",
"displayName": "Test",
"imageId": "ocid1.image.oc1.phx.aaaaaaaa.........",
"shape": "VM.Standard2.1"
}

**Comment by paul-hummel-oracle** [comment]
Tried similar with the equivalent bash shell script, oci-curl.sh and also had a problem:

$ ./oci-curl.sh 
{
  "code" : "InvalidParameter",
  "message" : "Invalid availabilityDomain"
}
400

**Comment by paul-hummel-oracle** [comment]
Even CLI provides an error:
$ oci compute instance launch --availability-domain Iocq:PHX-AD-1 --compartment-id $OCI_CLI_COMPARTMENT_ID --shape "VM.Standard2.1"
ServiceError:
{
    "code": "InvalidParameter",
    "message": "Invalid subnet: null",
    "opc-request-id": "307290754D714C539D9E83376A7EF39B/9EA5528B6904EA3D0CCFE18EBB5E50FC/09FFEDC144B88C625C08F002A38DB38A",
    "status": 400
}

**Comment by paul-hummel-oracle** [comment]
@Noam-T 
After adding "subnetId" to the post body, it worked for me.

{
"availabilityDomain": "Iocq:PHX-AD-1",
"compartmentId": "ocid1.compartment.oc1..aaaaaaaa......",
"displayName": "PdhTest",
"imageId": "ocid1.image.oc1.phx.aaaaaaaa......",
"shape": "VM.Standard2.1",
"subnetId": "ocid1.subnet.oc1.phx.aaaaaaaa....."
}

I'm not 100% sure whether this is a documentation bug or a service bug.

**Comment by Noam-T** [comment]
Hi Paul,

Thanks you very much for your help.
I tried the json that you suggested and still the same generic error.
Unfortunately, I am not that familiar with Powershell to debug it properly.
I did notice that I get HTTP error "404 not found"  and not "400 bad request".
So I used the one of the default subnet ID and not the subnet I created and started to get "400 bad request".
I am trying to use Instance Configuration and Instance pool in hope that it will work.
I will update on this thread.
If you have any more ideas, I would highly appreciate that.

Thanks,
Noam

**Comment by paul-hummel-oracle** [comment]
I'm not that strong with Powershell either, and that's why I tried using CLI and oci-curl to see if I could get the same working in a different tool to make sure the API and privs were good.
When you use CLI with --debug option, you can see the json it sends to the server.

Perhaps you can add "echo" or "Console.WriteLine" statements to the Powershell to help debug.

**Comment by Noam-T** [comment]
Hi Paul,

With much luck, I found the problem yesterday. It was the Tenant limits.
Because I did not get any specific error, it took a while to find it.
BTW, I used your JSON.

Thanks a lot for your help,
Noam
