### ISSUE TITLE
Health Checks: missing validation

### ISSUE THREAD

**Issue by dariagrudzien** [oracle/oci-cli#197]
We found two places in which validation is missing:

- When creating HTTP monitors and making mistakes in targets (not separating the path from the host), the monitor still gets created but with incorrect target. We noticed that this validation exists in the GUI.
- When creating either HTTP or ping monitors with timeout set to 60s, the monitor gets created but the timeout is not set (related to #196 )

We would expect error messages instead, or automated correction (e.g. splitting host and path).

**Comment by kensthilaire** [comment]
Thank you for reporting these issues with the HealthChecks API. We'll have a look and make any necessary corrections in an upcoming version of the API.

**Comment by mandyht** [comment]
Issue resolved in an internal ticket.
