### ISSUE TITLE
Default --compartment-id to tenant id

### ISSUE THREAD

**Issue by xtoddx** [oracle/oci-cli#20]
Since a tenant OCID is a valid --compartment-id value, it would be great if I didn't have to specify it again (it already lives in my config file) for cases when I'm using the root compartment.

Even if the desire is to encourage users to compartmentalize, a shortcut like --compartment-id=ROOT could save copy-pasting, rekeying errors, etc while still encouraging the use of the --compartment-id flag.

**Comment by jodoglevy** [comment]
Thanks for reporting. We're working on a solution that should make this easier (ability to specify defaults for all CLI parameters, including --compartment-id). Stay tuned!

**Comment by nathan-vu** [comment]
We released v2.4.10 of the CLI yesterday (12 October) and as part of that release we introduced support for specifying command defaults in a file so that folks don't have to keep typing them. We support both global (i.e. applies to all CLI commands) and more granular (e.g. apply to a specific group of commands, apply to a specific command) defaults. 

Additional information can be found in the docs: https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cli.htm#config under the section _Using a File for Default Values_

**Comment by xtoddx** [comment]
Thanks. To make sure I'm clearly understanding the documentation: my --profile flag now chooses *both* the configuration and the defaults section to use?

Assume a config file (./my-config)
```
[PHX]
region=us-phoenix-1
tenancy=ocid1.tenancy.oc1..XXX
user=ocid1.user.oc1..XXX
key_file=XXX
fingerprint=X:X:X
```

And a defaults file (./my-defaults)
```
[PHXPRIV]
compute.instance.launch.subnet-id=ocid1.subnet.oc1.phx.XXX
# more stuff here

[PHXPUB]
subnet-id=ocid1.subnet.oc1.phx.YYY
# more stuff here
```

And I run `opc --config-file ./my-config --defaults-file ./my-defaults --profile PHX ...` (because this is how I'm accustomed to targeting a region), I can't pick up either of the defaults as-is? Is the suggested workaround in this scenario to create a ./my-defaults-pub and ./my-defaults-priv file and have both sections named PHX (or will DEFAULT be sufficient in those files)?

I'm just trying to clarify what is the current best-practice for these situations. Multiple defaults files seems workable for me, but I want to make sure I'm not misunderstanding the intent of defaults files or using them unexpectedly.

FWIW, the --help text for the --profile flag doesn't mention its control over the defaults file:
```
  --profile TEXT         The profile in the config file to load.  [default:
                         DEFAULT]
```

**Comment by nathan-vu** [comment]
Apologies for the confusion. 

> my --profile flag now chooses both the configuration and the defaults section to use?

Yes, sorry that the help text wasn't updated here. We'll get it updated.

***

> Is the suggested workaround in this scenario to create a ./my-defaults-pub and ./my-defaults-priv file and have both sections named PHX (or will DEFAULT be sufficient in those files)?

Yes, in this case you'd need to create separate files. The sections would need to be named PHX (unfortunately we can't locate a section if it doesn't exist in the file). 

As an aside, if you did have values you wanted to inherit down to each specific section of the config file, then having a [DEFAULT] section with common values is the way to go there.

**Comment by lee212** [comment]
@nathan-vu , is this the document about the cli configuration? https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cliconfigure.htm . It seems one you mentioned is moved.

I created `$HOME/.oci/--oci-rc-file` and specified compartment-id and namespace-name as the document instructed but it seems my `oci` CLI does not pick it up unless I specify the location of rcfile like `--cli-rc-file ~/.oci/--cli-rc-file` What am I missing here?

**Comment by nathan-vu** [comment]
@lee212 your file name need to be changed. If the file is in `~/.oci/oci_cli_rc` then it will be picked up automatically and you don't have to provide an explicit `--oci-cli-rc` parameter. Please see: https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cliconfigure.htm#UsingaFileforCLIConfigurations

**Comment by lee212** [comment]
It worked, Thanks!

I was confused about `~/.oci/--cli-rc-file` at the sub section (_Default Values File Name and Location_) in the document.

**Comment by nathan-vu** [comment]
We'll get that part of the docs fixed up. Sorry about the confusion here.
