### ISSUE TITLE
bulk pulls of data from OCI

### ISSUE THREAD

**Issue by Erniemoore** [oracle/oci-cli#206]
In pulling data from OCI using the CLI we are experiencing hangs at irregular intervals.

Is there a contact who can help understand why this happens?

Is there a better way to do bulk pulls of data from OCI that we can use for management purposes other than using the CLI?

**Comment by paul-hummel-oracle** [comment]
@Erniemoore would you be able to reproduce the problem and include the "--debug" option and capture the output and include it here?

**Comment by vish1** [comment]
Closing the ticket due to no response.
