### ISSUE TITLE
TypeError: update_database() got an unexpected keyword argument 'backup_destination'

### ISSUE THREAD

**Issue by wggit** [oracle/oci-cli#208]
oci --version
2.6.7

command:

oci db database update --database-id <db ocid>  --defined-tags file://$JSON_FILE  --config-file /usr/.oci/config  --profile <profile_name> --force

Error:

TypeError: update_database() got an unexpected keyword argument 'backup_destination'

Thank you.

**Comment by srikanthkumbham** [comment]
@wggit thanks for reporting this. Seems like this bug was introduced recently, we will provide the fix ASAP.

**Comment by srikanthkumbham** [comment]
meanwhile as a workaround, please pass `--auto-backup-enabled` option with a default(false) value.  

oci db database update --database-id --defined-tags file://$JSON_FILE --config-file /usr/.oci/config --profile <profile_name> --auto-backup-enabled false/true

**Comment by paul-hummel-oracle** [comment]
Fixed in 2.6.9
