### ISSUE TITLE
oci waas waf-log list doent get any logs from waaf

### ISSUE THREAD

**Issue by eugsim1** [oracle/oci-cli#212]
oci waas waf-log list \
--waas-policy-id  ocid1.waaspolicy.oc1..aaaaaaaaqaxiq4pepvbpzlg3q6w5xadx354cu2ap245rm7msmtoqc42q56nq

Logs from the GUI

/ | 141.143.213.37 |   | Access | Mon, Oct 14, 2019, 10:15:54 UTC
-- | -- | -- | -- | --

i m getting empty lists ... command broken

**Comment by kernleee** [comment]
The command looks to be working now atleast, so I'll be closing this issue. If it is still not working, feel free to reopen the issue. Relevant page for logs: https://docs.cloud.oracle.com/en-us/iaas/Content/WAF/Tasks/logs.htm
