### ISSUE TITLE
Only "oci session" and "oci setup" are available. Other commands missing.

### ISSUE THREAD

**Issue by corso75** [oracle/oci-cli#213]
After run "oci" the help is shown but there are only two supported commands are displayed:

> Commands:
>   session  Session commands for CLI
> setup    Setup commands for CLI

The try to get a namespace from oci using the command "oci os ns get" failed with the error:
> ~/virtualenv_workspace> oci os ns get
> Usage: oci [OPTIONS] COMMAND [ARGS]...
> Error: No such command "os".
> 

The other commands return the same error.

P.S. The oci-cli version 2.5.1 works.

**Comment by paul-hummel-oracle** [comment]
@corso75 thank you for reporting this bug.
I suspect you have found something that might be related to the specifics of installation.
We do have other users using v2.6.8.

What version of python are you using and on what platform?
Also, what method did you use to install/update the CLI?

The service subcommands such as "os" are dynamically discovered. Is there anything about your setup that might be unique that we overlooked?

**Comment by paul-hummel-oracle** [comment]
Somewhere before v2.5.22 we redid some of this "discovery" code I mentioned, so it makes sense that v2.5.1 behaved differently.

**Comment by corso75** [comment]
Host is Ubuntu 18.04.
Create virtualenv:
> python3 -m venv oci_cli

Activate:
> source oci_cli/bin/activate

Installation oci-cli:
> pip3 install ~/oci-cli-2.6.8/oci_cli-2.6.8-py2.py3-none-any.whl

Python path: 
> ~/virtualenv_workspace> which python
> python is ~/virtualenv_workspace/oci_cli/bin/python
> python is /usr/bin/python

Python version:
> ~/virtualenv_workspace> ~/virtualenv_workspace/oci_cli/bin/python
> Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> 

So i guess the first path is used to run Python.

**Comment by corso75** [comment]
i see that the structure of packages in the "\~/virtualenv_workspace/oci_cli/lib64/python3.6/site-packages" is different from 2.5.1. There are no any packages like "oci_cli_*" in the "site-packages" except: oci-2.6.0.dist-info, oci, oci_cli, oci_cli-2.6.8.dist-info. 
All packages with the names starting from "oci_cli_" are located in the folder "site-packages/services" in the subfolders like "~/virtualenv_workspace/oci_cli/lib64/python3.6/site-packages/services/core/src.

**Comment by paul-hummel-oracle** [comment]
Great, thanks for the details.  Let me try that out.

We hadn't made the switch to using venv from virtualenv yet b/c of py2.  Plan to do that later this year or early next year when we end support for py2.

**Comment by corso75** [comment]
Doesn't matter to use virtualenv or venv. I tried with virtualenv too. The same result.
Create:
> virtualenv oci_cli

Installl: 
> pip install ~/OracleCloud/oci-cli-2.6.8/oci_cli-2.6.8-py2.py3-none-any.whl

Activate:
> source oci_cli/bin/activate

Execute: 
> ~/virtualenv_workspace> oci os ns get
> Usage: oci [OPTIONS] COMMAND [ARGS]...
> Error: No such command "os".

**Comment by corso75** [comment]
paul, would you show the structure of Python "site-packages" in your virtual environment? I want to see where the "oci_cli_*" packages are located for the working variant of oci_cli v2.6.8.

**Comment by paul-hummel-oracle** [comment]
@corso75 I was able to repro the problem you are seeing.
We have a bug that needs some investigation.  But in the meantime, if you rename your virtual environment to something other than "oci_cli", I think that will work.  This worked for me:

python3 -m venv ocicli
. . . .

**Comment by paul-hummel-oracle** [comment]
\# cd ocicli/lib/python3.6/site-packages/
(ocicli) root@c7515939393a:~/ocicli/lib/python3.6/site-packages# ls -ld oci*
drwxr-xr-x 34 root root 4096 Oct 15 22:08 oci
drwxr-xr-x  2 root root 4096 Oct 15 22:08 oci-2.6.0.dist-info
drwxr-xr-x 10 root root 4096 Oct 15 22:08 oci_cli
drwxr-xr-x  2 root root 4096 Oct 15 22:08 oci_cli-2.6.8.dist-info

(ocicli) root@c7515939393a:~/ocicli/lib/python3.6/site-packages# ls oci_cli
__init__.py  bin             cli_constants.py   cli_session.py          cli_util.py   final_command_processor.py  json_skeleton_utils.py  scripts          version.py
__pycache__  cli.py          cli_exceptions.py  cli_setup.py            custom_types  formatting.py               oci_template.py         string_utils.py
aliasing     cli_clients.py  cli_root.py        cli_setup_bootstrap.py  file_filters  help_text_producer          retry_utils.py          util

(ocicli) root@c7515939393a:~/ocicli/lib/python3.6/site-packages# ls services/
__init__.py            audit        container_engine  dns    events        healthchecks    limits         object_storage  resource_manager  waas
__pycache__            autoscaling  core              dts    file_storage  identity        load_balancer  oce             resource_search   work_requests
announcements_service  budget       database          email  functions     key_management  monitoring     ons             streaming

**Comment by corso75** [comment]
Paul, your workaround works. Thanks. 
P.S. Glad to hear that the issue hasn't stayed in the unknown state and has been confirmed.

**Comment by paul-hummel-oracle** [comment]
Renaming bug title to something more descriptive.  Here is the original title:
The latest 2.6.8 version has an empty command list (completely broken)

**Comment by paul-hummel-oracle** [comment]
internally tracked as 7101.

**Comment by HamadaGabrIbrahim** [comment]
@corso75 With the latest version 2.8.1. this issue is fixed.
