### ISSUE TITLE
oci image import missing important features

### ISSUE THREAD

**Issue by dbarj** [oracle/oci-cli#215]
This is a request for new feature. The oci-cli still lacks some features that we already have in the OCI web-console for image import. I can mention 2 that are very important:

1 - source-image-type OCI

$ oci --cli-rc-file /dev/null compute image import from-object-uri ... --source-image-type OCI
Usage: oci compute image import from-object-uri [OPTIONS]

Error: Invalid value for "--source-image-type": invalid choice: OCI. (choose from QCOW2, VMDK)

2 - Operating System and Operating System Version (most for Windows licensing feature).

I have some automations that move computes among regions and I'm still excluding Windows OS to avoid non-compliance issues.

Thanks,
RJ

**Comment by paul-hummel-oracle** [comment]
@dbarj thank you for using the CLI and for giving feedback for features to make it more useful.

Regarding 1 -- the CLI is build on top of this underlying API -- 
https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/Image/CreateImage
https://docs.cloud.oracle.com/iaas/api/#/en/iaas/20160918/datatypes/ImageSourceDetails
The sourceImageType only accepts values for QCOW2 and VMDK.

We'll have to research what the Console UI is doing with regards to the "OCI" option.

I didn't quite understand your request for the second point.  What is it that you wanted here?

**Comment by dbarj** [comment]
Hi @paul-hummel-oracle , thank you for your attention.

For the second item, if you check https://docs.cloud.oracle.com/iaas/Content/Compute/Tasks/imageimportexport.htm there is now a new option where you can specify what is the target Operating System type and version. So if you specify "Microsoft Windows", it will also request the version. When specified, you will also be charged for the Windows licensing.

This option is available on the web-console. I would like to also have it on the oci-cli, if possible.
![image](https://user-images.githubusercontent.com/22628348/67811627-fa5f9400-fa7b-11e9-9b5e-b185d57b6fc2.png)

Thanks,
RJ

**Comment by paul-hummel-oracle** [comment]
For the second point, Console UI is being clever and doing something nice for user interface.  Whereas for the APIs and CLI the image has both pieces of information together -- i.e., we still support the same number of Windows images.

Running something like this would give you an idea of how many windows images/versions are available.
oci compute image list -c $COMPARTMENT_ID | grep Windows -A1

**Comment by paul-hummel-oracle** [comment]
For the second point, Console UI is being clever and doing something nice with the user interface.  Whereas for the APIs and CLI the image has both pieces of information together -- i.e., we still support the same number of Windows images.

Running something like this would give you an idea of how many windows images/versions are available.
oci compute image list -c $COMPARTMENT_ID | grep Windows -A1

**Comment by kernleee** [comment]
There was a feature added `oci compute image import from-object/from-object-uri` to specify operating system, operating system version. https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.12.5/oci_cli_docs/cmdref/compute/image/import/from-object.html

Still not sure about specifying OCI as an image type however.

**Comment by kernleee** [comment]
There currently isn't a way for us to support the 'OCI' source image type because the API only allows QCOW2, VMDK. I'll be closing this as a result. Feel free to reopen if necessary
