### ISSUE TITLE
list-vnics exits 0 even when host is terminated

### ISSUE THREAD

**Issue by thehhugg** [oracle/oci-cli#220]
Expected behavior: 
`oci compute instance list-vnics` should return an error code or JSON response indicating the host is terminated or no vnics exist. 

Observed behavior:
`list-vnics` on a terminated host results in an empty response and exit code 0. 

Example: 
```
➜  ~ oci compute instance list-vnics --instance-id ocid1.instance.oc1.iad.anuwcljsv66vvnicrxxobks5k2rxmwtuhftlbtgtahuxzlazgkr5jugjgwqa | echo $?
0
➜  ~ oci compute instance list-vnics --instance-id ocid1.instance.oc1.iad.anuwcljsv66vvnicrxxobks5k2rxmwtuhftlbtgtahuxzlazgkr5jugjgwqa
➜  ~
```

**Comment by srikanthkumbham** [comment]
@thehhugg thanks for reporting this issue. I'll file an internal bug for our team to fix this.

**Comment by HamadaGabrIbrahim** [comment]
@thehhugg This issue has been fixed. it returns now an error message.
