### ISSUE TITLE
error setting up oci-cli manually

### ISSUE THREAD

**Issue by shreikurao** [oracle/oci-cli#227]
I'm trying to setup oci-cli manually & used this command - "python setup.py install"
It executed many steps before hitting the below error:

Extracting oci_cli-2.6.14-py3.8.egg to c:\users\sreekanth manjunatha\appdata\local\programs\python\python38\lib\site-packages
error: [Errno 2] No such file or directory: 'c:\\users\\sreekanth manjunatha\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\oci_cli-2.6.14-py3.8.egg\\services\\dts\\src\\oci_cli_dts\\physical_appliance_control_plane\\client\\__pycache__\\physical_transfer_appliance_client_composite_operations.cpython-38.pyc'

Any help on this please?

**Comment by paul-hummel-oracle** [comment]
setup.py is used by pip command.

Assuming you have cloned the GitHub repo, from the oci-cli, please try 
pip install -e .

**Comment by vish1** [comment]
@shreikurao Please update if you are still facing issues. If not, please close the issue.

**Comment by shreikurao** [comment]
I was able to workaround it by copying python and oracle-cli.zip 
Thanks.
