### ISSUE TITLE
install oci cli on windows 10 - doesn't work

### ISSUE THREAD

**Issue by dumians** [oracle/oci-cli#230]
Dear Team,

I try to install OCI cli on Windows 10 x64 with all requirements installed and the install script it is broken with :
Building wheels for collected packages: cryptography

  Building wheel for cryptography (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\jd\lib\oracle-cli\scripts\python.exe' 'c:\users\jd\lib\oracle-cli\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\jd\AppData\Local\Temp\tmpaxz4owc3'
       cwd: C:\Users\jd\AppData\Local\Temp\pip-install-llseo27j\cryptography

Even if i install the cryptography & pep517 package manualy and try to upgrade
with : pip  install --cache-dir 'C:\\Users\\jd\\AppData\\Local\\Temp\\tmp9vfzan8n'  oci_cli --upgrade --no-use-pep517

I could for sure compile all libs myself but i think that i is not the experience that we expect for the people that's use OCI.

regards,
Johannes
EMEA Chief Customer Architect

**Comment by kernleee** [comment]
Hi Johannes,

Could you try changing the requirements for the cryptography package to the latest version, 2.8, from our present one, 2.4.2 and see if that will fix your issue.

**Comment by vish1** [comment]
@dumians Which version of python are you running?

**Comment by dumians** [comment]
@vish1 i'm using 3.8.0 , i try it on different machine wit 3.7.5 works.

**Comment by hyder** [comment]
I have the same problem with Python 3.8.1

**Comment by dumians** [comment]
@vish1  i use 3.8.0

**Comment by dumians** [comment]
hi Guys, i get that running in following way.

#set c++ compiler variables target platform
&"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

#set path to openssl include & libs - are needed for python cryptography library wheel
set LIB="C:\Program Files\OpenSSL\lib";%LIB%
set INCLUDE="C:\Program Files\OpenSSL\include";%INCLUDE%

#run 
pip install oci-cli

**Comment by kernleee** [comment]
@dumians The latest release has a version bump to cryptography that should have fixed the issue.

**Comment by vish1** [comment]
Issue has been fixed as indicated by previous comment.
