### ISSUE TITLE
pip install oci-cli fails on install

### ISSUE THREAD

**Issue by ghoddg** [oracle/oci-cli#231]
Hi,
I am trying to install oci-cli but getting below error, Please help.

sudo pip install oci_cli-2.7.0-py2.py3-none-any.whl
Processing ./oci_cli-2.7.0-py2.py3-none-any.whl
Collecting oci==2.8.0 (from oci-cli==2.7.0)
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143bd0>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143d50>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143910>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647143710>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/oci/
Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff647138190>: Failed to establish a new connection: [Errno 113] No route to host',)': /simple/oci/
Could not find a version that satisfies the requirement oci==2.8.0 (from oci-cli==2.7.0) (from versions: )
No matching distribution found for oci==2.8.0 (from oci-cli==2.7.0)

**Comment by vish1** [comment]
@ghoddg Installation requires access to pypi.org. Please check the network connection for the machine and see if the site (pypi.org) is accessible. Also check if any proxy setup is needed for external access.

**Comment by vish1** [comment]
@ghoddg Were you able to move forward and install CLI?

**Comment by vish1** [comment]
Closing this issue due to lack of response.
