### ISSUE TITLE
Compute Instance Resize

### ISSUE THREAD

**Issue by twmcelroy** [oracle/oci-cli#232]
I see compute instance resize has been added to the CLI and Terraform Provider. When I attempt to enable this I just get the instance information returned. This is in a commercial tenancy, us-phoenix-1. Has it not been activated? 

Command: 
oci compute instance update --instance-id <instance ocid> --shape VM.Standard2.2 --force 

Response: 
Instance information, same as oci compute instance get --instance-id <instance ocid>

**Comment by vish1** [comment]
@twmcelroy Yes, this seems to be an issue and will be fixed soon.

**Comment by twmcelroy** [comment]
Great news Vish. Any ETA? Is this a fix on the CLI requiring a release or backend? We have a go live soon and I’d love to use this rather than recover from a backup (helps keeping the same IP and host name).

**Comment by vish1** [comment]
@twmcelroy The fix will be in the backend and will not require any CLI update. It is expected to be released in the upcoming week.

**Comment by twmcelroy** [comment]
Thank you vish! I’ll test next week. This is good news for our project. I’ll just have to keep them patient

**Comment by twmcelroy** [comment]
Will this only be available on Commercial (OC1) or Government (OC2) as well? I would need in Government this week or we would resize by backup and rebuild.

**Comment by twmcelroy** [comment]
Any updates if the bug was fixed last week? And if it will be available in Gov?

**Comment by twmcelroy** [comment]
I have tested it since the blog post was released today and it now works in Gov and commercial. We can close this issue.

**Comment by vish1** [comment]
Thanks for the update @twmcelroy. Closing the issue.
