### ISSUE TITLE
how to check block volume state if it is attached to instance ?

### ISSUE THREAD

**Issue by givesussmile-hoon** [oracle/oci-cli#233]
i am trying to build automation to cloning & deleting block volume by using oci-cli.

however, i faced two problem.

first, i have trouble to change date format "time-created". 

i want to compare localtime with "time-created" for deleting 7 days old volume.

but, i cant find a way to transform "time-created" to be another date format by using jq.

ex) "time-created": "2019-12-29T12:11:52.358000+00:00"

second,  following is the message i found when i tried to delete the volume attached to a instance

sure, it was failure with below message : 

{
    "code": "Conflict",
    "message": "Volume ocid1.volume.oc~~~... may not be deleted while attached to an Instance.",
    "opc-request-id": "C05ADA1C1FE24B83BDAFC9526C2019BD/53272540EB028A41B3DD0BC0D195051A/3C3A65D36C9DB05430C993409A53812F",
    "status": 409
}

however, i didnt want to try any deleting attempt for attached volume.

so i was going to find if attached volme state in json message.

but i cant find it ,too.

how can i solve this problems?
please help me.

**Comment by vish1** [comment]
Hi @givesussmile-hoon, You can use this command `oci compute volume-attachment list` to get a list of all the volumes attached to instances.

**Comment by vish1** [comment]
@givesussmile-hoon Were you able to use the provided command to make progress?

**Comment by vish1** [comment]
Closing this issue due to lack of response.

**Comment by charles-josiah** [comment]
Hello, the only method I found to accomplish this, albeit not the most one, is:
```
           oci bv volume list --compartment-id "$compartment"  --region $region | grep '"id"' | cut -d '"' -f 4 > all_volumes #get all volumes and place them in a file
            oci compute volume-attachment list --compartment-id "$compartment"  --region $region | grep '"volume-id"' | cut -d'"' -f 4 > attached_volumes #get attached volumes and place them in a file

            for volumes in $(grep -vxFf attached_volumes all_volumes ); do
                       if [[ "$volumes" == ocid1.volume.* ]]; then echo "Not attached" else echo "Attached" fi
            done 
```
