### ISSUE TITLE
how do I assign nsg to existing compute instance using oci-cli?

### ISSUE THREAD

**Issue by wggit** [oracle/oci-cli#238]
oci -version 2.6.7

could not find option to add NSG to existing compute instance using oci-cli.
lbaas has an option  "oci lb nsg update" 

Thank you.

**Comment by vish1** [comment]
As NSG operate on VNICs, please update the VNIC for the compute instance to add the NSG

**Comment by wggit** [comment]
Thank you. I could not find oci-cli command option to assign NSG to vnic. If you can please point me to document link please. Thank you.

**Comment by wggit** [comment]
found
oci network vnic update
