### ISSUE TITLE
platform.linux_distribution() was removed in python3.8 - install breaks

### ISSUE THREAD

**Issue by paralllax** [oracle/oci-cli#241]
`install.py` uses `platform.linux_distribution()`, the installation breaks with the following error:

`AttributeError: module 'platform' has no attribute 'linux_distribution'`

Here is the upstream: https://bugs.python.org/issue28167

It was deprecated in 3.5, then recently removed. If anyone knows of a work around in the meantime, it would be much appreciated. Thanks!

**Comment by vish1** [comment]
Thanks for reporting this @paralllax. We are working on a fix for this and should have an update soon.

**Comment by gareth-j** [comment]
A workaround is to update the version of `virtualenv` that [`install.py`](https://github.com/oracle/oci-cli/blob/master/scripts/install/install.py) tries to download (see line 47). You'll need to either update the checksum or just remove the check, then it install correctly.

**Comment by paralllax** [comment]
Awesome, thank you so much @gareth-j  & @vish1

**Comment by HamadaGabrIbrahim** [comment]
@paralllax Could you please provide more info like
How did you install CLI? What Operation System you were using?
Thanks.

**Comment by paralllax** [comment]
Hi @HamadaGabrIbrahim 

I had followed the instructions from install steps:

```
$ bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
$ source ~/.bashrc
$ oci setup config
```

As for my operating system, I am running Manjaro i3. Let me know if you need more information. Thank you

**Comment by HamadaGabrIbrahim** [comment]
@paralllax Thanks for your reply.
In install.py file, the function platform.linux_distribution() will be called only if you pass the parameter --verify-native-dependencies
I am curious to know if you have passed this parameter to the insaller.

**Comment by paralllax** [comment]
@HamadaGabrIbrahim Happy to help!
As far as I can remember, and reviewing my command history, I didn't pass any additional options, and rather had just run the installer as is. I would like to note that at the time, install.sh pulled down version 2.6.12 of install.py. I tested the current version and it seems to work without issues.

**Comment by HamadaGabrIbrahim** [comment]
@paralllax Thanks for all the info you provided.
I am glad the current version doesn't have this issue.
I am going to close the ticket
