### ISSUE TITLE
Requirement for old arrow 0.10.0

### ISSUE THREAD

**Issue by lucianf** [oracle/oci-cli#248]
Is there any particular reason why we force a dependency on `arrow-0.10.0`, which is a release from almost 4 years ago?

Not asking only from a security/support point of view, but also because of convenience.  While it is a best practice to have `oci-cli` installed in a virtual env (in which case versions of dependencies don't make any difference); but when installing as a global module, the hard requirement on an older package version will always lead to upgrade/downgrade clashes.

To be more specific, when doing a global upgrade, `arrow` will get upgraded to the current version (e.g.` 0.15.5`, January 2020); then `oci-cli` will in turn downgrade it to `0.10.0`, November 2016; and so on.

We should remove this hard dependency on `arrow`'s version.

**Comment by vish1** [comment]
@lucianf Thanks for the suggestion. We will look into upgrading the version for the package.

**Comment by systemcatch** [comment]
There's been many improvements to arrow over the past year so upgrading is definitely worthwhile.

`0.15.0+` have some breaking changes to do with parsing but I don't think it'll effect this repo, `0.14.7` is the last version before that.

**Comment by vish1** [comment]
Thanks for the suggestions @lucianf and @systemcatch. We will be upgrading the version for arrow in the upcoming release.

**Comment by vish1** [comment]
Module arrow has been upgraded to 0.14.7 in release version 2.9.5.

**Comment by lucianf** [comment]
Hi @vish1, could you please review the hardcoded dependency on arrow `0.14.7`, the current version of the library is `0.17.0`.  Perhaps you can upgrade it again in an upcoming release.

**Comment by systemcatch** [comment]
`0.17.0` is definitely worth the upgrading with big improvements to DST transitions.
