### ISSUE TITLE
Specify the --profile value via environment variable

### ISSUE THREAD

**Issue by jamgold** [oracle/oci-cli#25]
It would be nice if the profile (--profile) could be specified via environment variable
```
5a6
> from os import environ as os_environ
26a28,30
> DEFAULT_PROFILE = "DEFAULT"
> if "OCI_PROFILE" in os_environ: DEFAULT_PROFILE = os_environ["OCI_PROFILE"]
> 
44c48
<               default='DEFAULT', show_default=True,
---
>               default=DEFAULT_PROFILE, show_default=True,
```
by making this simple change to oci_cli/cli_root.py simply setting OCI_PROFILE will make that happen

**Comment by therealcmj** [comment]
You should probably submit this as a pull request instead.

**Comment by mross22** [comment]
Thanks for reporting, we just added a fix for this issue which will be part of our next release.  As Chris mentioned we gladly welcome pull requests so if you run into any issues in the future which you have a proposed fix for, feel free to submit one!

**Comment by mross22** [comment]
As of version 2.4.12 we have added the ability to specify this in your ~/.oci/oci_cli_rc file by adding the following section:

```
[OCI_CLI_SETTINGS] 
default_profile=MYPROFILE
```

**Comment by mross22** [comment]
Following up on this, as of release 2.4.13 we have also added the ability to specify --profile through the OCI_CLI_PROFILE environment variable.
