### ISSUE TITLE
Unable to reach Oracle Streaming service through oci cli

### ISSUE THREAD

**Issue by runionow** [oracle/oci-cli#251]
## Unable to reach streaming services through oci cli 

**Command ::**`oci streaming admin stream get --stream-id ocid1.stream.oc1.phx.*********** --profile PERSONAL`

After using the above command i am getting this below error

```HTTPSConnectionPool(host='streaming.us-phoenix-1.oci.oraclecloud.com', port=443): Max retries exceeded with url: /20180418/streams/ocid1.stream.oc1.phx.amaaaaaalhp3ulia45hcaw3n7pqqaiwtvon2hs76uskvsv3wrz4wooll7szq (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x113d7d450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')))```

Verified the policies and groups, I still see the same error.

Unable to reach this host name as well `streaming.us-phoenix-1.oci.oraclecloud.com`

**Comment by vish1** [comment]
@runionow Can you check the proxy setup - the error message indicates that the connection to the proxy could not be established?

**Comment by runionow** [comment]
I don't have any proxy setup on my machine

**Comment by HamadaGabrIbrahim** [comment]
@runionow As @vish1 mentioned it seems to be connection issue.
I wonder if you are able to execute other commands with the same settings.
like for example 'oci iam availability-domain list --profile PERSONAL'

**Comment by kernleee** [comment]
@runionow I'm closing this issue since there hasn't been a response in a while. Feel free to open it back up.
