### ISSUE TITLE
oci compute block-volume-attachment list?

### ISSUE THREAD

**Issue by hiriumi** [oracle/oci-cli#256]
I was looking for a way to list the Block Volume attachment but I was not able to find one. I do see **oci compute boot-volume-attachement list** but not for **Block Volume**. Do we already have one or plan to implement the feature in the future?

**Comment by vish1** [comment]
Hi @hiriumi  This command should allow you to list volume attachments **oci compute volume-attachment list**

**Comment by vish1** [comment]
@hiriumi Were you able to use the command mentioned above?

**Comment by hiriumi** [comment]
@vish1 Yes! I was able to list the attachments using the command. Thank you very much for your help! :)
