### ISSUE TITLE
oci cli command to set DNS record

### ISSUE THREAD

**Issue by psaini2018** [oracle/oci-cli#259]
Please provide the command example to set the DNS record in OCI. I tried following and it keeps on failing:

oci dns record rrset update --domain "rcidemo.com" --zone-name-or-id "ocid1.dns-zone.oc1..0d05bc1787b544d39eb143930ab4b95f" --rtype 'A' --items "[{\"domain\":\"rocidemo.com\", \"rdata\":\"cnode1\", \"rtype\":\"A\",\"ttl\":24000}]"

WARNING: Updates to items will replace any existing values. Are you sure you want to continue? [y/N]: y
ServiceError:
{
    "code": "CannotParseRequest",
    "message": "Invalid value for items[0].rdata: bad A A: \"cnode1\" at line: 1:35",
    "opc-request-id": "5F660ECB927E4094A164D1D195EE86D4/7D12D983655D493D8B004AFA9F1E0A1C/F1D5DA49787241A59EEA4B2F8656EE9A",
    "status": 400
}

Also, how this warning can be ignored supressed?

**Comment by vish1** [comment]
@psaini2018 The warning can be suppressed by using the `--force` flag for the command.

**Comment by vish1** [comment]
@psaini2018 Looks like the json object for `--items` is not correctly formed. As shown in the example input [here](https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliusing.htm#ManagingCLIInputandOutput)

`'{"key1":"value1","key2":"value2"}'`

Please use single quotes to surround the json input.

**Comment by vish1** [comment]
@psaini2018 Please let us know if you were able to proceed using the above comments.

**Comment by vish1** [comment]
@psaini2018 Closing this issue due to lack of response. Please re-open if needed.

**Comment by tfountain** [comment]
A records are for IP addresses (IPv4 addresses to be specific), but the rdata you are providing is `cnode1`, so that's why you're getting the "Invalid value" error. You'll need to provide an IP address instead, or use a different record type.
