### ISSUE TITLE
OCI OD Error: no such option: -f

### ISSUE THREAD

**Issue by arunmc05** [oracle/oci-cli#262]
Hi,

I have installed the OCI to my local windows PC and running the following command in command prompt to FTP the pdf file and I am getting the following error.

------------------------------------------------------------------------------
```
Microsoft Windows [Version 10.0.16299.1686]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\mca>oci os object put -ns bmhe7fzgl3tr -bn INVOICES -file C:\Users\mca\Desktop\Holidays.pdf
Error: no such option: -f

C:\Users\mca>
can you please what is the issue.

```
bmhe7fzgl3tr is the Namespace in the Bucket details
INVOICES is the Bucket name

is this correct.

Thank You,
Arun

**Comment by vish1** [comment]
thanks @arunmc05 for opening the issue. I think the problem is that you need to use double dashes for the `file` parameter. (as in `--file`)

**Comment by arunmc05** [comment]
Thank you it worked @vish1  but I got  

```
   "code": "BucketNotFound",
    "message": "Either the bucket named 'INVOICES' does not exist in the namespace 'bmhe7fzgl3tr' or you are not authorized to access it",
    "opc-request-id": "bom-1:h88PGO-go9CCkA72LqQrDeY2IZlIxkoeH5Vm0luUr-fYoDtEaCxpSZiw_3duCX4X",
    "status": 404
```

I have kept Bucket Visibility has Public anything work

**Comment by arunmc05** [comment]
Hi,

I am able transfer the file. issue was I missed to add the User to the Group.
