### ISSUE TITLE
need upload all the file which is in the folder to Bucket

### ISSUE THREAD

**Issue by arunmc05** [oracle/oci-cli#263]
Hi,

I need to upload the all file exists in the folder . what is the command for this and if any same file name exists in the bucket  then it should over write it. 
is it possible.

I am able to upload a single file to Bucket with following command in command prompt.
`oci os object put -ns <object_storage_namespace> -bn <bucket_name> –file <file_location>`

Please help.

Thank You,
Arun

**Comment by vish1** [comment]
@arunmc05 You can use the bulk upload feature
`NAME
       os_object_bulk-upload -

DESCRIPTION
       Uploads all files in a given directory and all subdirectories.

USAGE
          oci os object bulk-upload [OPTIONS]`

You can use this flag on the command to overwrite existing files
`       --overwrite

       If a file being uploaded already exists in Object Storage with the same
       name, overwrite the existing object in Object Storage without a confir-
       mation  prompt. If neither this flag nor no-overwrite is specified, you
       will be prompted each time an object with the same name would be  over-
       written.

       Specifying this flag will also allow for faster uploads as the CLI will
       not initially check whether or not the files with the same name already
       exist in Object Storage.`

**Comment by arunmc05** [comment]
@vish1 Thank You!
