### ISSUE TITLE
How to filter JSON data with dashed name

### ISSUE THREAD

**Issue by hiriumi** [oracle/oci-cli#264]
Hello,

I'm trying to filter image data by using --query but I haven't been able to.

`oci compute image list --compartment-id $T --query 'data[?"operating-system"==CentOS]'`

I get the following message.

> Query returned empty result, no output to show.

I think dashed data name is the issue here. Can someone help me with this issue please?

**Comment by hiriumi** [comment]
I finally figured it out. Here is what I wanted to accomplish.

`oci compute image list --compartment-id $T --query "data[?\"operating-system\"=='CentOS']"`

I will close this ticket.

**Comment by zelrew** [comment]
@hiriumi Thank you for this! Four years later, I was scratching my head trying to figure out why my query was returning nothing.
