### ISSUE TITLE
Need support for container registry through oci cli

### ISSUE THREAD

**Issue by sauraahu** [oracle/oci-cli#265]
Couldn't find support for container registry  to create repos , delete repo, delete containers etc. on https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.9.6/oci_cli_docs/

Similar option are available in AWS and Azure called ECR https://docs.aws.amazon.com/cli/latest/reference/ecr/index.html and ACR resp. https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-azure-cli for reference.

**Comment by vish1** [comment]
@sauraahu Thanks for the ask. Support for container registry is coming soon.
