### ISSUE TITLE
File transfer from Oracle cloud to on premises EBS application (Linux server)

### ISSUE THREAD

**Issue by arunmc05** [oracle/oci-cli#266]
Hi,

what is the command to SFTP the csv file from object Storage to Linux server. 

Can you please help. 

Thank you, 
Arun

**Comment by vish1** [comment]
@arunmc05 Can you provide more specific details? The subject mentions database, but the question talks about SFTP from object storage to linux server.

**Comment by arunmc05** [comment]
@vish1  I have modified the subject. is there way to push file from Cloud storage to on premises appliaction.
I Tried pushing from files  on premises to  cloud. using  
` oci os object put -ns <object_storage_namespace> -bn <bucket_name> --file <file_location>`

**Comment by vish1** [comment]
@arunmc05 You can use `oci os object get`

**Comment by vish1** [comment]
@arunmc05 Were you able to use the command mentioned in the previous comment?

**Comment by vish1** [comment]
@arunmc05 Closing this ticket due to no response.
