### ISSUE TITLE
configparser error when installing on macOS

### ISSUE THREAD

**Issue by ctripod** [oracle/oci-cli#271]
I was trying to install Oracle OCI CLI and I'm getting the following error.  It appears that configparser has been upgraded to 5.0.0 which does not match the required 4.0.2 for the installer.

ERROR: oci 2.12.2 has requirement configparser==4.0.2, but you'll have configparser 5.0.0 which is incompatible

Any flag I can pass or solution?

**Comment by vish1** [comment]
@ctripod The issue has been fixed in the latest release. Please upgrade.
