### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the specified path: 'services'

### ISSUE THREAD

**Issue by danielfclp** [oracle/oci-cli#278]
Hello,

I'm getting this error when trying to create the kubeconfig file using OCI CLI:
FileNotFoundError: [WinError 3] O sistema não pode encontrar o caminho especificado: 'services'
**FileNotFoundError: [WinError 3] The system cannot find the specified path: 'services'**

I'm using this command:
oci ce cluster create-kubeconfig --cluster-id *myclusterid* --file $HOME/.kube/config --region us-ashburn-1 --token-version 2.0.0 --profile *myprofilename*

**Comment by himanshu1591** [comment]
Hi Daniel,

I faced the similar error during my kubeconfig setup. I hope you have resolved it by now but if not, try below method.

The error indicates that OCI is trying to give you a ServiceError and it fails to find the location 'services' where it's error code resides. Hence you are getting that vague line not the exact error.

In my case , my user account in the respective tenancy was missing the public key , hence I was getting this error for "ServiceError: NotAauthorised".

Try checking that.

**Comment by roberthuie** [comment]
Double check your CLI config file.  I had my tenancy ID wrong. After I corrected that, the error went away for me.

**Comment by danielfclp** [comment]
Hello guys, tks for all the help.

I've finally understood the CLI config file.

I was trying to use a different profile every time and the api key pairs were all wrong.

I now use only 1 profile, and got that profile to use the api keys I've uploaded to OCI dashboard and created the kubeconfig file alright.
