### ISSUE TITLE
scripts directory not taking defaults when using the --install-dir flags

### ISSUE THREAD

**Issue by binbashroot** [oracle/oci-cli#282]
It appears the install.py script is setting the script_dir as "None" and not passing the --install-dir configurations as the base dir to install the scripts to defined bin directory in the install.sh script.

[root@myhost~]# sh install.sh --install-dir /opt/foo/oracle-cli --exec-dir /opt/foo/oracle-cli/bin

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.9.3/scripts/install/install.py to /tmp/oci_cli_install_tmp_MXFI.
######################################################################## 100.0%
Running install script.
python3 /tmp/oci_cli_install_tmp_MXFI  --install-dir /opt/foo/oracle-cli --exec-dir /opt/foo/oracle-cli/bin
-- Verifying Python version.
-- Python version 3.6.8 okay.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/root/bin/oci-cli-scripts'):

**Comment by HamadaGabrIbrahim** [comment]
@binbashroot Thanks for reporting this issue. we are looking into it

**Comment by kernleee** [comment]
@binbashroot We've added a new parameter to specify the install script directory, --script-dir.
Thank you for bringing this to our attention, closing this issue.
