### ISSUE TITLE
oci last_patch_history details

### ISSUE THREAD

**Issue by Shashank-Barki** [oracle/oci-cli#285]
Is there a way to list all the patches installed in a database system and db instances using any python or cli commands. Don't want to trigger dbcli commands in each db system. I want to get patch information across tenancy.

**Comment by adizohar** [comment]
you can run showoci script I wrote to extract all database ++ information, it will show you the current patch and what available to deploy
https://github.com/oracle/oci-python-sdk/tree/master/examples/showoci

**Comment by Shashank-Barki** [comment]
Thanks Adi for your reply and showoci utility. I have tried showoci and it returns available patches and not the history of patches. I have tried with python function with patch history id and also with oci db command but with no success. 

Is there anything I am missing as only way seems to use dbcli describe-component at this stage.

Also I see a comment that     # class oci.database.DatabaseClient(config, **kwargs)
 # Below APIs not yet done (TBD):
    # list_db_home_patch_history_entries
    # list_db_system_patch_history_entries

**Comment by adizohar** [comment]
Hi Shashank, For OCI CLI, you can use - 
oci db patch-history list by-database --database-id
or
oci db patch-history list by-db-system

I may add the patch history to showoci in next releases

**Comment by Shashank-Barki** [comment]
Hi Adi, Thanks for your reply again. 
I see that oci db patch-history list by-database will not return any records if patches are applied from databases directly (not using cloud console or OCI update commands).

Output of oci db patch-history and dbcli describe-component are not in sync at all.

Please let know your opinion on how to show patch history details.

[root@prod-server~]# dbcli describe-component
System Version
---------------
20.1.2.0.0

Component                                Installed Version    Available Version
---------------------------------------- -------------------- --------------------
OAK                                       18.6.0.0.0            up-to-date
GI                                        18.6.0.0.190416       18.10.0.0
DB                                        18.6.0.0.190416       18.10.0.0

oci db patch-history list by-database --database-id ocid1.database.oc1.iad.xyzzzzzz
>>> no output

**Comment by adizohar** [comment]
Shashank, there is no shortcut, if you apply database patches using opatch, or patches that already applied to the image, you won't be able to see from console
only patches that applied from the console or dbcli will appear

For all patches, either run opatch or select from the DBA_REGISTRY_HISTORY

This is not OCI CLI issue

**Comment by kernleee** [comment]
Closing this since this isn't a CLI issue.
