### ISSUE TITLE
ImportError: No module named operator

### ISSUE THREAD

**Issue by andrefecto** [oracle/oci-cli#286]
When running any commands after installing oci I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 5, in <module>
    from oci_cli.cli import cli
  File "/opt/oci/lib/python2.7/site-packages/oci_cli/__init__.py", line 8, in <module>
    from inspect import getsourcefile
  File "/usr/lib64/python2.7/inspect.py", line 41, in <module>
    from operator import attrgetter
ImportError: No module named operator
```
My installation parameters were:
```
Install Dir: /opt/oci
Executable location: /usr/local/bin
Place scripts in: /opt/oci/scripts
```
 
Running oci as root is fine, no errors. But if you're not root, you get that no module named operator error. However, I have given all users access to everything in the /opt/oci directory (R-X)

This installation worked a few weeks ago on other systems I have, but not anymore. 
Version of OCI that doesn't have any problems: ``` 2.10.0```
Version of OCI that has this issue: ``` 2.10.4 ```
Operating system on both systems:
```
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.8:GA:server
Kernel: Linux 3.10.0-1127.8.2.el7.x86_64
```
Python version on both systems: ``` 2.7.5 ```
Python path on both systems (which python): ``` /usr/bin/python ```
OCI path on both systems (which python) ``` /usr/local/bin/oci ```

Please let me know if I can provide any other debugging information.

EDIT:
I have tried completely removing /opt/oci and then reinstalling it with the --oci-cli-version 2.10.0  flag and still get this issue. Maybe this is an issue with an oci-cli dependency?
EDIT 2:
I updated the system to python3 via the directions here:
https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/
Ran ``` scl enable rh-python36 bash ``` then re-ran the oci install via: ``` ./install.sh --install-dir /opt/oci --exec-dir /usr/local/bin --oci-cli-version 2.10.0 --accept-all-defaults ``` and now any user can actually run ``` oci setup config ``` or any other oci command. So seems like a dependency updated behind the scenes and broke RHEL7 python 2.7.X support.

**Comment by kernleee** [comment]
Closing this as it looks like the issue was solved.
