### ISSUE TITLE
AttributeError when trying to retrieve WaaS log list

### ISSUE THREAD

**Issue by rramge** [oracle/oci-cli#287]
Hello,

I run into the following error when I try to access the WAF logs:

[rramge@ol7 ~]$ oci --profile SES waas waf-log list --waas-policy-id < ocid_inserted-here > --all
AttributeError: 'dict' object has no attribute 'replace'
[rramge@ol7 ~]$ 

Other commands like 'waf-config get' work fine, so I assume there'ws either a bug hidden somewhere or, which is maybe more likely, I do something wrong here.

Any advice will be highly appreciated.

Cheers,

Ralf

**Comment by vish1** [comment]
@rramge Thanks for pointing this issue out. Can you please provide the following details:

1. Which version of the CLI is being used?
2. Did the same code work in the past for you? Or did the code never work in the first place?
3. What operating system and version is the CLI being used on?
4. Debug log output (run the same command with `-d` flag)

**Comment by rramge** [comment]
Hi,

thanks for your quick reaction. Let me provide the answers for you:

> Which version of the CLI is being used?

[rramge@ol7 ~]$ oci -version
2.10.4
[rramge@ol7 ~]$ 

> Did the same code work in the past for you? Or did the code never work in the first place?

This is for a new OCI customer and the feature was never requested before, so it is my first time I try this.

> What operating system and version is the CLI being used on?

[rramge@ol7 ~]$ uname -a
Linux ol7 4.14.35-1902.302.2.el7uek.x86_64 #2 SMP Fri Apr 24 14:24:11 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux
[rramge@ol7 ~]$ 

> Debug log output (run the same command with -d flag)

I attach it here with OCIDs made unusable. I hope this is okay for you.

[debug.txt](https://github.com/oracle/oci-cli/files/4722706/debug.txt)

Thanks,

Ralf

**Comment by adizohar** [comment]
Hi Ralf
You are running OCI CLI on top of Python2 which not supported any more
I am running on Python3 and it works well
I would suggest to install Python3 + OCI CLI and try again.
Adi.

**Comment by rramge** [comment]
Adi, you are correct. When looking into the reason WHY oci-cli used python 2.7, things are getting interesting, because oracle-cli's install.sh created the python 2.7 directories in its installation path. 

A quick look showed me that, when using Oracle Linux or another  distro which uses 'yum', the install script tries to download the python 3.6 package and compile it. This never happened on my Oracle Linux 7.8 (vanilla install with updated ULN packages). I didn't look into it further, because a after a manual install of python3 a new installation of oci-cli via install.sh worked fine, but my guts tell me that the install script is not perfect here.

Thanks, I got my logfiles :-)

Ralf

**Comment by rramge** [comment]
I close the issue. Thanks for the help.
