### ISSUE TITLE
oci bv boot-volume list, should support lifecycle-state filtering

### ISSUE THREAD

**Issue by hatvik** [oracle/oci-cli#289]
>  },
>   "display-name": "REDACTED (Boot Volume)",
>   "freeform-tags": {},
>   "id": "ocid1.bootvolume.oc1.iad.REDACTED",
>   "image-id": "ocid1.image.oc1.iad.REDACTED",
>   "is-hydrated": true,
>   "kms-key-id": null,
>   "lifecycle-state": "AVAILABLE", <----------------
>   "size-in-gbs": 47,
>   "size-in-mbs": 47694,
>   "source-details": null,
>   "system-tags": {},
>   "time-created": "2020-05-25T10:05:51.058000+00:00",
>   "volume-group-id": null,
>   "vpus-per-gb": 10
> }
> 

https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.10.4/oci_cli_docs/cmdref/bv/boot-volume/list.html

This should work similar to eg oci bv volume list

**Comment by adizohar** [comment]
HI Hatvik

I don't understand what is the issue, running oci bv boot-volume list does show the lifecycle-state

Please advise
Thank you

**Comment by hatvik** [comment]
Sorry, an important word was missing in the title, filter.
This works:
> oci bv volume list --availability-domain ${ad} --compartment-id ${c} --lifecycle-state AVAILABLE --all

This doesnt work:
> oci bv boot-volume list --availability-domain ${ad} --compartment-id ${c} --lifecycle-state AVAILABLE --all

**Comment by adizohar** [comment]
Hi Hatvik
Not all API has the lifecycle-state as filter , list of boot volumes doesnot
This is why OCI CLI established Query option
You can run the below to filter:

oci bv boot-volume list --availability-domain $AD --compartment-id $COMP --query "data [?\"lifecycle-state\" == 'AVAILABLE']"

**Comment by hatvik** [comment]
Yes, thats one possible workaround. 
But are saying that will not be fixed?

**Comment by kernleee** [comment]
This will not be fixed as stated above, not all commands have the option for filtering which is why we offer the --query parameter as a global parameter. I'll be closing this ticket, feel free to reopen it if you have more concerns.
