### ISSUE TITLE
Issue while accessing Cost and Usage reports

### ISSUE THREAD

**Issue by Vivek-ghub** [oracle/oci-cli#294]
We are trying to get "Cost and Usage reports" data from different tenancies using federated user and getting following error message. We have defined tenancy usage-report and got access to that group.

Error Download Usage and insert to database - {'opc-request-id': 'xxxxxxxxxxx', 'code': 'BucketNotFound', 'message': "Either the bucket named 'ocid1.tenancy.oc1..xxxxxxxxxxxx' does not exist in the namespace 'bling' or you are not authorized to access it", 'status': 404}

Following is the reference using to access cost & usage reports
https://docs.cloud.oracle.com/en-us/iaas/Content/Billing/Tasks/accessingusagereports.htm

Following installation steps to create Cost and Usage reporting using APEX Reporting with in the tenancy. But we need to collect different tenancies data and create APEX reporting.
https://github.com/oracle/oci-python-sdk/blob/master/examples/usage_reports_to_adw/step_by_step_installation.md

**Comment by adizohar** [comment]
Please share the policy you created

**Comment by Vivek-ghub** [comment]
Thank you for the update Adi!! I really appreciate your help!
The Cost & Reports are no longer being generated in internal tenancies.
