### ISSUE TITLE
unable to install cli to RHEL instance

### ISSUE THREAD

**Issue by terter** [oracle/oci-cli#296]
I launched RHEL 8.1 instance from custom image and tried to install CLI using command below, but SSL error has occurred. 

1. executed command
export https_proxy = "https://user:password#@localhost:8080"
export http_proxy = "http://user:password#@localhost:8080"
bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -U ${user}:${pass} -x http://localhost:8080)"

2. error
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8080

3. information
OS version RHEL 8.1
curl version curl 7.61.0

**Comment by adizohar** [comment]
Please try to install OCI-CLI using pip
pip install oci-cli

**Comment by kernleee** [comment]
@terter Are you still facing this issue? It could also be caused by the proxies.

**Comment by vish1** [comment]
@terter Please let us know if you are still facing this issue?

**Comment by kernleee** [comment]
I'll be closing this from no response, feel free to reopen this issue. Thanks.
