### ISSUE TITLE
Unable to assign public ip to private IP via CLI @Oracle Linux 7

### ISSUE THREAD

**Issue by raylaw-hk** [oracle/oci-cli#299]
A auto refresh public ip script can be run in oracle cloud shell without any error but error returned in OCI CLI

Environment:  Oracle Linux Storage Appliance 1.8.1 instance on OCI
OCI CLI version: 2.12.0

Behavior: 
Able to delete public ip but cannot create, command will stuck until a public IP assigned via Cloud Shell (by running: oci network public-ip create --compartment-id $compartmentID --lifetime RESERVED --private-ip-id $privateIPID) or manually assigned via portal.
Error will returned once a public ip assigned (private ip already has public ip)

Code Sample:

export LC_ALL=en_NZ.utf8
compartmentID={my compartment}
privateIPID={my private IP}
publicIPID=$(oci network public-ip get --private-ip-id $privateIPID | grep -o '"id": "[^"]*' | grep -o '[^"]*$')
oci network public-ip delete --public-ip-id $publicIPID --force  --wait-for-state UNASSIGNED
oci network public-ip create --compartment-id $compartmentID --lifetime RESERVED --private-ip-id $privateIPID

**Comment by vish1** [comment]
@raylaw-hk Was this working with an earlier version of the CLI? Also, can you provide the output with debug enabled`-d` ?

**Comment by raylaw-hk** [comment]
Hi @vish1 ,
Sorry that I am new to oracle cloud so I cannot confirm if it was working before.

I also cannot do debug enable since my ssh session would end once reached the drop ip commend:
oci network public-ip delete --public-ip-id $publicIPID --force --wait-for-state UNASSIGNED

The create ip is the one that not able to proceed via ssh:
oci network public-ip create --compartment-id $compartmentID --lifetime RESERVED --private-ip-id $privateIPID

Full set of commends can be put in a .sh and run without error via cloud shell .

Thanks for your help.

**Comment by kernleee** [comment]
This may be because your instance does not have full permissions for this operation. Cloudshell's authentication is different from compute instance authentication. Can you check whether your instance has full permissions for this operation? Could you also return the error code?

**Comment by kernleee** [comment]
Will be closing this as it hasn't had a response in a long time. Feel free to open it back up.
