### ISSUE TITLE
Rename-Item appears every time powershell is opened

### ISSUE THREAD

**Issue by twmcelroy** [oracle/oci-cli#301]
I've had this issue every time I open my powershell. 

Rename-Item : The item at path 'TabExpansionBackupFromOciAutocomplete' already exists.
At C:\Users\travis.mcelroy\lib\oracle-cli\Lib\site-packages\oci_cli\bin\OciTabExpansion.ps1:120 char:5
    Rename-Item Function:\TabExpansion TabExpansionBackupFromOciAutoc ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidArgument: (:) [Rename-Item], PSArgumentException
     FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand

I don't understand Powershell scripting. Can anyone help me eliminate this error. It's quite annoying to appear with every command I run as well.

**Comment by kernleee** [comment]
@twmcelroy Have you tried deleting the file from the location? That should solve it.

**Comment by twmcelroy** [comment]
No that throws even more errors. 
![image](https://user-images.githubusercontent.com/20779080/89459736-be560f80-d72e-11ea-9b48-156b44bb229c.png)

**Comment by kernleee** [comment]
When is that error thrown? Have you tried uninstalling and installing? https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliuninstall.htm

**Comment by twmcelroy** [comment]
That didn't work but then it gave more errors. But I found it. My initial profile had duplicates
![image](https://user-images.githubusercontent.com/20779080/89747225-592e5100-da83-11ea-98d1-3daaa3e4352a.png)
I've commented them out and now on a load it doesn't send the error. Now i've learned about PowerShell profiles. No clue how those duplicates got in there. Maybe with how it was installed and with upgrades? I'm not sure.

But that seemed to have fixed it!

**Comment by albertyckwok** [comment]
@twmcelroy, could you tell me where is the initial profile or which file I need to look? I am having similar problem. The following is what I see when I start PowerShell:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Rename-Item : The item at path 'TabExpansionBackupFromOciAutocomplete' already exists.
At C:\Users\akwok\lib\oracle-cli\Lib\site-packages\oci_cli\bin\OciTabExpansion.ps1:120 char:5
+     Rename-Item Function:\TabExpansion TabExpansionBackupFromOciAutoc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand

Rename-Item : The item at path 'TabExpansionBackupFromOciAutocomplete' already exists.
At C:\Users\akwok\lib\oracle-cli\Lib\site-packages\oci_cli\bin\OciTabExpansion.ps1:120 char:5
+     Rename-Item Function:\TabExpansion TabExpansionBackupFromOciAutoc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Rename-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RenameItemCommand

Loading personal and system profiles took 3123ms.
```
Thanks very much in advance
Albert

**Comment by twmcelroy** [comment]
Wow this is bringing me back. I believe it is that file that is listed. 
C:\Users\akwok\lib\oracle-cli\Lib\site-packages\oci_cli\bin\OciTabExpansion.ps1. 
That is where I'd look first.

**Comment by twmcelroy** [comment]
I am not sure. I don't know powershell well and I had two sections right next to each other that were the same.

**Comment by dylan-leggatt** [comment]
I had the same issue, it was present 4 times in my inital profile that loaded when powershell opened. To fix it from powershell I did notepad $PROFILE and then deleted all the duplicates

**Comment by albertyckwok** [comment]
This works, thanks very much @dylan-leggatt, we probably need to update the doc.
