### ISSUE TITLE
os object bulk-upload timeout feature

### ISSUE THREAD

**Issue by aaronkvanmeerten** [oracle/oci-cli#309]
When uploading files via oci os object bulk-upload we are regularly experiencing failures which cause the oci tool to block and not return, sometimes for days or weeks if left alone.  

It would nice to have a timeout parameter which could cause the oci tool to exit non-zero if the upload processing takes longer than a specified amount of time.

It would also be nice to understand why this happens.  An strace of the process shows it's stuck on a read(0) system call.  lsof shows several open connections stuck in CLOSE_WAIT:

169.254.169.254:http (CLOSE_WAIT)
169.254.169.254:http (CLOSE_WAIT)
129.213.2.151:https (CLOSE_WAIT)
134.70.27.247:https (CLOSE_WAIT)
134.70.27.247:https (CLOSE_WAIT)

This is running on an instance in a VCN within oracle cloud itself, in case that helps

**Comment by aaronkvanmeerten** [comment]
I've seen no response here, so we'll be raising an internal oracle cloud ticket to escalate with our customer representative, as this continues to happen on a regular basis.

**Comment by kernleee** [comment]
Is this resolved? I don't think I saw an internal ticket for this.

**Comment by aaronkvanmeerten** [comment]
It appears to have been user error, the lack of --no overwrite or --overwrite combined with a retry of an existing path meant the application was blocking waiting for user input.  I am closing this now.
