### ISSUE TITLE
oci announce announcements list doesn't have an '--all' and return misleading warning

### ISSUE THREAD

**Issue by VAdamec** [oracle/oci-cli#311]
Hi,
 oci announce announcements list command returns paged data and _WARNING: This operation supports pagination and not all resources were returned.  Re-run using the --all option to auto paginate and list all resources._ But there is no such option, it is possible to add --all option or at least tweak returned warning as it's misleading.

Thanks

**Comment by kernleee** [comment]
Hi, this request was added in the last 2.12.12 release.
Thanks for your suggestion @VAdamec, closing this ticket

**Comment by kk-hiraskar** [comment]
Hi any suggestion to disable this warning message ?

**Comment by adizohar** [comment]
I don't see any warning message running the command
