### ISSUE TITLE
CLI installation script fails 

### ISSUE THREAD

**Issue by pikopiri127** [oracle/oci-cli#317]
Im following https://docs.cloud.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm to install CLI for Windows. 
When I run the installer script as Administrator I got the following error.
I'm very beginner in CLI and I'd appreciate it if I could get any help so that I can move forward and complete this installation.

PS C:\WINDOWS\system32> powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1'))"

/ Program 'powershell.exe' failed to run: Access is deniedAt line:1 char:1
/ + powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Obj ...
/ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
/ At line:1 char:1
/ + powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Obj ...
/ + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
/     + FullyQualifiedErrorId : NativeCommandFailed

**Comment by vish1** [comment]
@pikopiri127 The line provided on the page for Windows install assume you are running in the Windows Shell. The first line of the command is actually to start `powershell`. In your case, you are running the line within Powershell and hence should only run the actual command - `iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1'))`

**Comment by pikopiri127** [comment]
@vish1 Yes it works!! Thank you so much for your prompt response, I really appreciate it!!
