### ISSUE TITLE
--scripts-dir option causes installation failure

### ISSUE THREAD

**Issue by binbashroot** [oracle/oci-cli#319]
Running following installation with options fails:
OS:  OEL 7.8
Python: 3.6.8

Steps
```
# wget https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
# sh install.sh --install-dir /opt/oracle-cli --exec-dir /opt/oracle-cli/bin --script-dir=/opt/oracle-cli/bin/oci-cli-scripts  --update-path-and-enable-tab-completion --rc-file-path ~/.bashrc
```
Failed to run install script. Unrecognized argument: --script-dir=/opt/oracle-cli/bin/oci-cli-scripts

**Comment by kernleee** [comment]
There's an equal sign in --script-dir=/opt/oracle-cli/bin/oci-cli-scripts. Can you try spacing out the parameter and argument? 
--script-dir /opt/oracle-cli/bin/oci-cli-scripts

**Comment by binbashroot** [comment]
Sorry for wasting your time.  Didn't even catch that.  It works.  Sincerest apologies!!
