### ISSUE TITLE
Feature request - Add a --no-tty option for hands off installations that do not use defaults.

### ISSUE THREAD

**Issue by binbashroot** [oracle/oci-cli#321]
install.sh script requires a tty to perform an installation that does not take the defaults.   This makes it difficult to use tools like Ansible without having to use expect or some other methodology to work around a hands off installation when passing options for a non default installation.

Feature request:
add a --no-tty option to install.sh 

Example: 
case $key in
    --no-tty)
    NO_TTY_REQUIRED="true"
    shift # past argument
    shift # past value
    ;;

......SHORTENED FOR BREVITY.....

if [ "${ACCEPT_ALL_DEFAULTS}" == "true" ] || [ [ "${NO_TTY_REQUIRED}" == "true" ];then
    # By removing the tty requirement, users will be able to install non-interactively over ssh
    # and in docker containers more easily.
    $python_exe $install_script $install_args
else
    $python_exe $install_script $install_args < $_TTY
fi

**Comment by kernleee** [comment]
This feature was released in our latest release 2.12.11.
Thank you @binbashroot for your suggestion. Closing the ticket
