### ISSUE TITLE
oci cli os object list limitations

### ISSUE THREAD

**Issue by jspring11** [oracle/oci-cli#323]
When doing oci os object list --limit > than 3,000,000 objects, oci cli hangs.  --all just hangs.  Please add error condition based on timeout limit (or whatever).  Also, would be good if we could list by pages.

**Comment by kernleee** [comment]
Hi @jspring11, we've added a new parameter for `oci os object list --stream-output` that works in conjunction with `--all`. It will stream the responses from the service, so it should not hang. This is available with CLI version 2.13.0.
Thank you for your suggestion. Closing this ticket.
