### ISSUE TITLE
cannot ping hosts

### ISSUE THREAD

**Issue by akojima** [oracle/oci-cli#325]
One arguably obvious use case in the Cloud Shell is pinging specific instances to check connectivity and availability, as a first step when troubleshooting something. However, it's not possible to use ping in the cloud shell:

alfredo@cloudshell:~ (us-ashburn-1)$ ping 127.0.0.1
ping: socket: Operation not permitted
alfredo@cloudshell:~ (us-ashburn-1)$

**Comment by kernleee** [comment]
Hi @akojima, Cloud Shell has opened an internal ticket for this request and are working on it. Since this issue isn't CLI related and we can't do anything on our side, I'll be closing this ticket. Thanks
