### ISSUE TITLE
list compartments?

### ISSUE THREAD

**Issue by gliptak** [oracle/oci-cli#33]
When trying to list compartments, I get an error that compartment needs to be specified. Am I using this incorrectly? Thanks

```
λ oci --version
2.4.13
λ oci iam compartment list
Usage: oci iam compartment list [OPTIONS]

Error: Missing option(s) --compartment-id.
```

**Comment by nathan-vu** [comment]
Sorry, it's a little obtuse but if you provide your tenancy's OCID as the compartment ID  does that work?

```
Usage: oci iam compartment list [OPTIONS]

  Lists the compartments in your tenancy. You must specify your tenancy's
  OCID as the value for the compartment ID (remember that the tenancy is
  simply the root compartment). See [Where to Get the Tenancy's OCID and
  User's OCID].
```

**Comment by gliptak** [comment]
@nathan-vu Thank you for the pointer. Using the tenancy ID as compartment ID worked. (Now I'm recalling running into this in the past) Should the option be renamed to ```--tenancy-id``` (or is this a hierarchical lookup (compartments in compartments)?

**Comment by nathan-vu** [comment]
My (somewhat vague) understanding is that it's named `--compartment-id`/`compartmentId` (depending on whether you look at the CLI or the SDK or API) so as not to preclude hierarchical lookups in the future (though I think today there aren't really compartments inside compartments, apart from at the tenancy level)
