### ISSUE TITLE
free-text-search returns spurious results and does not agree with console

### ISSUE THREAD

**Issue by bridgem** [oracle/oci-cli#330]
oci search resource free-text-search --text 'query image resources where lifecycleState != "Deleted"'
Returns resources that it should not:
1. It returns images that *are* Deletes
2. It also returns policy objects

When running the same query in the console, the correct results are returned.

**Comment by kernleee** [comment]
@bridgem Have you tried structured-search command? https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.13.0/oci_cli_docs/cmdref/search/resource/structured-search.html

**Comment by kernleee** [comment]
I'll be closing this since `oci search resource structured-search --query-text 'query image resources where lifecycleState != "Deleted"'` returns the correct results. 
Feel free to reopen this if you have more questions.
