### ISSUE TITLE
os-management software-source search

### ISSUE THREAD

**Issue by slevey** [oracle/oci-cli#332]
oci-cli version: 2.12.13
Command:  oci os-management software-source search-packages

The utility specifies a mandatory parameter:  --package-name

This is contradictory to the underlying API and prevents searching via alternate approached including:  --cve-name

**Comment by HamadaGabrIbrahim** [comment]
@slevey Thanks for bringing this to us.
I am looking into it
Thanks

**Comment by HamadaGabrIbrahim** [comment]
@slevey This issue has been fixed in the CLI version 2.14.1 and the field --package-name is optional now
I am going to close the issue
