### ISSUE TITLE
install.sh just  started failing with "install.sh: line 361: /dev/tty: No such device or address"

### ISSUE THREAD

**Issue by wajiii** [oracle/oci-cli#343]
We use tty-less installation in an automated Docker container build, and it has been working flawlessly for a long time, but just started failing sometime between X and Y today  with this error; looks like a mistake or oversight in the install script.

`#7 [4/10] RUN export http_proxy=http://www-proxy-hqdc.us.oracle.com:80     ...
#7 1.601   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#7 1.601                                  Dload  Upload   Total   Spent    Left  Speed
100 16012  100 16012    0     0  42026      0 --:--:-- --:--:-- --:--:-- 41916
#7 2.005 bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf-8)
#7 2.023 WARNING: Some interactive prompts may not function correctly if this script is piped into bash (e.g. 'curl "https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh" | bash)'
#7 2.023 WARNING: Script should either be downloaded and invoked directly, or be run with the following command: bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
#7 2.043 Running with --accept-all-defaults
#7 2.048 Downloading Oracle Cloud Infrastructure CLI install script from https://raw.githubusercontent.com/oracle/oci-cli/v2.12.7/scripts/install/install.py to /tmp/oci_cli_install_tmp_uLtz.
######################################################################## 100.0%
#7 3.145 /tmp/install.sh: line 361: /dev/tty: No such device or address
#7 3.145 Running install script.
#7 3.145 python3 /tmp/oci_cli_install_tmp_uLtz  --accept-all-defaults --install-dir /u01/oracle/lib --exec-dir /usr/bin
#7 ERROR: executor failed running [/bin/sh -c export http_proxy=http://www-proxy-hqdc.us.oracle.com:80     https_proxy=http://www-proxy-hqdc.us.oracle.com:80     HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80     HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80     LC_ALL=en_US.utf-8 LANG=en_US.utf-8 PYTHONIOENCODING=utf-8     && curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > /tmp/install.sh     && chmod +x /tmp/install.sh     && /tmp/install.sh --accept-all-defaults --install-dir ${ORACLE_HOME}/lib --exec-dir /usr/bin </dev/null     && rm -f /tmp/install.sh     && yes | oci setup autocomplete]: runc did not terminate sucessfully

#8 [internal] load build context
#8 transferring context: 449.73kB 3.3s
#8 transferring context: 454.68kB 3.4s done
#8 CANCELED
------
 > [4/10] RUN export http_proxy=http://www-proxy-hqdc.us.oracle.com:80     https_proxy=http://www-proxy-hqdc.us.oracle.com:80     HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80     HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80     LC_ALL=en_US.utf-8 LANG=en_US.utf-8 PYTHONIOENCODING=utf-8     && curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > /tmp/install.sh     && chmod +x /tmp/install.sh     && /tmp/install.sh --accept-all-defaults --install-dir /u01/oracle/lib --exec-dir /usr/bin </dev/null     && rm -f /tmp/install.sh     && yes | oci setup autocomplete:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c export http_proxy=http://www-proxy-hqdc.us.oracle.com:80     https_proxy=http://www-proxy-hqdc.us.oracle.com:80     HTTP_PROXY=http://www-proxy-hqdc.us.oracle.com:80     HTTPS_PROXY=http://www-proxy-hqdc.us.oracle.com:80     LC_ALL=en_US.utf-8 LANG=en_US.utf-8 PYTHONIOENCODING=utf-8     && curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > /tmp/install.sh     && chmod +x /tmp/install.sh     && /tmp/install.sh --accept-all-defaults --install-dir ${ORACLE_HOME}/lib --exec-dir /usr/bin </dev/null     && rm -f /tmp/install.sh     && yes | oci setup autocomplete]: runc did not terminate sucessfully`
I examined the named line in the install script, and that looks pretty straightforward:
`361     $python_exe $install_script $install_args < $_TTY`

So, I can spend a lot of timetrying to hack round this, but am hoping it will get fixed in the official code line...

**Comment by kernleee** [comment]
@wajiii Can you run the script with --no-tty as a workaround for now?

**Comment by kernleee** [comment]
@wajiii Updated the script, should be ok now. Closing this issue.
If it is still occurring please feel free to reopen this.

**Comment by wajiii** [comment]
@kernleee I did a bit of digging on my own last night, and discovered the `--no-tty` parameter option in the script. 
That did the trick; thank you very much!
I find it quite interesting that `--accept-all-defaults` used to preclude requirement of specifiying `--no-tty`, but with this new command, that is no longer the case; it gives the impression that something was overlooked. :)

**Comment by kernleee** [comment]
Yep, it was an oversight on our part and a bug. But it has been removed and reverted, so it should be all sunshine now. You should be able to use the old `--accept-all-defaults` parameter only now without specifying an additional `--no-tty`
