### ISSUE TITLE
not compatible with zsh on Mac OS

### ISSUE THREAD

**Issue by ghost** [oracle/oci-cli#350]
Mac OS Catalina is using zsh by default, not bash.
Setting:

[[ -e "/<...>/lib/oracle-cli/lib/python3.8/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "/<...>/lib/oracle-cli/lib/python3.8/site-packages/oci_cli/bin/oci_autocomplete.sh"

will raise:

/<...>/lib/oracle-cli/lib/python3.8/site-packages/oci_cli/bin/oci_autocomplete.sh:12: command not found: complete

**Comment by jhult** [comment]
Not sure if this can or should be added into oci-cli but [this](https://github.com/eddiezane/lunchy/issues/57#issuecomment-448588918) solved the issue for me.

**Comment by kernleee** [comment]
I'll be closing this since this is not a cli specific issue and won't be introducing a specific fix for this. A possible cause for this issue is by curling the script install in a bash environment, users facing the issue should see the link above for a fix.
