### ISSUE TITLE
missing oci-cli-2.14.5.zip in the download location

### ISSUE THREAD

**Issue by linqing2004** [oracle/oci-cli#352]
Can not download from 
https://github.com/oracle/oci-cli/releases/download/v2.14.5/oci-cli-2.14.5.zip

Please correct the error. Thanks!

**Comment by kernleee** [comment]
@linqing2004 Sorry about that, I've updated the release. Please try again now.

**Comment by linqing2004** [comment]
It works now. Thanks!
