### ISSUE TITLE
need oci os command to create a folder inside a bucket

### ISSUE THREAD

**Issue by ammislam** [oracle/oci-cli#354]
Hello, 

I am using oci-cli regularly. Recently a request came that I need to create a new folder inside a bucket, also need to upload/download from a folder inside a bucket. 

I cannot find any command parameter to create a folder to an existing bucket or to upload/download from a folder/subfolder within a bucket. 

Need this option for automation purposes.

**Comment by adizohar** [comment]
# load current folder into cloud folder
oci os object bulk-upload --bucket-name bucket_name --src-dir . --object-prefix "cloud_folder/"

# list folder
oci os object list --bucket-name bucket_name --prefix "cloud_folder/"

**Comment by ammislam** [comment]
> ```
> # load current folder into cloud folder
> oci os object bulk-upload --bucket-name bucket_name --src-dir . --object-prefix "cloud_folder/"
> 
> # list folder
> oci os object list --bucket-name bucket_name --prefix "cloud_folder/"
> ```

I thought --object-prefix is used to naming the object, assigning prefix to object name. I want to add date to each object, in order to identify them by the date on the end of object name, using $dt variable on shell script. How can I do this? 

more precisely - I will upload on-prem db backup to object storage, so let's say 4 of today's update will name the object to backup1.<date1> , backup2.<date1>  this way, next day, new folder, then backup1.<date2> , backup2.<date2>, how can I do this? I thought using --object-prefix. 

also can you please help me how to use the --include paramater to sort/select specific files for bulk-upload?

**Comment by adizohar** [comment]
Hi, 
Folders at object storage is virtual folders, if you add prefix to the file with folder name it will count as folder

you can add prefix with date as well, or create folder with the date:

```
--prefix "backup_${dt}/"
```

Include form the documentation:

     --include [text]

       Only upload files which match the provided pattern. Patterns are  taken
       relative to the CURRENT directory. This option can be provided mulitple
       times to match on mulitple patterns. Supported pattern symbols are:

       *: Matches everything

       ?: Matches any single character

       [sequence]: Matches any character in sequence

       [!sequence]: Matches any character not in sequence
