### ISSUE TITLE
OCI Announcement is only delivered to tenant administrator.

### ISSUE THREAD

**Issue by vikash476** [oracle/oci-cli#359]
Currently, OCI Announcement is only delivered to the tenancy administrator. Mostly tenancy admins are unable to forward the notifications to administrators. All the OCI Administrators should also get the announcements in their mailbox.

**Comment by adizohar** [comment]
Hi Vikas, those issues are for OCI CLI, if you have issue with OCI Announcement, I would suggest to open SR for it at Oracle Support
For your info

**Comment by vikash476** [comment]
Closing the issue as clarified by adizohar

**Comment by vikash476** [comment]
Closing
