### ISSUE TITLE
Homebrew package for MacOS

### ISSUE THREAD

**Issue by suyashjoshi** [oracle/oci-cli#362]
Hi,

Can you make the OCI CLI Homebrew installable package for MacOS as the steps and process otherwise is too clunky and error prone. Homebrew is the easiest and most popular way to install utilities and tools on MacOS by far.

**Comment by mryanlam** [comment]
You can already brew install oci-cli
https://formulae.brew.sh/formula/oci-cli

**Comment by suyashjoshi** [comment]
Thanks Matt, that worked. It would be nice to have that mentioned in the README as well.
