### ISSUE TITLE
OpenSSL Warnings at Runtime

### ISSUE THREAD

**Issue by bmb5182** [oracle/oci-cli#367]
I recently started getting the following warning in some of my cli scripts:

usr/lib/python3.6/site-packages/oci/packages/cryptography/hazmat/bindings/openssl/binding.py:179: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will completely remove support for it.
  utils.CryptographyDeprecationWarning,
  
  Is there a fix for this or some version upgrade that I am missing? I'm installying via yum install -y python36-oci-cli

**Comment by kernleee** [comment]
Hi @bmb5182, this would not be an issue on the latest cli release because we require Python3 which would not cause this warning to appear. Please update to the latest version if not done already.
I'll be closing this issue.
