### ISSUE TITLE
dependency issue with oci-cli and macos+homebrew - must use outdated click,configparser,cryptography,pyOpenSSL,PyYAML,six

### ISSUE THREAD

**Issue by mickrussom** [oracle/oci-cli#369]
On MacOS 14 on a brew/homebrew setup the latest oci/oci-cli packages must have the following packages out-of-date

click        6.7     7.1.2
configparser 4.0.2   5.0.1
cryptography 3.2.1   3.3.1
pyOpenSSL    19.1.0  20.0.1
PyYAML       5.1.2   5.4.1
six          1.14.0  1.15.0

oci 2.30.0 requires configparser==4.0.2, but you have configparser 5.0.1 which is incompatible.
oci 2.30.0 requires cryptography==3.2.1, but you have cryptography 3.3.1 which is incompatible.
oci 2.30.0 requires pyOpenSSL<=19.1.0,>=17.5.0, but you have pyopenssl 20.0.1 which is incompatible.
oci-cli 2.21.0 requires click==6.7, but you have click 7.1.2 which is incompatible.
oci-cli 2.21.0 requires configparser==4.0.2, but you have configparser 5.0.1 which is incompatible.
oci-cli 2.21.0 requires cryptography==3.2.1, but you have cryptography 3.3.1 which is incompatible.
oci-cli 2.21.0 requires pyOpenSSL==19.1.0, but you have pyopenssl 20.0.1 which is incompatible.
oci-cli 2.21.0 requires PyYAML==5.1.2, but you have pyyaml 5.4.1 which is incompatible.
oci-cli 2.21.0 requires six==1.14.0, but you have six 1.15.0 which is incompatible.

**Comment by vish1** [comment]
@mickrussom 

These packages have now been updated in the latest CLI version - cryptography, pyYAML and six

- Click will be updated to 7.1.2 in the upcoming release
- Configparser and pyOpenSSL will be updated in the future.
