### ISSUE TITLE
Add support for new OCI storage type - File Systems (aka File Storage Service)

### ISSUE THREAD

**Issue by gcstang** [oracle/oci-cli#37]
Oracle [recently announced](https://blogs.oracle.com/cloud-infrastructure/introducing-oracle-cloud-infrastructure-file-storage-service) the public availability of Oracle Cloud Infrastructure File Storage Service (FSS) in all OCI regions. Here is the [File Storage Service API](https://docs.us-phoenix-1.oraclecloud.com/api/#/en/filestorage/20171215/).

**Comment by nathan-vu** [comment]
Thanks for reaching out - support for FSS is currently scheduled for our next release. We'll update this issue when it's out or if there's any news of significance before then

**Comment by nathan-vu** [comment]
Apologies for the lack of update here. We had a release ([2.4.16](https://pypi.python.org/pypi/oci-cli)) of the CLI yesterday but this doesn't include support for FIle Storage Service.

We encountered some issues while doing this work and so need a bit more time to iterate on this experience for our SDK, CLI and programmatic access customers. We'll post further updates once support is released or if there's other news before that point.

**Comment by nathan-vu** [comment]
We've released v2.4.17 of the CLI and this includes support for File Storage Service. A basic example of calling these operations in the CLI can be found [here](https://github.com/oracle/oci-cli/blob/master/scripts/file_storage_example.sh)
