### ISSUE TITLE
Cannot import Custom Image from-object with instance_principal

### ISSUE THREAD

**Issue by jeliker** [oracle/oci-cli#384]
Creating Custom Image from Object Storage bucket object is failing when using Instance Principal.

Consider this scenario

* QCOW2 image exists in Object Storage bucket Compartment "Migration"
* Intent is to import and create new Custom Image in Compartment "Apps"
* Instance Principal has been granted (temporarily) policy "allow dynamic group MigrationHost to manage all-resources in tenancy"

```
$ oci os object list --auth instance_principal --bucket-name $MY_BUCKET --namespace $MY_NS --fields name --prefix myimage.qcow2
{
  "data": [
    {
      "etag": null,
      "md5": null,
      "name": "myimage.qcow2",
      "size": null,
      "time-created": null,
      "time-modified": null
    }
  ],
  "prefixes": []
}

$ oci compute image import from-object --auth instance_principal --compartment-id $TARGET_COMP --display-name myimage --launch-mode PARAVIRTUALIZED --namespace $MY_NS --bucket-name $MY_BUCKET --name myimage.qcow2 --source-image-type QCOW2
ServiceError:
{
    "code": "InvalidParameter",
    "message": "Invalid objectName: Specified object or bucket or namespace to import image from does not exist",
    "opc-request-id": "C6A5591993327EE3CF7279489521B6C3/CA5CFAAF4CFB91606974817A22274ADE/491E1052DEC6BFE3618EE1924AFAF818",
    "status": 400
}
```

**Comment by jeliker** [comment]
I have just confirmed above command using API-key authentication (not instance principal) works as expected.

Also I have created a simple `~/.oci/config` file containing only this (below) and still the same error as shown above.

```
[DEFAULT]
tenancy=[MY TENANCY OCID]
```

**Comment by jeliker** [comment]
Confirmed issue still persists

**Comment by TajMahPaul** [comment]
Are you able to list the buckets in your compartment?

**Comment by jimmywutangclan** [comment]
I'm currently experiencing the same issue occurring here, on OCI CLI version 3.2.2 and OCI Python SDK version 2.49.1 on Python 3.6.8. When I try to use the instance principal to create a custom image with the OCI Python SDK, I get the same error. This leads me to suspect that there's a bug in the Python SDK.

This command is able to successfully return the list of all the buckets within the compartment:
`oci os bucket list --auth instance_principal --compartment-id ocid1.compartment.oc1..aaaaaaaar4...`

The same command that was run above, to import a custom image, results in an identical error as the one above
```
{
    "code": "InvalidParameter",
    "message": "Invalid objectName: Specified object or bucket or namespace to import image from does not exist",
    "opc-request-id": "FD3C047100404B6AA6DBCDB050B6D347/FD614F6CB6F5EB6BE2B0EE9C1BABCB48/7D26FE16118F8D3B57A8A29ACA51B31C",
    "status": 400
}
```

The command `cat /etc/os-release` returns
```
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

```

**Comment by jhult** [comment]
@vish1, @kernleee, @harshkumar-dev,

Any ideas on getting this resolved?

**Comment by franciscvass** [comment]
HI,
I'm having the same issue.
The same piece of code (create custom img importing from bucket) works if I authenticate with API key but does not works if I try with instance or resource principal. However, the issues seams to be related with obj storage as it is working either way if I simply create cust img from compute instance.

**Comment by harshkumar-dev** [comment]
hi @franciscvass  Could you confirm the follow:

1) You are running the command from an --auth instance_principal
2) Your instance principal setup is correct. i.e run some other CLI command to confirm 

if you still have same error, could you please send the terminal output with exact error?

**Comment by harshkumar-dev** [comment]
We have identified an issue with API and we will fix the API in future release. 

For now, please follow this as a workaround.


Workaround is to split SDK or CLI call into 2 commands
Get a pre-authenticated request for the image file you want to import from object storage
Use the pre-authenticated request in the "oci compute image import" call, rather than trying to reference the image file in object storage directly


https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.17.0/oci_cli_docs/cmdref/compute/image/import/from-object-uri.html
https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.17.0/oci_cli_docs/cmdref/os/preauth-request/create.html



oci os preauth-request create --namespace <object_storage_namespace> --bucket-name <bucket_name> --name MyObjectReadPAR --access-type ObjectRead -time-expires <timestamp> --object-name <the name of your image file>

# For import command, you use from-object-uri instead of from-object
oci compute image import from-object-uri --uri <your URI from the above command> --auth instance_principal --compartment-id <compartment for resulting image> --display-name <display name for resulting image> --launch-mode PARAVIRTUALIZED --source-image-type VMDK

**Comment by franciscvass** [comment]
Hi,
we implemented the WA provided using the OCI python SDK and its working. It should works with OCI CLI as well.
basically we generate a PAR for the object and we use that PAR instead of object URI to import the image.
Thanks.

**Comment by simengineering** [comment]
I ran into this issue today.
When you are creating the PAR it lists data attributes, one of which is "access-uri" "/p/RnAP-xxxxx"
How do I use the PAR "instead" of object URI?
Could you demo the PAR generation command and then the subsequent oci compute image import command
to include the PAR?
Thanks very much.

**Comment by franciscvass** [comment]
HI,

Basically to access_uri returned by PAR creation :
oci.object_storage.ObjectStorageClient(config={}).create_preauthenticated_request()
you need to add the endpoint of the bucket . You can get this from:
oci.object_storage.ObjectStorageClient(config={}).obj_client.base_client.endpoint

and when you call create_image from oci.core.ComputeClient you pass this
endpoint + access_uri to source_uri argument as below:

create_img_response = oci.core.ComputeClient(config={}).create_image(
        create_image_details = oci.core.models.CreateImageDetails(
            display_name            =...,

            compartment_id          = v_comp_id

            launch_mode             = "NATIVE",
            image_source_details    =
oci.core.models.ImageSourceViaObjectStorageUriDetails(
                source_image_type   = "VMDK",
                source_uri          = v_endpoint + v_uri
                ,source_type = "objectStorageUri"
                )
            )
    )

I hope that helped.

**Comment by simengineering** [comment]
Yes it helped very much thanks!

**Comment by KartikShrikantHegde** [comment]
Closing this ticket as a resolution has been found based on the comments above. Please feel free to reopen the ticket in case of a problem.
