### ISSUE TITLE
Offline install bundle for Windows Server 2016 is no longer available from 2.22.0?

### ISSUE THREAD

**Issue by hitsumabushi845** [oracle/oci-cli#390]
Hello.

I'm using offline install bundle, provided from v2.21.5,  to install oci-cli on network restricted environment.  
Until v2.21.6, it provides the module for Windows Server 2016, but the latest version(v2.22.0) doesn't provide it.
Is it no longer available from 2.22.0?

If the bundle for Windows Server 2019 can be used for Windows Server 2016, I'll use it.

**Comment by HamadaGabrIbrahim** [comment]
@hitsumabushi845 Sorry for the inconvenience. It is still supported, but we had an issue releasing it last week. It will be released today.

**Comment by HamadaGabrIbrahim** [comment]
@hitsumabushi845 The Offline install bundle for Windows Server 2016 is released https://github.com/oracle/oci-cli/releases/tag/v2.22.0. I will go ahead and close the issue
