### ISSUE TITLE
AttributeError: module 'oci' has no attribute 'identity'

### ISSUE THREAD

**Issue by Xachman** [oracle/oci-cli#420]
running 

```
oci setup bootstrap
```
gives me this after browser authentication 

```
AttributeError: module 'oci' has no attribute 'identity'
```

**Comment by kernleee** [comment]
Hi, which version of the cli do you have? Issue should have been fixed with 2.25.1+

**Comment by Xachman** [comment]
2.25.2 But I think I have no idea what the bootstrap command does.  I ended up using oci setup config instead.  And that seems to have worked for my initial setup.

**Comment by kernleee** [comment]
Great, setup bootstrap is another way of building the config, but glad to hear it's working.
Took another look at it and it was a bug, it'll be fixed for the next release.
