### ISSUE TITLE
nlb network-load-balancer does not work

### ISSUE THREAD

**Issue by whoever42** [oracle/oci-cli#426]
oci nlb network-load-balancer get --network-load-balancer-id <ocid1.loadbalancer.....>
returns NotAuthorizedOrNotFound

# oci -v
2.26.0

even in Cloud shell in OCI Web management, with particular load balancer being open in the same browser tab (so, same user, same permissions) (v2.25.4)

**Comment by adizohar** [comment]
I checked it and it worked well, please make sure you are checking networkloadbalancer and not normal load balancer
oci nlb network-load-balancer get --network-load-balancer-id ocid1.networkloadbalancer.oc1.iad.amaaaaaaafha7wiacsq2txllk3bkbdjacemxqzfvxplxb...

OCID must have networkloadbalancer.

**Comment by whoever42** [comment]
Apologies, apparently I didn't know there are different types of load balancers ... I owe you a coffee
