### ISSUE TITLE
install.ps1 fails - Directory test not sufficient if key exists but is empty. 

### ISSUE THREAD

**Issue by EscVector** [oracle/oci-cli#43]
Directory test not sufficient if key is empty. 

Certain programs like Anaconda or other Python installs that might have installed into the HKLM, if removed, my leave that path blank.  Likewise, with HKCU.  If either of these directory checks returns TRUE, but returns zero child objects, the script fails with 

You cannot call a method on a null-valued expression.
At C:\Users\admin72014\Projects\oci\oci-cli\scripts\install\install.ps1:108 char:44
+             If ($installation.Name.EndsWith <<<< ("\InstallPath")) {
    + CategoryInfo          : InvalidOperation: (EndsWith:String) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

![image](https://user-images.githubusercontent.com/120213/36438624-7d070a84-1638-11e8-8d31-258fcb7f0aec.png)

Commenting out the empty key allows installation to proceed.

**Comment by mross22** [comment]
Thanks for filing this issue and for adding the accompanying pull request!  The change looks good, I want to do some quick validation and then I can sign off so you can merge.

**Comment by mross22** [comment]
Closed by pull request #44
