### ISSUE TITLE
I don't know where is the error "code": "InvalidParameter",     "message": "Unable to process JSON input" coming from where in my JSON file

### ISSUE THREAD

**Issue by doratina** [oracle/oci-cli#433]
I have made a JSON file to deploy instances automatically because the region I'm on is currently full when I try to deploy instances manually

command for deploying:
`oci compute instance launch --from-json file://auto.json`

error:
`ServiceError:
{
    "code": "InvalidParameter",
    "message": "Unable to process JSON input",
    "opc-request-id": "1B631AE04F164FA5B8CAAF84A68F3E90/621C9F507CF535143F27DF42C6B0393B/4EF9CD28B613296542E54FD3CC81DFEE",
    "status": 400
}`

JSON:
`{
	"assignPublicIp":true,
	"availabilityDomain":"nVnj:AP-TOKYO-1-AD-1",
	"compartmentId":"ocid1.tenancy.oc1..aaaaaaaatzt4zpica7f4pswyxe3pupy4q4mt4eb3c33k6lxfhairknq4g5pq",
	"displayName":"mcserver",
	"hostnameLabel":"vwerty",
	"imageId":"ocid1.image.oc1.ap-tokyo-1.aaaaaaaavpko5qipin7c2lfn5l74vunedrjfeiym4pkibosdbtzqbnocoffa",
	"privateIp":"192.168.1.100",
	"shape":"VM.Standard.A1.Flex",
	"shapeConfig":{
		"baselineOcpuUtilization":"string",
		"memoryInGBs":6,
		"ocpus":2
	},
	"sshAuthorizedKeysFile":"/home/nguyen/.oci/ssh.pub",
	"subnetId":"ocid1.subnet.oc1.ap-tokyo-1.aaaaaaaa6fy4br7xswxw4zgkjeykx3miwpont36blekibqfvhgcmk2q5xiea"
}
`

**Comment by vish1** [comment]
@doratina The error is due to the `"baselineOcpuUtilization":"string"` parameter not filled up. Please use one of the valid values from [here](https://docs.oracle.com/en-us/iaas/api/#/en/iaas/20160918/datatypes/LaunchInstanceShapeConfigDetails). Please re-open if you face any issues.
