### ISSUE TITLE
please support a `sync` command for oci-cli

### ISSUE THREAD

**Issue by kilokahn** [oracle/oci-cli#435]
When copying the modified contents of a large directory to an objectstorage bucket, we have to do a multi-step workflow of using making a [get (using head)](https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.26.4/oci_cli_docs/cmdref/os/object/head.html) on each of the files in the directory to identify the files that are modified by comparing local vs remote. After doing the check, we identify the objects that need to be uploaded and then call [put on those modified files](https://docs.oracle.com/en-us/iaas/tools/oci-cli/2.26.4/oci_cli_docs/cmdref/os/object/put.html) individually. From a customer's point of view, a `sync` command that does this for a directory will be hugely useful as command sugaring. A colleague pointed out a few blogs from Oracle (see references) which utilizes `rclone` via the S3 compatibility API, and it is a viable workaround. I wanted to add this ticket to see if there is interest in other customers to see it available natively in the OCI CLI without having to install `rclone`. There are other contrived advantages of secure key sharing in going via the API keys and supporting easy setup, but are secondary in nature.

References:
- https://blogs.oracle.com/linux/post/using-rclone-to-copy-data-in-and-out-of-oracle-cloud-object-storage
- https://docs.oracle.com/en/solutions/move-data-to-cloud-storage-using-rclone/index.html#GUID-13EF8474-9517-4043-9638-8EE04FE6C565
- https://rclone.org/

**Comment by vish1** [comment]
@kilokahn Thanks for the suggestion. This feature will be released in the upcoming release.

**Comment by vish1** [comment]
Release in v3.0.0: https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.0.0/oci_cli_docs/cmdref/os/object/sync.html#sync

**Comment by kilokahn** [comment]
This is amazing! Thank you so much CLI team 🎉
