### ISSUE TITLE
Loosen pip requirements (semver dependencies)

### ISSUE THREAD

**Issue by robert-heinzmann-logmein** [oracle/oci-cli#439]
Hello, 
we are using the official packer image (hashicorp/packer:1.7.4) from hashicorp (slim version, which is based on alpine 3.14) to build custom images for AWS as well as Oracle Cloud in multiple regions. 

Packer supports image copy natively for AWS but not for OCI, so we have to workaround (different issue).

To copy the image to other regions, post build, we need to add the oci-cli to the official packer image to copy the image between regions post build as a shell script. (e.g. pip install oci-cli)

Currently the oci-cli is using "six=1.14.0", while the alpine image only provided "six=1.15.0". This is also true for other dependencies, which are really specific. Currently we mitigated this by using a venv and building almost all things from source. However, this is quite cumbersome. 

It would be great if the requirements.txt could follow a semver approach (e.g. six>=1.14.0,<2.0) for all modules backed by native libraries, which have a lot of build dependencies.

Thanks.

**Comment by vish1** [comment]
@robert-heinzmann-logmein This issue has now been fixed in the latest CLI release 3.0.1. ([Link](https://github.com/oracle/oci-cli/blob/master/setup.py#L41))
