### ISSUE TITLE
oci db cloud-vm-cluster update  "Authorization failed or requested resource not found."

### ISSUE THREAD

**Issue by ladak44** [oracle/oci-cli#445]
Hello,
I try to scale up my exacs service using this command and i receive error below.
This works fine from Web Console.

ci db cloud-vm-cluster update --cloud-vm-cluster-id ocid1.dbsystem.oc1.eu-frankfurt1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq \
> --cpu-core-count 28
ServiceError:
{
    "code": "NotAuthorizedOrNotFound",
    "message": "Authorization failed or requested resource not found.",
    "opc-request-id": "DB0DE128941F4800813506717F9456B7/BB24A7F8E6CF9AE940DADE6BA1707180/FB8408DEB362A6D15C654DC0ED78AC03",
    "status": 404
}

**Comment by ladak44** [comment]
This resource exists. I can see when i run this command.
(ENV) [a-cke-marclad@lxans001p exa]$ **oci db cloud-vm-cluster list --compartment-id** ocid1.compartment.oc1..aaaaaaaalwkwvvzba76ie33bn6cvybuhq7p7ynvrbdvac426vnqmwcusml5q
{
  "data": [.....

    "disk-redundancy": "HIGH",
      "display-name": "ckexafra2",
      "domain": "exa2client.vcnprv.oraclevcn.com",
      "freeform-tags": {},
      "gi-version": "19.12.0.0.0",
      "hostname": "ckexafra2-bhyl4",
      "id": "ocid1.dbsystem.oc1.eu-frankfurt-1.abtheljsbrlk62xdw3tjkciqqz3vwgnap7e5oxmhp5arbrnthp3leitqvuzq",
      "is-local-backup-enabled": false,
      "is-sparse-diskgroup-enabled": false,
      "last-update-history-entry-id": "ocid1.dbpatchhistory.oc1.eu-frankfurt-1.abtheljspjnnrortsacxlgqwfxikww6xiuab6jibcqrrxsbjaxcbqncnkunq",
      "license-model": "LICENSE_INCLUDED",
      "lifecycle-details": null,
      "lifecycle-state": "AVAILABLE",
      "listener-port": 1521,
...

**Comment by vish1** [comment]
@ladak44  The error mentions `NotAuthorizedOrNotFound`. If the resource exists, can you please check and confirm if you have the right policies as a user to update the resource?

**Comment by ladak44** [comment]
Yes, this resource exists. I can update this resource using web console, using the same user which is used in oci cli setup. It's odd.

**Comment by vish1** [comment]
@ladak44 Is the user a federated or local user?

**Comment by ladak44** [comment]
This is federated user.

**Comment by KartikShrikantHegde** [comment]
Hi @ladak44 , can you confirm if you are still facing this issue? If you do, would you mind sharing the opc-request-id with us so that I can have an Engineer look into it?

**Comment by KartikShrikantHegde** [comment]
Hi @ladak44 , I will be closing this ticket, please feel free to re-open it if you are still running into the issue.
