### ISSUE TITLE
OCI PUT command fails in the middle of a disrupted connection without a retry

### ISSUE THREAD

**Issue by rsabdar** [oracle/oci-cli#446]
OCI PUT command fails if there are TCP connection issues such as timeout, TCP reset, or server unresponsive without any retries. 
The expectation is that the OCI CLI PUT command should retry the underlying TCP connection to resume the upload otherwise PUT should be repeated which could cost extra time and space if the object is very large.

Details:- 
--------- 
1) Trigger an OCI PUT command on a large File  
2) while the PUT command is in progress trigger network disruption via connection reset on the server side (node takeover/failback, etc)

The PUT operation which is in progress fails with following error: 
    RequestException: ('Connection aborted.', ConnectionResetError(104,  'Connection reset by peer')) 

Log:- 
--------- 
echo y|/root/bin/oci os object put --config-file /tmp/oci_config/b7420-02m_oci_plan_002_user_65bbbc7a3148b6f12791517f0c9f11c1_2021_04_05_11_47_34_Config --endpoint http://10.80.198.217/oci --namespace  export/oci_plan_002_project/oci_plan_002_filesystem --bucket-name plan_002_bucket --file  /net/qsestor01/export/os8.8_micros/job_data00/ParmFiles/oci_API/upload_data/10GB_files/10GB_1  --name 10GB_1 

WARNING: This object already exists. Are you sure you want to overwrite it?  
[y/N]: Upload ID: 6afa36b3-f0d1-4dd9-b67b-aba2129ff237 
Split file into 80 parts for upload. 
^[[?25lUploading object  [------------------------------------]    0% 
^[[?25lUploading object  [------------------------------------]    1%  0d  
00:04:30 
^[[?25lUploading object  [------------------------------------]    2%  0d  
00:03:43 
^[[?25lUploading object  [#-----------------------------------]    3%  0d  
00:03:50 
^[[?25lUploading object  [#-----------------------------------]    5%  0d  
00:03:47 
^[[?25lUploading object  [##----------------------------------]    7%  0d  
00:03:41 
^[[?25lUploading object  [###---------------------------------]    8%  0d  
00:03:18 
^[[?25lUploading object  [###---------------------------------]   10%  0d  
00:03:15 
^[[?25lUploading object  [####--------------------------------]   11%  0d  
00:02:58 
^[[?25lUploading object  [####--------------------------------]   12%  0d  
00:02:45 
^[[?25lUploading object  [####--------------------------------]   13%  0d  
00:02:35 
^[[?25lUploading object  [#####-------------------------------]   15%  0d  
00:02:33 
^[[?25lUploading object  [#####-------------------------------]   16%  0d  
00:02:31 
^[[?25lUploading object  [######------------------------------]   17%  0d  
00:02:11 
^[[?25lUploading object  [######------------------------------]   18%  0d  
00:02:09 
^[[?25lUploading object  [#######-----------------------------]   20%  0d  
00:02:07 
^[[?25lUploading object  [#######-----------------------------]   21%  0d  
00:01:58 
^[[?25lUploading object  [########----------------------------]   22%  0d  
00:01:40 
^[[?25lUploading object  [########----------------------------]   23%  0d  
00:01:35 
^[[?25lUploading object  [#########---------------------------]   25%  0d  
00:01:33 
^[[?25lUploading object  [#########---------------------------]   26%  0d  
00:01:30 
^[[?25lUploading object  [#########---------------------------]   27%  0d  
00:01:28 
^[[?25lUploading object  [##########--------------------------]   28%  0d  
00:01:26 
^[[?25lUploading object  [##########--------------------------]   30%  0d  
00:01:24 
^[[?25lUploading object  [###########-------------------------]   31%  0d  
00:01:23 
^[[?25lUploading object  [###########-------------------------]   32%  0d  
00:01:19 
^[[?25lUploading object  [############------------------------]   33%  0d  
00:01:18 
^[[?25lUploading object  [############------------------------]   35%  0d  
00:01:16 
^[[?25lUploading object  [#############-----------------------]   36%  0d  
00:01:14 
^[[?25lUploading object  [#############-----------------------]   37%  0d  
00:01:12 
^[[?25lUploading object  [#############-----------------------]   38%  0d  
00:01:11 
^[[?25lUploading object  [##############----------------------]   40%  0d  
00:01:08 
^[[?25lUploading object  [##############----------------------]   41%  0d  
00:01:07 
^[[?25lUploading object  [###############---------------------]   42%  0d  
00:01:05 
^[[?25lUploading object  [###############---------------------]   43%  0d  
00:01:04 
^[[?25lUploading object  [################--------------------]   45%  0d  
00:01:02 
^[[?25lUploading object  [################--------------------]   46%  0d  
00:01:00 
^[[?25lUploading object  [#################-------------------]   47%  0d  
00:00:59 
^[[?25lUploading object  [#################-------------------]   48%  0d  
00:00:57 
^[[?25lUploading object  [##################------------------]   50%  0d  
00:00:56 
^[[?25lUploading object  [##################------------------]   51%  0d  
00:00:54 
^[[?25lUploading object  [##################------------------]   52%  0d  
00:00:52 
^[[?25lUploading object  [###################-----------------]   53%  0d  
00:00:50 
^[[?25lUploading object  [###################-----------------]   55%  0d  
00:00:49 
^[[?25lUploading object  [####################----------------]   56%  0d  
00:00:47 
^[[?25lUploading object  [####################----------------]   57%  0d  
00:00:46 
^[[?25lUploading object  [#####################---------------]   58%  0d  
00:00:45 
^[[?25lUploading object  [#####################---------------]   60%  0d  
00:00:43 
^[[?25lUploading object  [######################--------------]   61%  0d  
00:00:42 
^[[?25lUploading object  [######################--------------]   62%  0d  
00:00:40 
^[[?25lUploading object  [######################--------------]   63%  0d  
00:00:39 
^[[?25lUploading object  [#######################-------------]   65%  0d  
00:00:37 
^[[?25lUploading object  [#######################-------------]   66%  0d  
00:00:36 
^[[?25lUploading object  [########################------------]   67%  0d  
00:00:35 
^[[?25lUploading object  [########################------------]   68%  0d  
00:00:33 
^[[?25lUploading object  [#########################-----------]   70%  0d  
00:00:32 
^[[?25lUploading object  [#########################-----------]   71%  0d  
00:00:31 
^[[?25lUploading object  [##########################----------]   72%  0d  
00:00:29 
^[[?25lUploading object  [##########################----------]   73%  0d  
00:00:28 
^[[?25lUploading object  [###########################---------]   75%  0d  
00:00:27 
^[[?25lUploading object  [###########################---------]   76%  0d  
00:00:25 
^[[?25lUploading object  [###########################---------]   77%  0d  
00:00:25 
^[[?25lUploading object  [############################--------]   78%  0d  
00:00:24 
^[[?25lUploading object  [############################--------]   80%  0d  
00:00:23 
^[[?25lUploading object  [#############################-------]   81%  0d  
00:00:22 
^[[?25lUploading object  [#############################-------]   82%  0d  
00:00:21 
^[[?25lUploading object  [##############################------]   83%  0d  
00:00:20 
^[[?25lUploading object  [##############################------]   85%  0d  
00:00:19 
^[[?25lUploading object  [###############################-----]   86%  0d  
00:00:18 
^[[?25lUploading object  [###############################-----]   87%  0d  
00:00:17 
^[[?25lUploading object  [###############################-----]   88%  0d  
00:00:16^[[?25h 
RequestException: ('Connection aborted.', ConnectionResetError(104,  
'Connection reset by peer'))

**Comment by vish1** [comment]
@rsabdar Which version of the CLI are you running? Object put command does have retries enabled in the latest version.

**Comment by rsabdar** [comment]
version 2.26.3. What is the minimum version required? 3.0.x?

**Comment by vish1** [comment]
@rsabdar That version is good. The Python SDK, which the CLI uses, implements the retries for these operations - it does [retry on `RequestException`](https://github.com/oracle/oci-python-sdk/blob/99f12c53a29422ca48a4be3ceacb1986dedfdb70/src/oci/retry/retry_checkers.py#L155)  For multipart upload operations, each multipart upload is [retried 60 times](https://github.com/oracle/oci-cli/blob/3170664f2a6b540d929346883b4ef3f95fed746f/services/object_storage/src/oci_cli_object_storage/objectstorage_cli_extended.py#L736). Are you able to reproduce this issue?

**Comment by rsabdar** [comment]
Our client python is 2.7.5 and server's is 3.7.10. Is it possible that it affects the SDK behavior as far as retry behavior for OCI CLI? We can consistently reproduce this using the current version (CLI v2.26.3)

**Comment by rsabdar** [comment]
After upgrade and trying with several disruption scenarios (server takeover, failback) OCI CLI retried multi-part upload and it went through. Closing this issue
