### ISSUE TITLE
windows 2016 oci-cli installation failure

### ISSUE THREAD

**Issue by PavelVakulov** [oracle/oci-cli#448]
(New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1') > c:\temp\install_ocicli.ps1

c:\temp\install_ocicli.ps1 -AcceptAllDefaults
VERBOSE: No valid Python installation found.
VERBOSE: Downloading Python...
VERBOSE: Download Complete! Installer executable written to: C:\Users\xx\AppData\Local\Temp\2\tmp7AFA.tmp.exe
VERBOSE: Installing Python to C:\Users\xx\Python...
VERBOSE: Successfully installed Python!
VERBOSE: Downloading install script to C:\Users\xx\AppData\Local\Temp\2\tmp3F64.tmp
VERBOSE: C:\Users\xx\Python True    False
VERBOSE: Using Python executable: C:\Users\xx\Python\python.exe to run install script...
VERBOSE: Arguments to python script: "C:\Users\xx\AppData\Local\Temp\2\tmp3F64.tmp" --accept-all-defaults
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Temp\2\tmp3F64.tmp", line 28, in <module>
    if os.geteuid() == 0:
AttributeError: module 'os' has no attribute 'geteuid'
C:\temp\install_ocicli.ps1 : Executing C:\Users\xx\Python\python.exe
"C:\Users\xx\AppData\Local\Temp\2\tmp3F64.tmp" --accept-all-defaults returned a non-zero exit code.
At line:1 char:1
+ c:\temp\install_ocicli.ps1 -AcceptAllDefaults
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,install_ocicli.ps1
	

python.exe
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.geteuid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'geteuid'
>>> dir(os)
['DirEntry', 'F_OK', 'MutableMapping', 'O_APPEND', 'O_BINARY', 'O_CREAT', 'O_EXCL', 'O_NOINHERIT', 'O_RANDOM', 'O_RDONLY', 'O_RDWR', 'O_SEQUENTIAL', 'O_SHORT_LIVED', 'O_TEMPORARY', 'O_TEXT', 'O_TRUNC', 'O_WRONLY', 'P_DETACH', 'P_NOWAIT', 'P_NOWAITO', 'P_OVERLAY', 'P_WAIT', 'PathLike', 'R_OK', 'SEEK_CUR', 'SEEK_END', 'SEEK_SET', 'TMP_MAX', 'W_OK', 'X_OK', '_Environ', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_execvpe', '_exists', '_exit', '_fspath', '_get_exports_list', '_putenv', '_unsetenv', '_wrap_close', 'abc', 'abort', 'access', 'altsep', 'chdir', 'chmod', 'close', 'closerange', 'cpu_count', 'curdir', 'defpath', 'device_encoding', 'devnull', 'dup', 'dup2', 'environ', 'errno', 'error', 'execl', 'execle', 'execlp', 'execlpe', 'execv', 'execve', 'execvp', 'execvpe', 'extsep', 'fdopen', 'fsdecode', 'fsencode', 'fspath', 'fstat', 'fsync', 'ftruncate', 'get_exec_path', 'get_handle_inheritable', 'get_inheritable', 'get_terminal_size', 'getcwd', 'getcwdb', 'getenv', 'getlogin', 'getpid', 'getppid', 'isatty', 'kill', 'linesep', 'link', 'listdir', 'lseek', 'lstat', 'makedirs', 'mkdir', 'name', 'open', 'pardir', 'path', 'pathsep', 'pipe', 'popen', 'putenv', 'read', 'readlink', 'remove', 'removedirs', 'rename', 'renames', 'replace', 'rmdir', 'scandir', 'sep', 'set_handle_inheritable', 'set_inheritable', 'spawnl', 'spawnle', 'spawnv', 'spawnve', 'st', 'startfile', 'stat', 'stat_float_times', 'stat_result', 'statvfs_result', 'strerror', 'supports_bytes_environ', 'supports_dir_fd', 'supports_effective_ids', 'supports_fd', 'supports_follow_symlinks', 'symlink', 'sys', 'system', 'terminal_size', 'times', 'times_result', 'truncate', 'umask', 'uname_result', 'unlink', 'urandom', 'utime', 'waitpid', 'walk', 'write']
>>>

**Comment by harshkumar-dev** [comment]
Fix has been made.
