### ISSUE TITLE
`oci network ipv6 list` example does not work

### ISSUE THREAD

**Issue by i-g-k** [oracle/oci-cli#454]
`oci network ipv6 list -h` gives `oci network ipv6 list` as an example. Running `oci network ipv6 list` returns an error:

> `ServiceError:
{
    "code": "MissingParameter",
    "message": "Missing Parameter",
    "opc-request-id": "<redacted>",
    "status": 400
}`

as does `oci network ipv6 list --all`.

Occurs today via Cloud Shell with oci-cli v3.0.5.

**Comment by niskulka71** [comment]
You need to either provide the vnic ocid, or the subnet ocid, or the subnet ocid and ipv6 address as input arguments. The documentation is also updated to reflect the same.
