### ISSUE TITLE
Add md5-checking mode or retry to `oci os object bulk-upload`

### ISSUE THREAD

**Issue by tedpearson** [oracle/oci-cli#46]
My usage of the `oci os object bulk-upload` here at the oracle data cloud involves uploading 1.3TB of files each day. If for some reason there are errors when doing that, it would be nice to have a new mode in addition to `--no-overwrite` and `--overwrite` that checked file md5sums before uploading, and only overwrites if the sums don't match.

I know md5sums are stored on upload, so it seems like a feature that would be fairly easily supported.

I am aware that the json returned by the command returns the failed uploads. It would certainly be possible to parse that json and just overwrite those files with some more more external commands. Another option could be having the bulk-upload function add a retry functionality (during uploading, or accepting the json output from the `"upload-failures": {` in the json.)

Thanks for your consideration.

**Comment by viralmodi** [comment]
Hi Ted,

Thank you for your suggestion. We will look into it and respond back.

**Comment by viralmodi** [comment]
We looked into this suggestion and decided as something that is good to have. We will update this thread again when we start working on it.

**Comment by tedpearson** [comment]
Thanks.

**Comment by kernleee** [comment]
This is an old ticket, the --verify-checksum flag in `oci os object bulk-upload` solves this issue so I'll be closing it.
https://docs.cloud.oracle.com/en-us/iaas/tools/oci-cli/2.12.6/oci_cli_docs/cmdref/os/object/bulk-upload.html
