### ISSUE TITLE
Support for compartment id in profile

### ISSUE THREAD

**Issue by jhorwit2** [oracle/oci-cli#47]
It'd be really nice if we could configure the compartment id in the config as part of the profile since OCIDs aren't something that you can easily just type out on demand. It'll greatly increase the usability of the client.

**Comment by nathan-vu** [comment]
Sorry if I'm misunderstanding, but I think this is already possible using a CLI configuration file (see: https://docs.us-phoenix-1.oraclecloud.com/Content/API/SDKDocs/cliconfigure.htm#UsingaFileforCLIConfigurations)

As an example, I have my `oci_cli_rc` file with the following:

```
[DEFAULT]
compartment-id=ocid1.compartment.oc1..aaa<snip>
```

So for any command I issue with given profile (`DEFAULT` in this case) the CLI will use the value above whenever a `compartment-id` parameter is required. So I can run, say, `oci compute instance list` and I don't have to specify a compartment OCID:

```
oci compute instance list
{
  "data": [
    {
      "availability-domain": "kIdk:PHX-AD-1",
      "compartment-id": "ocid1.compartment.oc1..aaaaaa<snip>",
      "defined-tags": {},
      "display-name": "Mike Test Win Server Instance",
....
```

However, if I run with a different profile I still have to specify a compartment OCID:

```
oci compute instance list --profile ADMIN
Usage: oci compute instance list [OPTIONS]

Error: Missing option(s) --compartment-id.
```

Sorry again if I've missed the point here, but let me know & I'll try and give a better answer :-)

**Comment by jhorwit2** [comment]
Ah yeah that's exactly what I wanted. Definitely missed this on my quick skim 👼 

thanks @nathan-vu
