### ISSUE TITLE
bucket delete --empty

### ISSUE THREAD

**Issue by franciscvass** [oracle/oci-cli#473]
HI,
tried bucket delete with --empty and got the below error:

[opc@vm]$ oci --version
3.2.2
[opc@vm]$ oci os bucket delete -bn oci-dv-mysql-201 --empty --profile NNVF
This command will delete the bucket as well as all objects, pre-authenticated requests, uncommitted multipart uploads and replication policies associated with it. Are you sure you wish to continue? [y/N]: y
AttributeError: 'list' object has no attribute 'items'

**Comment by lodotek** [comment]
@mandyht @anup-21 @pankajmjx or any member of Oracle, can someone please take a look at this? 

Thanks in advance...

**Comment by adizohar** [comment]
did you upgrade to latest code ? pip3 install --upgrade oci oci-cli ? 
New changes pushed that fixed it, I tried and it worked for me.
Please advise.

**Comment by KartikShrikantHegde** [comment]
Just tried and it works for me as well. I am using v3.9.1.

**Comment by mandyht** [comment]
Please upgrade cli to a more recent version and try the command again.
As of March 16, we are on version 3.23.4: https://github.com/oracle/oci-cli/releases

Here is our upgrade guide: [Upgrading the CLI](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliupgrading.htm)

**Comment by lodotek** [comment]
> 

Thanks for the quick reply! That worked :-)  I am using the cloudshell, so I had to do `pip3 install --upgrade --user oci oci-cli` since we don't get sudo in the cloudshell.
