### ISSUE TITLE
Add support for click version 8

### ISSUE THREAD

**Issue by fpiecka** [oracle/oci-cli#479]
oci-cli depends on an obsolete version of click python module.

Please upgrade click to a recent version and fix relevant issues mentioned in #440.

**Comment by vish1** [comment]
@fpiecka CLI depends on Click version 7.1.2 which was released last year and is the latest release in 7.x. Why do you think that version of click is obsolete?

We will look into upgrading the version of click to 8.x, but it might have breaking changes.

**Comment by meanjollies** [comment]
7.x is no longer stable nor the latest release. The [7.x release page](https://click.palletsprojects.com/en/7.x/) even mentions `Warning: This is an old version. The latest stable version is Version 8.0.x.`

**Comment by aurelg** [comment]
Looks like the following line:

https://github.com/oracle/oci-cli/blob/37230ac988874eeaff3f8ca4d7a3b9b69ab0d61f/src/oci_cli/cli_root.py#L348

Would have to be replaced either by

```python
    if str(profile) == str(Sentinel(DEFAULT_PROFILE)):  # convert both to string, to be compatible with click 7 and 8
```

or by:

```python
    if profile == str(Sentinel(DEFAULT_PROFILE)):  # convert string, to be compatible with click 8
```


Anyone with an [Oracle Contributor Agreement](https://github.com/oracle/oci-cli/blob/2c0932ebd36a155521231ecb2965c14268f018ac/CONTRIBUTING.rst) want to test and make a PR?

**Comment by meanjollies** [comment]
I do not have (nor wish to sign) an OCA, but I can confirm that the proposed Click 8-specific fix from @aurelg works.

**Comment by dhoogfr** [comment]
During the intallation of 3.22.3 I got the following message

_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oci-cli 3.22.3 requires click==7.1.2, but you have click 8.1.3 which is incompatible._

So it seems that the issue is not fixed?
