### ISSUE TITLE
It could be bug - OCI SDK with Python Kubernetes library

### ISSUE THREAD

**Issue by RahulMR42** [oracle/oci-cli#481]
Hi ,

While using kubernetes clients for python with oci sdk (python version) ,we could see its failing with below error 
```
"- root - ERROR - [Errno 2] No such file or directory: 'oci'"
````
This is happening right after create_kubeconfig method and at the step to load the same to kubernetes python client 

Ref # https://github.com/RahulMR42/oci-functions-with-oke/blob/main/oke.py#L36

**Comment by robo-cap** [comment]
To give some context to this situation:
if we create a ContainerEngineClient providing a custom config (either from a file or variable), this config is not reused when we create a kubeconfig file.

In kubeconfig file, generated oci command required to get a kubernetes token doesn't have as argument the custom config file provided when we created the client.  Instead is looking for it in ~/.oci/config and if none is found, it will go into an endless loop.

**Comment by RahulMR42** [comment]
thanks to @robo-cap  - we got a way forward here. https://github.com/RahulMR42/oci-functions-oke/blob/main/func.py#L35
