### ISSUE TITLE
Unable to install on MAC

### ISSUE THREAD

**Issue by kollachaitanyakrishna** [oracle/oci-cli#488]
homebrew installation stuck after downloading the tar file.
![Screenshot 2021-12-12 at 3 16 03 PM](https://user-images.githubusercontent.com/64516009/145707658-1ef5c61a-2319-44e3-b0ad-79625b8cc9c7.png)

**Comment by harshkumar-dev** [comment]
@kollachaitanyakrishna It could be a temporary issue. Could you open a fresh terminal and try again?


If it still fails, could you try installing any other tool using brew and check if that installs correctly?

**Comment by KartikShrikantHegde** [comment]
Hello @kollachaitanyakrishna ,

I will be closing this issue for now based on Harsh's response. If you are still hitting the problem, please feel free to reopen this.

Thanks.
