### ISSUE TITLE
OCI CLI installation downgraded 2 of my Python packages

### ISSUE THREAD

**Issue by pdxkzeerkti** [oracle/oci-cli#49]
I installed an unrelated Python program which upgraded `python-dateutils` to 2.6.1 and `crypto` to 2.1.4. Then installing the OCI CLI native on the same host downgraded these packages because the requirements.txt contains e.g. `python-dateutils==2.5.3` viz. `python-dateutils>=2.5.3`. I put in a pull request to prompt some discussion about this - https://github.com/oracle/oci-cli/pull/48/files.

**Comment by viralmodi** [comment]
Hi Jeff,
Thanks for reporting the issue. We use packages with specific versions to achieve stability and consistency with respect to reproducibility of releases. These packages with specific versions as mentioned in requirements.txt are known to work and are well tested before release. At this point, my suggestion is to use a virtual environment specific to OCI CLI to mitigate the issue you are facing. We might look into resolving this in a better way in future.
