### ISSUE TITLE
Compartment id is required to list compartments

### ISSUE THREAD

**Issue by fkrestan** [oracle/oci-cli#50]
**TLDR;** `oci iam compartment list` requires compartment id - this is very confusing.

**Env:**
```
$ oci -v
2.4.17
$ python --version
Python 2.7.14
```

**Description:**

Compartment id is required to list compartments:

```
$ oci iam compartment list
Usage: oci iam compartment list [OPTIONS]

Error: Missing option(s) --compartment-id.
```

While the option is documented to be actually *tenant OCID*, it is very confusing and inconsistent with the rest of the cli:
```
$ oci iam compartment --help
...
    --compartment-id, -c [text]
        The OCID of the tenancy containing the compartment. [required]
...

# Inconsistent with:
$ oci network vcn --help
...
    --compartment-id, -c [text]
        The OCID of the compartment to contain the VCN. [required]
...

$ oci compute instance --help
...
   --compartment-id, -c [text]
       The OCID of the instance's compartment. [required]
... 

$ oci os bucket --help
...
    --compartment-id, -c [text]
        The ID of the compartment in which to create the bucket. [required]
...
```

If I understand it correctly, compartments can be nested so it actually makes sense to have this option. Perhaps default value with tenancy OCID specified in config file could fix this.

**Expected result:**
List of compartments in tenancy is shown

**Comment by viralmodi** [comment]
The latest release of OCI CLI (2.4.20) has the fix for this open item.  It allows usage of oci iam compartment list without any arguments. It will take the default as tenancy (root compartment) ID
