### ISSUE TITLE
Create bucket with KMS key BadRequest error

### ISSUE THREAD

**Issue by DobbyH** [oracle/oci-cli#507]
I am attempting to create buckets with the oci-cli while specifying the use of a kms-key-id for encryption.

The command I am running is:
`oci os bucket create -c $compartment_id --name $target --kms-key-id $backups_encryption_key_ocid`

However the reply I get from the API is:
```
ServiceError:
{
    "code": "BadRequest",
    "message": "Caught RestClientException exception. Please visit https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm to learn more about this error code",
    "opc-request-id": "iad-1:XXXXXXX",
    "status": 400
}
```

I was previously getting a different error (404: NotAuthorizedOrFoundKmsKey) that was resolved by adding a key delegation and service usage policy.
The current error is far more vague.

Any help appreciated.

**Comment by adizohar** [comment]
I tried using user authentication and cloud shell and it worked well
you may not have permission to one of the objects, did you try with user authentication ? 
```
adiwrk::/home/opc> oci os bucket create -c ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7oxxxxxxx --name testkms --kms-key-id ocid1.key.oc1.iad.bbpqq6iuaacuu.abuwcljrydh5zgiwwtcrz7fzuurny3ijfhjka3vefnrqcwfd3xxxxxxxx
{
  "data": {
    "approximate-count": null,
    "approximate-size": null,
    "auto-tiering": null,
    "compartment-id": "ocid1.compartment.oc1..aaaaaaaa24b3mfwu6aulib33oan3eqicwm4az65cog7oxxxxxx",
    "created-by": "ocid1.user.oc1..aaaaaaaaq4kbbj2ag6rktjwixapm2vjd7gb5bydvvjsxt2ixxxxxxxxx",
    "etag": "fac19c0e-a55e-46fb-81b5-28e1e69cc186",
    "freeform-tags": {},
    "id": "ocid1.bucket.oc1.iad.aaaaaaaakifmg5tvyr57nlrszblzblcwyzpmdvuhts5n5fcevydv7xxxxxx",
    "is-read-only": false,
    "kms-key-id": "ocid1.key.oc1.iad.bbpqq6iuaacuu.abuwcljrydh5zgiwwtcrz7fzuurny3ijfhjka3vefnrqcwfd34dxa6xxxxxx",
    "metadata": {},
    "name": "testkms",
    "namespace": "orasenatdpltdevopxxxxxxx",
    "object-events-enabled": false,
    "object-lifecycle-policy-etag": null,
    "public-access-type": "NoPublicAccess",
    "replication-enabled": false,
    "storage-tier": "Standard",
    "time-created": "2022-02-28T18:37:56.774000+00:00",
    "versioning": "Disabled"
  },
  "etag": "fac19c0e-a55e-46fb-81b5-28e1e69cc186"
}
```

**Comment by DobbyH** [comment]
The user account I'm using has permissions to create buckets. The command without the --kms-key-id param works fine.
I'm unsure about what additional policies I should add to allow kms usage.

Currently I have "use key-delegate" (for the group that the users is in) and "use keys" for the services.

https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/commonpolicies.htm#os-bv-admins-use-key-id
https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/commonpolicies.htm#services-use-key

**Comment by DobbyH** [comment]
Was using RSA rather than AES encryption key. Creating the correct one in the vault and trying again worked.
