### ISSUE TITLE
OCI Authentication Error

### ISSUE THREAD

**Issue by DylanLee1** [oracle/oci-cli#514]
Using 'oci iam compartment list' gives me 

`
ServiceError:
{
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect.",
    "opc-request-id": "140B5D99586342369E220237042EFA8C/4108CEBB5940591EEFE18B31005AE356/5709F92BC2BFEEA4615DD66C3E9120C9",
    "status": 401
}
`

Config file tenancy and user id is correct with keys made.

**Comment by harshkumar-dev** [comment]
Hi Dylan, 
There are multiple reasons that can cause 401 error. Once you created private-public key, did you upload the public keys to console? Please check if fingerprint matches. 

Are you able to login to console and access compartments or objects? If not, you may need right policies. If you can, you can try "oci setup bootstrap" which will prompt you to a browser where you can login https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.6.2/oci_cli_docs/cmdref/setup/bootstrap.html


https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#ErrorDetailsandTroubleshooting

HTTP Status 401 Error Codes
NotAuthenticated

Description

The required authentication information was not provided or was incorrect.

Troubleshooting

https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm#ErrorDetailsandTroubleshooting

There are several things that can trigger this error code:

    Missing or incorrect authentication information.
        Verify that all of the required information (tenant OCID, user OCID, fingerprint, and private key) is provided and accurate
        Verify your private_key_path is pointing to your private key and not the corresponding public key
        Verify the public/private key pairs you are using are in the correct format
        Verify the user account is part of a group with the appropriate permissions to perform the actions in the plan you are executing
        Verify your tenancy has been subscribed to the region you are targeting in your plan
        Verify that the public key corresponding to the fingerprint has been uploaded for the user you are making the request as. For more information, see [Required Keys and OCIDs](https://docs.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#Required_Keys_and_OCIDs).
    Clock skew. This status code is returned if the client's clock is skewed more than five (5) minutes from the server's clock. For more information, see Maximum Allowed Client Clock Skew.
    API request signature error. This status code is returned if a required piece of information is missing or is malformed in the Authorization header. For more information, see [Request Signatures](https://docs.oracle.com/iaas/Content/API/Concepts/signingrequests.htm#Request_Signatures).

**Comment by DylanLee1** [comment]
I have fixed the problem, thank you.

**Comment by KishorePujari** [comment]
We are also facing the same error from node js code. @DylanLee1  How did you resolve it?

**Comment by prmjh4** [comment]
Hi, @DylanLee1 Can you share with worked for you so that we can also try that and get our issue resolved!
