### ISSUE TITLE
problems running install.sh on Linux 7

### ISSUE THREAD

**Issue by qtlin** [oracle/oci-cli#544]
Python3 wasn't initially present, accepted offer to install all necessary packages. Cryptography installation failed with 
```

      =============================DEBUG ASSISTANCE=============================
      If you are seeing a compilation error please try the following steps to
      successfully install cryptography:
      1) Upgrade to the latest pip and try again. This will fix errors for most
         users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
      2) Read https://cryptography.io/en/latest/installation.html for specific
         instructions for your platform.
      3) Check our frequently asked questions for more information:
         https://cryptography.io/en/latest/faq.html
      4) Ensure you have a recent Rust toolchain installed:
         https://cryptography.io/en/latest/installation.html#rust
      5) If you are experiencing issues with Rust for *this release only* you may
         set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
      =============================DEBUG ASSISTANCE=============================
  
  error: can't find Rust compiler
```
Set variable CRYPTOGRAPHY_DONT_BUILD_RUST as suggested and re-run, got tons of C compiler errors. Examined installed by the script https://github.com/oracle/oci-cli/blob/4af2e3db33fd332e6247c369cc5b7aa999d5f200/scripts/install/install.sh#L323 python related packages and found that i686 versions were installed. Erased them and reinstalled x86_64 explicitly. Then installation completed with no errors.
Questions:
1. should the script make sure it installs proper architecture?
2. should the script set CRYPTOGRAPHY_DONT_BUILD_RUST=1 if Rust is not found or install Rust instead?

**Comment by harshkumar-dev** [comment]
Please use yum for oracle linux 7

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm#InstallingCLI__oraclelinux7
