### ISSUE TITLE
Fails install on Linux 7 due to openssl version

### ISSUE THREAD

**Issue by gillfimj** [oracle/oci-cli#547]
Getting install error on a oci db system running Linux 7.9:
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib/oracle-cli/include -I/usr/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-x86_64-3.6/_openssl.c:575:30: fatal error: openssl/opensslv.h: No such file or directory
     #include <openssl/opensslv.h>
                                  ^
    compilation terminated.

        =============================DEBUG ASSISTANCE=============================
        If you are seeing a compilation error please try the following steps to
        successfully install cryptography:
        1) Upgrade to the latest pip and try again. This will fix errors for most
           users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        2) Read https://cryptography.io/en/latest/installation.html for specific
           instructions for your platform.
        3) Check our frequently asked questions for more information:
           https://cryptography.io/en/latest/faq.html
        =============================DEBUG ASSISTANCE=============================

    error: command 'gcc' failed with exit status 1

Current openssl version is:
rpm -aq|grep openssl
openssl-libs-1.0.2k-25.el7_9.x86_64
openssl-1.0.2k-25.el7_9.x86_64

Cryptography site says that it has desupported openssl v1.0.2 and the only option would be to upgrade the OS:
"The OpenSSL project has dropped support for the 0.9.8, 1.0.0, 1.0.1, and 1.0.2 release series. Since they are no longer receiving security patches from upstream, cryptography is also dropping support for them. To fix this issue you should upgrade to a newer version of OpenSSL (1.1.0 or later). This may require you to upgrade to a newer operating system."

Upgrading the OS cannot be the only option, especially if this is attempting to be installed on a db system.  Is there an alternative?

**Comment by harshkumar-dev** [comment]
This doesn't look like a OCI-CLI issue. Please provide exact install command you are using to install OCI-CLI if the error occurs while installing OCI-CLI.

Please reopen if its an OCI-CLI issue.
