### ISSUE TITLE
Not able to execute oci-cli command "oci iam db-token get" using Python inbuilt subprocess.run method 

### ISSUE THREAD

**Issue by Kajalagg98** [oracle/oci-cli#551]
Getting error "iam: oci: command not found" when trying to execute oci-cli command "oci iam db-token get" using Python inbuilt subprocess.run method .

**Comment by harshkumar-dev** [comment]
Try this:
    
import os

command = (
    "oci iam db-token get"
)
os.system(command)

**Comment by Kajalagg98** [comment]
I checked. Outside an ADE View, this command or even subprocess.run is working.
But such command does not work inside an ADE view. Any workaround??

**Comment by harshkumar-dev** [comment]
Do you still have this issue? What is an ADE?

**Comment by Kajalagg98** [comment]
The issue is resolved now. thanks!

**Comment by harshkumar-dev** [comment]
fixed
