### ISSUE TITLE
unknown Error: NamespaceNotFound

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-cli#554]
I see a new error code called `NamespaceNotFound` in SIN DC, which is not documented in https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm
```
{
    "code": "NamespaceNotFound",
    "message": "You do not have authorization to perform this request, or the requested resource could not be found.. Please visit https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm to learn more about this error code",
    "opc-request-id": "sin-1:OsIKuG1OdBl8YANUKCvt09C-ZyzWNhSLLMENI7BkVu5devc-FeQ_hX9OCNnudFF-",
    "status": 404
}
```

I expect a document improve, and anything I should do to resolve this error

**Comment by davidkhala** [comment]
Update: this is found as an authentication error, but the document should reveal this code.

**Comment by harshkumar-dev** [comment]
Hi David, 
Could you please confirm what command were you running when you received this error?

**Comment by davidkhala** [comment]
> Hi David, Could you please confirm what command were you running when you received this error?

most of command options suffer from this. A simple one is `oci os bucket list`

**Comment by harshkumar-dev** [comment]
This has been updated at https://docs.oracle.com/en-us/iaas/Content/API/References/apierrors.htm
