### ISSUE TITLE
db pluggable-database reports OPEN-MODE incorrectly (CLI version 3.10.4)

### ISSUE THREAD

**Issue by MikeSilman** [oracle/oci-cli#565]
When getting a pluggable database list the open-mode is reported incorrectly.

oci db pluggable-database list --database-id  <MYDBID>

+------------+----------+-
| open-mode  | pdb-name | 
+------------+----------+-
| READ_WRITE | DB1        | 
| READ_WRITE | DB2        |  
| READ_WRITE | DB3        | 
+------------+----------+-

In the above list DB3 is actually only MOUNTED.

**Comment by ShakthiGanesh** [comment]
Hi @MikeSilman MikeSilman
This sync is taken care as a part of PDB management V2 project and this issue will be resolved in PDB V2.

**Comment by MikeSilman** [comment]
Issue answered.
