### ISSUE TITLE
Infinite loop when running install.sh with option --accept-all-defaults

### ISSUE THREAD

**Issue by gavares** [oracle/oci-cli#57]
When running install.sh with option `--accept-all-defaults` on a system which as a previous installation of the oci cli in the default location, the installer enters an infinite loop in function `get_install_dir`. The issue appears to be on line 182 which reads:
```python
  ans_yes = prompt_y_n('Remove this directory', 'n')
```

and should probably read:
```python
  ans_yes = True if ACCEPT_ALL_DEFAULTS else prompt_y_n('Remove this directory', 'n')
```

without this change, the variable `install_dir` is reset to `None` and the encompassing while loop repeats.

**Comment by gavares** [comment]
I've submitted a PR for the issue at #58

**Comment by mross22** [comment]
Thanks for submitting the PR! I have merged it into our repo with a couple changes.  I am closing this issue as it is now fixed in the latest version of the install script.
