### ISSUE TITLE
error after installing in non default dirs

### ISSUE THREAD

**Issue by postak** [oracle/oci-cli#59]
After installing in non default dirs - On my mac I used _/usr/local/lib/oracle-cli_ and _/usr/local/bin_ - I got the following error when running **oci** command:

_Traceback (most recent call last):
  File "/usr/local/bin/oci", line 7, in <module>
    from oci_cli.cli import cli
ModuleNotFoundError: No module named 'oci_cli'_

solved installing oci_cli manually  

_pip3 install oci_cli_

**Comment by mross22** [comment]
Thanks for filing this issue, we are looking into it and will get back to you soon.

**Comment by mross22** [comment]
This appears to be the same issue mentioned here:
https://github.com/pypa/virtualenv/issues/845

I have submitted a fix here so the latest version of the install script should resolve this issue:
https://github.com/oracle/oci-cli/commit/5657b833bfcf16298d43fb6f0204cd66173c5ac0

Please re-open if you continue to encounter this issue and thanks for bringing it to our attention!
