### ISSUE TITLE
[feat] uninstall guide of oci cli

### ISSUE THREAD

**Issue by davidkhala** [oracle/oci-cli#592]
Since there are mulitple ways to install oci-cli. 

I want to have ways to uninstall respecitvely.

**Comment by mandyht** [comment]
You can find the uninstall commands for most installation approaches at the end of each section on our [Quickstart](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm) page.

**Comment by davidkhala** [comment]
Thanks @mandyht

**Comment by ipranjal** [comment]
there is no guide to uninstallation when setup done manually

**Comment by anup-21** [comment]
Refer to [Uninstalling the CLI](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliuninstall.htm) page which contain different way to uninstall oci-cli depending on how the oci-cli is installed in the first place.
