### ISSUE TITLE
oci-cli can't run togheter with awscli because of old click version requirement

### ISSUE THREAD

**Issue by herveschweitzer** [oracle/oci-cli#599]
OS : Debian 11.4

     echo "# ----------"
     echo "# 5. AWS CLI"
     echo "# ----------"
     pip3 install boto3 
     pip3 install boto 
     pip3 install ansible-lint 
     pip3 install requests 
     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
     unzip awscliv2.zip 
     ./aws/install 
     echo "# ------------------"
     echo "# 6. Oracle OCI-CLI"
     echo "# ------------------"
     pip3 install oci-cli 
...
Collecting click==7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
....
  Attempting uninstall: click
    Found existing installation: click 8.1.3
    Uninstalling click-8.1.3:
      Successfully uninstalled click-8.1.3
....
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
black 22.10.0 requires click>=8.0.0, but you have click 7.1.2 which is incompatible.
.....

**Comment by herveschweitzer** [comment]
if I change the order of OCI-CLI and AWS-CLI installation I get the below error

[91mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oci-cli 3.18.1 requires click==7.1.2, but you have click 8.1.3 which is incompatible.

**Comment by mandyht** [comment]
We're planning to upgrade click to 8.0.4. That should resolve the dependency conflict you're experiencing.

**Comment by herveschweitzer** [comment]
Hi Mandy,

Thanks for you help, let me know we you did the update, thus I can also update my package.  Finally the issue came from ansible-lint which require a newer version of click.

Best Regards
Hervé



Hervé Schweitzer | CTO & Principal Consultant

dbi services sa | Rue de la Jeunesse 2, CH-2800 Delémont

M ***@***.******@***.***> | T +41 32 422 96 00 | D +41 79 963 43 67 | W dbi-services.com<http://www.dbi-services.com/>

[cid:70c65742-f038-4571-8f9e-2d9e2314020a]<https://www.data-community.ch/>

________________________________

**Comment by mandyht** [comment]
Please install the latest version 3.19.0.
