### ISSUE TITLE
Bug: oci search query text command error with multiple conditions

### ISSUE THREAD

**Issue by luckeyca** [oracle/oci-cli#606]
On OCI console, this query works: QUERY vcn resources where lifeCycleState == 'AVAILABLE' && displayName == "test".

However, with OCI CLI, the command below returns service error:

oci search resource structured-search --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && displayName == "test""

ServiceError:
{
    "client_version": "Oracle-PythonSDK/2.81.0, Oracle-PythonCLI/3.16.0",
    "code": "CannotParseRequest",
    "logging_tips": "Please run the OCI CLI command using --debug flag to find more debug information.",
    "message": "Syntax error near: no viable alternative at input 'test'",
    "opc-request-id": "FB5F3BFCE8094DA9B3CDD7F9B097B838/80B711DAA34B8EA602E6DDC0D28EFD97/35FA50220DAE94E74760E022BA90BED4",
    "operation_name": "search_resources",
    "request_endpoint": "POST https://query.ca-toronto-1.oci.oraclecloud.com/20180409/resources",
    "status": 400,
    "target_service": "resource_search",
    "timestamp": "2022-11-03T14:45:31.625841+00:00",
    "troubleshooting_tips": "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_cannotparserequest for more information about resolving this error. If you are unable to resolve this issue, run this CLI command with --debug option and contact Oracle support and provide them the full error message."
}

Debug messages:

DEBUG:oci_cli.cli_metrics: 2022-11-03 14:45:55.406796: Metrics is not enabled
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
System name: Linux
System release : 5.10.102.1-microsoft-standard-WSL2
System version: #1 SMP Wed Mar 2 00:30:59 UTC 2022

env OCI_CLI_COMPARTMENT_OCID is set
env OCI_CLI_REGION is set
env OCI_CLI_USER is set
env OCI_CLI_PASSPHRASE is set
env OCI_CLI_FINGERPRINT is set
env OCI_CLI_KEY_FILE is set
env OCI_CLI_TENANCY is set
env OCI_PYTHON_SDK_NO_SERVICE_IMPORTS is set
DEBUG:oci_cli.cli_util:user: Environment Variable
DEBUG:oci_cli.cli_util:fingerprint: Environment Variable
DEBUG:oci_cli.cli_util:key_file: Environment Variable
DEBUG:oci_cli.cli_util:tenancy: Environment Variable
DEBUG:oci_cli.cli_util:pass_phrase: Environment Variable
DEBUG:oci_cli.cli_util:region: Environment Variable or Parameter
DEBUG:oci.base_client.139873133001264:Endpoint: https://query.ca-toronto-1.oci.oraclecloud.com/20180409
INFO:oci.base_client.139873133001264: 2022-11-03 14:45:55.452216: Request: POST https://query.ca-toronto-1.oci.oraclecloud.com/20180409/resources
Not using Expect header...
send: b'POST /20180409/resources HTTP/1.1\r\nuser-agent: Oracle-PythonSDK/2.81.0 (python 3.10.6; x86_64-Linux) Oracle-PythonCLI/3.16.0\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nconnection: keep-alive\r\ncontent-type: application/json\r\nopc-request-id: 57EE3DD457F54E748BC0EEF2379F7642\r\nopc-client-retries: true\r\nopc-client-info: Oracle-PythonSDK/2.81.0\r\nContent-Length: 113\r\ndate: Thu, 03 Nov 2022 14:45:55 GMT\r\nhost: query.ca-toronto-1.oci.oraclecloud.com\r\nx-content-sha256: vvRf8GT0SrA7+DZXG1lYmFS6JTIjwadSeQ5mj6pEaoY=\r\nauthorization: Signature algorithm="rsa-sha256",headers="date (request-target) host content-length content-type x-content-sha256",keyId="ocid1.tenancy.oc1..aaaaaaaawlq4uqsqhvqvtywcmwnzrgzon4iybbsm7isgzmcwqqxgmmvdystq/ocid1.user.oc1..aaaaaaaazsqqfxs3l5ppbmo5lbrt4wjrzkzbulyugpxyncxnycecs2t4rboa/73:5b:df:01:0e:3a:a6:6e:f4:f7:25:9c:58:1e:72:62",signature="T6taiZZo3MiShfgbzABDyzfc4WPYuOszq9pV/bR/G//2RPtJey75+flIklTU9d2b9qi5Wwt8QproNvQ5YLauELfdPikfeHxjWukZpGO4UGmkVi3BETmwgUoVktDDc2//Cn8ncIDlNDTozsfWPPsFf3uNCL7atpXJYvnwwowTPfMkzZVDRbBYt+tUwu96zn2AMJbiSURg0LUz+l72lLdvm4Ts63pBiDNeE9YHID804GfWkaM9HM5K+MzisEJ41vgS4S1GQ/CE5RrPy4IOCjiXg8BJ5uP5niYNSP4brK/UhGMP9sa5Nl5kMosFoWHyAs9H6TKM4ijM+evTSqqqQJiktg==",version="1"\r\n\r\n{"query": "QUERY vcn resources where lifeCycleState == \'AVAILABLE\' && displayName == test", "type": "Structured"}'
reply: 'HTTP/1.1 400 Bad Request\r\n'
header: Date: Thu, 03 Nov 2022 14:45:55 GMT
header: opc-request-id: 57EE3DD457F54E748BC0EEF2379F7642/C3822EF24A6313339E9FEDC7469BAC8F/4933F0278F28729F389B3F0858883C67
header: Content-Type: application/json
header: X-Content-Type-Options: nosniff
header: Content-Length: 109
DEBUG:oci.base_client.139873133001264: 2022-11-03 14:45:55.708862: time elapsed for request 57EE3DD457F54E748BC0EEF2379F7642: 0.2565783009995357
DEBUG:oci.base_client.139873133001264: 2022-11-03 14:45:55.709118: Response status: 400
DEBUG:oci.base_client.139873133001264: 2022-11-03 14:45:55.709351: python SDK time elapsed for deserializing: 1.6560000403842423e-05
Traceback (most recent call last):
  File "/usr/local/bin/oci", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci_cli/json_skeleton_utils.py", line 78, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci_cli/cli_util.py", line 852, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/services/resource_search/src/oci_cli_resource_search/resourcesearch_cli_extended.py", line 29, in search_resources_structured_search_details
    ctx.invoke(resourcesearch_cli.search_resources_structured_search_details, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci_cli/json_skeleton_utils.py", line 78, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci_cli/cli_util.py", line 852, in wrapped_call
    func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/services/resource_search/src/oci_cli_resource_search/generated/resourcesearch_cli.py", line 173, in search_resources_structured_search_details
    result = client.search_resources(
  File "/usr/local/lib/python3.10/dist-packages/oci/resource_search/resource_search_client.py", line 383, in search_resources
    return retry_strategy.make_retrying_call(
  File "/usr/local/lib/python3.10/dist-packages/oci/retry/retry.py", line 308, in make_retrying_call
    response = func_ref(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci/base_client.py", line 477, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/usr/local/lib/python3.10/dist-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/oci/base_client.py", line 617, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/usr/local/lib/python3.10/dist-packages/oci/base_client.py", line 774, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'target_service': 'resource_search', 'status': 400, 'code': 'CannotParseRequest', 'opc-request-id': '57EE3DD457F54E748BC0EEF2379F7642/C3822EF24A6313339E9FEDC7469BAC8F/4933F0278F28729F389B3F0858883C67', 'message': "Syntax error near: no viable alternative at input 'test'", 'operation_name': 'search_resources', 'timestamp': '2022-11-03T14:45:55.709251+00:00', 'client_version': 'Oracle-PythonSDK/2.81.0', 'request_endpoint': 'POST https://query.ca-toronto-1.oci.oraclecloud.com/20180409/resources', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_cannotparserequest for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/search/20180409/ResourceSummary/SearchResources for details on this operation's requirements. If you are unable to resolve this resource_search issue, please contact Oracle support and provide them this full error message."}

**Comment by luckeyca** [comment]
found the issue. 
looks like the value must in single quote in cli which is inconsistent with what the oci conole. On oci console, both single quote and double quote work which is the way should be.

**Comment by karthik-k-kamath** [comment]
Thanks Cheng Lu, for reporting this.
Please note OCI CLI does support both single and double quotes, when they clearly distinguish inner and outer values.
For Example these commands work:
`oci search resource structured-search --query-text 'QUERY vcn resources where lifeCycleState == "AVAILABLE" && displayName == "test"'`
and
`oci search resource structured-search --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && displayName == 'test'"`

In the command you tried, the double and single quotes are incorrectly used for both inner and outer values, which causes the error:
`oci search resource structured-search --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && displayName == "test""
`
