### ISSUE TITLE
Issue: oci cli structured-search doesn't print all the support api attributes

### ISSUE THREAD

**Issue by luckeyca** [oracle/oci-cli#607]
using vcn resource as an example, the vcn api support dnsLabel attribute. so the query can use the dnsLabel as condition and return the correct results. However, the dnsLabel attribute cannot be found in the output

oci search resource structured-search --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && dnsLabel == 'testvcndnslabel'"

**Comment by karthik-k-kamath** [comment]
Thanks Cheng Lu, for highlighting this.
We shall investigate and get back here.

**Comment by niskulka71** [comment]
Hi, the query being used is incorrect. 

Please try 

oci search resource structured-search --query-text "QUERY vcn resources where lifeCycleState == 'AVAILABLE' && dnsLabel == 'testvcndnslabel' return alladditionalfields"

**Comment by niskulka71** [comment]
Please reopen if this does not work.

**Comment by KartikShrikantHegde** [comment]
Hi @luckeyca , I am closing this issue for now. Please feel free to re-open if you run into issues again.

**Comment by luckeyca** [comment]
The response posted above on Aug 24, 2023 is incorrect. When running the command with the additional "return alladditionalfields", it returned "syntax error". without "return alladditionalfields", the command ran successfully, but still without the dns label returned in the result as reported.

**Comment by luckeyca** [comment]
correct syntax oci search resource structured-search --query-text "QUERY vcn resources return alladditionalfields where lifeCycleState == 'AVAILABLE' && dnsLabel == 'testvcndnslabel'" the "return alladditionalfields" must be before the where clause.
