### ISSUE TITLE
install.py fails when run as root

### ISSUE THREAD

**Issue by krilor** [oracle/oci-cli#620]
I've been running the latest install.py on ubuntu 18.04 and saw a bit of a weird behavior/failure.
Consider this output:

```
# python3 /tmp/install-oci-cli.py --accept-all-defaults --oci-cli-version 3.21.0 --exec-dir /usr/bin --install-dir /usr/lib/oracle-cli
-- Verifying Python version.
-- Python version 3.6.9 okay.
-- Creating directory '/usr/lib/oracle-cli'.
-- Creating directory '/root/bin/oci-cli-scripts'.
-- The scripts will be in '/root/bin/oci-cli-scripts'.
-- The optional packages installed will be ''.
-- Executing: ['', 'apt-get', 'update']
-- System was unable to use venv, is going to download and create virtualenv.
-- Downloading virtualenv package from https://github.com/pypa/get-virtualenv/blob/20.6.0/public/virtualenv.pyz?raw=true.
^C
```

The "weird part here is that it never actually tries to test using python3 -m venv. It fails before that, outputs an incorrect error message and downloads the virtualenv package (which is not possible on the node where I am working since I'm not able to reach github.com.

I've tried to isolate the issue and I believe that it is failing on executing: ['', 'apt-get', 'update']` here https://github.com/oracle/oci-cli/blob/ad80f194f04e27029bcabac027666e44d1045337/scripts/install/install.py#L145

The empty string at the beginning of the list is not handled very well by subprocess.check_call.

Observe:

```
root@jira-test:~# python3
Python 3.6.9 (default, Nov 25 2022, 14:10:45)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.check_call(["date", "-I"])
2022-12-15
0
>>> subprocess.check_call(["","date", "-I"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''
>>>
```
I patched the script with the following (basically just removing empty strings from the command_list

```
143a144
>     command_list = [i for i in command_list if i]
```

And now it works.

**Comment by krilor** [comment]
It looks like what I reported here resembles the behavior observed in #496.
Let me know if you would be interested in a PR for this.

Btw, the OCA link in https://github.com/oracle/oci-cli/blob/master/CONTRIBUTING.rst is dead

**Comment by pankajmjx** [comment]
Thanks @krilor for pointing this.We have made changes in code for this which will be out in next release.
