### ISSUE TITLE
cx_Oracle.DatabaseError: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by siddharthaweb** [oracle/oci-cli#625]
I am unable to connect Oracle server from my local, due to this error. Kindly help
**cx_Oracle.DatabaseError: ORA-12505: TNS:listener does not currently know of SID given in connect descriptor**

Here are the details of the associated modules and oporating system.

Oracle DB details
NLSRTL 						        12.2.0.1.0
Oracle Database 12c Standard Edition 	12.2.0.1.0
PL/SQL 						        12.2.0.1.0
TNS for Linux: 					        12.2.0.1.0

Python 3.10.5

instantclient_19_17
Microsoft Visual C++ 2015-2022 Redistributable - VC_redist.x64.exe
Name: cx-Oracle (Version: 8.3.0)
Oporating System : Windows 11

**Comment by adizohar** [comment]
This repository is for OCI CLI only,. you opened ticket related to cx_Oracle please close this ticket and open ticket in the correct repository - https://github.com/oracle/python-cx_Oracle/issues, 
just FYI your error is related to wrong tnsnames entry

**Comment by siddharthaweb** [comment]
As suggested issue post to another forum.
