### ISSUE TITLE
Cannot disable UpdatePathAndEnableTabCompletion in scripts/install/install.ps1

### ISSUE THREAD

**Issue by CowboyNick** [oracle/oci-cli#630]
When running install.ps1 in unattended mode, the AcceptAllDefaults parameter is required. However, the default value for the UpdatePathAndEnableTabCompletion prompt is "Y". So the path and tab completion is always enabled as there is no way to set UpdatePathAndEnableTabCompletion parameter to false.

**Comment by Kanvipasricha** [comment]
Thank you for raising your concern. We will investigate this and get back to you.

**Comment by pankajmjx** [comment]
Closing the ticket because of above reason.Feel free to open the ticket again if any further help is needed.

**Comment by CowboyNick** [comment]
Hi Pankajmjx, the issue is that we want to do a silent install "without" updating the path. If I leave off the AcceptAllDefault when calling the script it prompts for input so I can't use it with an automated/silent install.

**Comment by cesarjorgemartinez** [comment]
+1 Same for Linux installs

**Comment by cesarjorgemartinez** [comment]
this issue should be reopened

**Comment by cesarjorgemartinez** [comment]
Also missing a parameter --quiet to do silent installation
