### ISSUE TITLE
v3.23.0 version.py still has 3.22.5

### ISSUE THREAD

**Issue by amsteinb-orcl** [oracle/oci-cli#640]
https://github.com/oracle/oci-cli/blob/v3.23.0/src/oci_cli/version.py

__version__ = '3.22.5'

**Comment by amsteinb-orcl** [comment]
In looking further, I see that the commit hash for 3.23.0 on https://github.com/oracle/oci-cli/releases is the same as 3.22.5.  I also see a 3.23.0.1 tag which may be correct, but not reflected in the releases page.

**Comment by amsteinb-orcl** [comment]
I see this was fixed now.

**Comment by karthik-k-kamath** [comment]
Thanks Alan for highlighting this
