### ISSUE TITLE
oci-cli need to use crytography version 39.0.1 or above

### ISSUE THREAD

**Issue by jgau** [oracle/oci-cli#645]
We are hitting security issue that crytography version needs to be 39.0.1, oci-cli uses cryptography-38.0.4. 
how to get install oci-cli on oracle linux7 that can pass the security

**Comment by jgau** [comment]
this is the problem
 oci-cli 3.23.2 has requirement cryptography<39.0.0,>=3.2.1
 
 During oci-cli installation, it will remove 39.0.01 and install 38.0.4

**Comment by mrd000** [comment]
```
oci-2.93.1:Requires-Dist: cryptography (<39.0.0,>=3.2.1)
oci_cli-3.23.2:Requires-Dist: cryptography (<39.0.0,>=3.2.1)
pyOpenSSL-22.1.0:Requires-Dist: cryptography (<39,>=38.0.0)
```
