### ISSUE TITLE
oci kms management key not create a new master encryption key

### ISSUE THREAD

**Issue by romuloslv** [oracle/oci-cli#646]
I'm having trouble trying to create a master encryption key. Errors are below.

oci kms management key create --compartment-id xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --display-name master_key --endpoint https://kms.sa-saopaulo-1.oraclecloud.com --protection-mode HSM --key-shape '{"algorithm": "AES", "length": 32}' --debug

```
Error: 404-NotAuthorizedOrNotFound, Authorization failed or requested resource not found.
Suggestion: Either the resource has been deleted or service Kms Key need policy to access this resource. Policy reference: https://docs.oracle.com/en-us/iaas/Content/Identity/Reference/policyreference.htm
Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/kms_key 
API Reference:  
Request Target: POST https://kms.sa-saopaulo-1.oraclecloud.com/20180608/keys 
Provider version: 4.110.0, released on 2023-03-01.  
Service: Kms Key 
Operation Name: CreateKey 
OPC request ID: aa2fbbede1c031959164df0acf569a6b/D0203BA1F8F629895AE4A402CCE3100E/44EEA6B0F129A7E8B359998378EB338C 


  with oci_kms_key.master_key,
  on vaults.tf line 7, in resource "oci_kms_key" "master_key":
   7: resource "oci_kms_key" "master_key" {
```

[log full here](https://gist.github.com/romuloslv/c12162036ec52c0ac51602598efa487a)

### Versions

Terraform v1.3.6 on darwin_arm64
oracle/oci v4.110.0

### Reproduce

Create a user: test
Create a group: test
Create a permission policy to group created: Allow group test to manage all-resources in compartment test
Add a user created to group created
Enable api key on created user
Update your config file: ~/.oci/config
oci kms management key create...

Can you help?

**Comment by bassg0navy** [comment]
@romuloslv did you find a solution to this? I'm experiencing the same. I tried creating a policy that allows KMS service to manage vault in my tenancy. Any help would be greatly appreciated.

**Comment by adizohar** [comment]
It works well, you need to make sure you specify the management end point of the vault, below is working:
```
oci kms management key create --compartment-id ocid1.xxxxxxx --display-name adi_new_key --endpoint https://abababababab-management.kms.us-ashburn-1.oraclecloud.com --protection-mode HSM --key-shape '{"algorithm": "AES", "length": 32}'
```

**Comment by bassg0navy** [comment]
My resources are also in Ashburn. I'm specifying `https://kms.us-ashburn-1.oraclecloud.com` as management_endpoint that I got from [the documentation](https://docs.oracle.com/en-us/iaas/api/#/en/key/release/). Is specified endpoint what you actually use, or an example?

**Comment by adizohar** [comment]
You need to go to the Vault and check the end point at the vault, each vault has it own end point.

**Comment by adizohar** [comment]
This is an example of real end point, just replaced the abababababab strings with yours
https://abababababab-management.kms.us-ashburn-1.oraclecloud.com

**Comment by bassg0navy** [comment]
Ah, I see; works beautifully now. Thank you for your quick and detailed response.

**Comment by adizohar** [comment]
This is great, please close the ticket if no more issues
