### ISSUE TITLE
Cython does not appear to be installed

### ISSUE THREAD

**Issue by merqurious77** [oracle/oci-cli#658]
On OEL7 with Pyth 3.10 or Python 3.11.2
running bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" and getting error

Collecting PyYAML<6,>=5.4
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 45.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      /tmp/pip-build-env-jsxeaubt/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      failed to import Cython: /tmp/pip-build-env-jsxeaubt/overlay/lib/python3.10/site-packages/Cython/Compiler/Scanning.cpython-310-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted
      error: Cython does not appear to be installed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_52T6", line 722, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_52T6", line 677, in main
    install_cli(install_dir, tmp_dir, cli_version, OPTIONAL_FEATURES)
  File "/tmp/oci_cli_install_tmp_52T6", line 319, in install_cli
    exec_command(cmd, env=env)
  File "/tmp/oci_cli_install_tmp_52T6", line 141, in exec_command
    subprocess.check_call(command_list, cwd=cwd, env=env)
  File "/osb/osbprod1/utils/Python/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/osb/osbprod1/utils/oci-cli-install/bin/pip', 'install', '--cache-dir', '/tmp/tmpisvx0ncn', 'oci_cli', '--upgrade']' returned non-zero exit status 1.

**Comment by Djelibeybi** [comment]
The OCI CLI is packaged for Oracle Linux. Please follow the Quick Start guide to install: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm
