### ISSUE TITLE
How to avoid having to remember compartment ID??

### ISSUE THREAD

**Issue by raffraffraff** [oracle/oci-cli#674]
Issue: when run a command like: `oci compute instance list`, I get this error:
```
Error: Missing option(s) --compartment-id.
```

I found a really old [issue from 2018](https://github.com/oracle/oci-cli/issues/47) that indicates that it should be possible. According to the docs for [Configuring the CLI/Specifying Default Values](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#Specifying_Default_Values), I should be able to add my compartment ID to the OCI configuration file to avoid being asked for it every time. But this doesn't work for me. My anonymized `~/.oci/config`:
```
[DEFAULT]
user = ocid1.user.oc1..blahblahblah
fingerprint = bl:ah:bl:ah:bl:ah:bl:ah:bl:ah:bl:ah:bl:ah:bl:ah
key_file = /home/blah/.oci/oci_api_key.pem
tenancy = ocid1.tenancy.oc1..blahblahblah
compartment-id = ocid1.tenancy.oc1..blahblahblah
region = eu-amsterdam-1
```

There doesn't seem to be a [CLI Environment Variable](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/clienvironmentvariables.htm) for compartment ID. I also tried adding this to the `~/.oci/config` (but didn't expect it to work anyway):
```
[OCI_CLI_SETTINGS]
default_profile=DEFAULT
```

I even went as far as reading all of the online docs and found an example of how to get the `oci` to automatically add the compartment-id value to an [aliased command](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#Specifying_Command_Aliases) where 'ls' alias is used for 'list'...
```
compute.instance.list.compartment-id=ocid1.tenancy.oc1..blahblahblah
```
...but that didn't work either!

Debug output from `oci os ns get --debug` shows that it's picking up the `compartment-id` from the config file:

```
DEBUG:oci_cli.cli_metrics: 2023-05-07 10:09:16.007636: Metrics is not enabled
Linux-6.2.6-1-default-x86_64-with-glibc2.37
System name: Linux
System release : 6.2.6-1-default
System version: #1 SMP PREEMPT_DYNAMIC Mon Mar 13 10:57:27 UTC 2023 (fa1a4c6)

DEBUG:oci_cli.cli_util:Config File: dict_keys(['log_requests', 'additional_user_agent', 'pass_phrase', 'user', 'fingerprint', 'key_file', 'tenancy', 'compartment-id', 'region'])
DEBUG:oci_cli.cli_util:region: Environment Variable or Parameter
```

**Comment by raffraffraff** [comment]
Because the `oci` requires positional args first I can't simply add a bash alias like `alias oci='oci --compartment-id ${BLAH}'`, and even if there wasn't a requirement for a positional arg first adding `--compartment-id` breaks _some_ commands. Right now my only workaround is to export it as a shell var and add `--compartment-id ${OCI_COMPARTMENT_ID}` whenever I get the error. But this should just work.

**Comment by raffraffraff** [comment]
Oh WOW, this is stupid... So `oci` completely ignores the compartment-id in your `~/.oci/config` when you run a command that requires `--compartment-id`. But if you add it to `~/.oci/oci_cli_rc` then this works. So I can literally `cp ~/.oci/config ~/.oci/oci_cli_rc` to fix this.

This is daft. It should use the compartment ID from the `~/.oci/config`. But feel free to close this if you disagree. People will at least be able to find this with a google/github search.

**Comment by spareslant** [comment]
> Oh WOW, this is stupid... So `oci` completely ignores the compartment-id in your `~/.oci/config` when you run a command that requires `--compartment-id`. But if you add it to `~/.oci/oci_cli_rc` then this works. So I can literally `cp ~/.oci/config ~/.oci/oci_cli_rc` to fix this.
> 
> This is daft. It should use the compartment ID from the `~/.oci/config`. But feel free to close this if you disagree. People will at least be able to find this with a google/github search.
> 
> The doc for [Specifying Default Values](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#Specifying_Default_Values) should explain this a lot better - like specifically calling out that you can't just use `~/.oci/config` to do this, because it is ignoring the value in that file.

+1 for this issue.

**Comment by karthik-k-kamath** [comment]
Hi @raffraffraff , @spareslant , I think you may have misunderstood `~/.oci/config` as the CLI config file.
The CLI config file is **`~/.oci/oci_cli_rc`** and not  `~/.oci/config`

This is clearly mention here: [CLI Configuration File](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#CLIconfigfile)
>CLI Configuration File
>The default location and file name for the CLI-specific configuration file is ~/.oci/oci_cli_rc ...

This should explain why your command started working only after you added the default value in ~/.oci/oci_cli_rc
Hope this helps, and let me know if I can help answer any other query.

**Comment by spareslant** [comment]
> Hi @raffraffraff , @spareslant , I think you may have misunderstood `~/.oci/config` as the CLI config file. The CLI config file is **`~/.oci/oci_cli_rc`** and not `~/.oci/config`
> 
> This is clearly mention here: [CLI Configuration File](https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliconfigure.htm#CLIconfigfile)
> 
> > CLI Configuration File
> > The default location and file name for the CLI-specific configuration file is ~/.oci/oci_cli_rc ...
> 
> This should explain why your command started working only after you added the default value in ~/.oci/oci_cli_rc Hope this helps, and let me know if I can help answer any other query.

Hi @karthik-k-kamath , if **`~/.oci/oci_cli_rc`**  is called as a CLI config file, what to call **`~/.oci/config`** file then? 

Leaving the naming convention aside,  the point is  It has been understood, how these works. Its the design and ergonomics of using these files that people are complaining/questioning about.  One set of params for a profile/section can be defined only in one file and and other set of params are for another file for same profile/section. This is not flexible. Natural way of thinking is to be able to use all params under a profile.  Is there a document that specify what params are effective  in `~/.oci/config` file and not in `~/.oci/oci_cli_rc`  and also vice-versa ?

**Comment by karthik-k-kamath** [comment]
Hi @spareslant , thanks for the questions, I understand your confusion.
Let  me help clarify.
The `~/.oci/config` file the common configuration file for all OCI tools: CLI, SDKs etc
This doc explains it better: [SDK and CLI Configuration File](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm)

The `~/.oci/oci_cli_rc` is an additional config file meant only for OCI CLI to use, it way CLI provides it's users lot more configuration features that `~/.oci/config` does not like: command aliases, names queries etc which are relevant only in CLI scope.
My suggestion is to only edit `~/.oci/oci_cli_rc` file and keep `~/.oci/config` untouched when using OCI CLI.
Is there any param/usage that you find **not** possible in `~/.oci/oci_cli_rc` file, for which you had to edit `~/.oci/config` ?

**Comment by spareslant** [comment]
Hi @karthik-k-kamath , Thanks for the explanation. I think confusion is, why there is an additional config file for cli. Both SDK and cli could have used a single unified config file giving a simple seem less config experience to the users. I am sure CLI might be using SDK behind the scenes. Feel free to close this issue.

**Comment by karthik-k-kamath** [comment]
Welcome @spareslant 
I think a single unified config file would have required all tools (and tools build on top of them) to be aware of each others config params and would have also brought in conflict if any params ended up being common, unintentionally.

So I am closing this issue for now, and I can still answer any future questions here.
