### ISSUE TITLE
offline install on ExaCC fails "pip requires Python '>=3.7' but the running Python is 3.6.8"

### ISSUE THREAD

**Issue by kranskydog** [oracle/oci-cli#690]
[opc@exadbsyd21 oci-cli]$ ll
total 69536
-rw-rw-r-- 1 opc opc 68265792 Jul  3 11:14 oci-cli-3.29.2-Oracle-Linux-7.9-Offline.zip
drwxrwxr-x 3 opc opc    20480 Jun 29 19:39 oci-cli-installation
[opc@exadbsyd21 oci-cli]$ cat /etc/oracle-release
Oracle Linux Server release 7.9

[opc@exadbsyd21 oci-cli-installation]$ bash install.sh --offline-install

    ******************************************************************************
    You have started the OCI CLI Installer in interactive mode. If you do not wish
    to run this in interactive mode, please include the --accept-all-defaults option.
    If you have the script locally and would like to know more about
    input options for this script, then you can run:
    ./install.sh -h
    If you would like to know more about input options for this script, refer to:
    https://github.com/oracle/oci-cli/blob/master/scripts/install/README.rst
    ******************************************************************************
Starting OCI CLI Offline Installation
Running install script.
python3 ./install.py  --offline-install
-- Verifying Python version.
-- Python version 3.6.8 okay.

===> In what directory would you like to place the install? (leave blank to use '/home/opc/lib/oracle-cli'):
-- Creating directory '/home/opc/lib/oracle-cli'.
-- We will install at '/home/opc/lib/oracle-cli'.

===> In what directory would you like to place the 'oci' executable? (leave blank to use '/home/opc/bin'):
-- Creating directory '/home/opc/bin'.
-- The executable will be in '/home/opc/bin'.

===> In what directory would you like to place the OCI scripts? (leave blank to use '/home/opc/bin/oci-cli-scripts'):
-- Creating directory '/home/opc/bin/oci-cli-scripts'.
-- The scripts will be in '/home/opc/bin/oci-cli-scripts'.
-- Trying to use python3 venv.
-- Executing: ['/usr/bin/python3', '-m', 'venv', '/home/opc/lib/oracle-cli']
-- Executing: ['/home/opc/lib/oracle-cli/bin/pip', 'install', 'pip', '--upgrade', '--find-links', 'cli-deps', '--no-index']
Collecting pip
pip requires Python '>=3.7' but the running Python is 3.6.8
-- System was unable to use venv, Please make sure Python3 venv is installed.

**Comment by karthik-k-kamath** [comment]
Hi Phil, can you try with Python v3.7+ ?

**Comment by kranskydog** [comment]
This is Exadata Cloud @ Customer, and I don't really want to be mucking around installing new versions of Python. This is the version of Python that comes with the OS image

**Comment by kranskydog** [comment]
And oci-cli is a prereq for using Oracle Dynamic Scaling - Remote Plug-in (Doc ID 2770544.1)

**Comment by kranskydog** [comment]
3.6.8 is also the latest version at https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/index.html, So I am not sure where I am supposed to get 3.7+

**Comment by karthik-k-kamath** [comment]
See: [Installing Python 3 from Oracle Linux Latest Repo](https://yum.oracle.com/oracle-linux-python.html#InstallPython3FromLatest)

**Comment by kranskydog** [comment]
I cannot use yum to install against an Exadata Cloud@Customer OS image.

**Comment by pankajmjx** [comment]
This issue is fixed now.Please download latest version of oci cli for fix.
