### ISSUE TITLE
interactive mode

### ISSUE THREAD

**Issue by stacksc** [oracle/oci-cli#702]
can we include a while loop on interactive mode, so we can optionally stay inside the shell interface and not exit until we CTRL D.
The current release just executes the command and it will exit the shell. Some users prefer to stay inside the shell interface.

**Comment by stacksc** [comment]
```
def start_interactive_shell(ctx):
    while True:
```

**Comment by karthik-k-kamath** [comment]
Hi Chris, closing the interactive shell after execution of each CLI command has been a design decision.
If there are many customers ask for it, then we shall sure consider it as future enhancement.

For now, I can suggest a workaround to simulate this and see how you like it.  
In a bash script or function:
===
function ocii {
  while [ 1 ]
  do
    oci -i
  done
}
===
Then run ocii to start the interactive cli shell like environment.  
Press Ctrl-C twice to exit.

**Comment by stacksc** [comment]
thx @karthik-k-kamath for getting back. That should be ok for a temporary work-around. thanks!

**Comment by bdowling** [comment]
I know this issue has been closed, but this seems like a silly feature not to include given the simplicity of implementation.

Could be `oci -I` (upper case I) that enables this mode for example.
