### ISSUE TITLE
Issues installing oci-cli on oracle linux 7 and 8. The error message is captured below.

### ISSUE THREAD

**Issue by marygaewu** [oracle/oci-cli#703]
[opc@ociuibps-wls-0 ~]$ sudo yum install python36-oci-cli
Loaded plugins: langpacks, ulninfo
ol7_MySQL80                                                                                                      | 3.0 kB  00:00:00
ol7_MySQL80_connectors_community                                                                                 | 2.9 kB  00:00:00
ol7_MySQL80_tools_community                                                                                      | 2.9 kB  00:00:00
ol7_UEKR6                                                                                                        | 3.0 kB  00:00:00
ol7_addons                                                                                                       | 3.0 kB  00:00:00
ol7_ksplice                                                                                                      | 3.0 kB  00:00:00
ol7_latest                                                                                                       | 3.6 kB  00:00:00
ol7_oci_included                                                                                                 | 2.9 kB  00:00:00
ol7_optional_latest                                                                                              | 3.0 kB  00:00:00
ol7_software_collections                                                                                         | 3.0 kB  00:00:00
(1/2): ol7_oci_included/x86_64/primary_db                                                                        | 1.6 MB  00:00:00
(2/2): ol7_ksplice/primary_db                                                                                    | 4.3 MB  00:00:00
Package python36-oci-cli-3.23.2-1.el7.noarch already installed and latest version
Nothing to do
[opc@ociuibps-wls-0 ~]$ oci -version
Traceback (most recent call last):
  File "/usr/bin/oci", line 7, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'click==7.1.2' distribution was not found and is required by oci-cli
[opc@ociuibps-wls-0 ~]$

**Comment by Djelibeybi** [comment]
Can you try running `yum reinstall python36-oci-sdk` as `click` is included in that package?
