### ISSUE TITLE
Issue in installing on OEL  6.10

### ISSUE THREAD

**Issue by mrashed82** [oracle/oci-cli#706]
Issue in installing on OEL  6.10.
Already Python 3.9.1 installed - but the installation script doesn't recognize it.

# bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)"
python3 not found on system PATH
System version of Python must be a Python 3 version >= 3.6.0.
OCI CLI will only run on Python 3.6 or higher. Would you like to upgrade to Python 3? Please enter Y or N. Y
Installing Python 3...
No package python3-devel available.
Python is not working correctly. Please read common errors in the following link. https://github.com/oracle/oci-cli/blob/master/COMMON_ISSUES.rst

while

# python --version
Python 3.9.1
# python3 --version
Python 3.9.1
# which python
alias python='/usr/local/bin/python3.9'
	/usr/local/bin/python3.9
# which python3
alias python3='/usr/local/bin/python3.9'
	/usr/local/bin/python3.9
# echo $PATH
/usr/local/bin/python3.9:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

--
Also i can't install python3-devel  using Yum.

Thanks.

**Comment by adizohar** [comment]
Did you try to install oci-cli using pip3 ? 

pip3 install oci-cli

**Comment by Djelibeybi** [comment]
There isn't a new enough version of Python for Oracle Linux 6 to support OCI CLI. It only runs on Oracle Linux 7 or higher.
