### ISSUE TITLE
No such file or directory: '/root/lib/oracle-cli/bin/pip' from installing oci-cli

### ISSUE THREAD

**Issue by zhouyuf6741** [oracle/oci-cli#710]
I am getting #18 2.037 FileNotFoundError: [Errno 2] No such file or directory: '/root/lib/oracle-cli/bin/pip'

when install oci in the dockercontainer with 
RUN curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults

**Comment by Djelibeybi** [comment]
We provide a pre-built container image for OCI CLI: https://github.com/oracle/docker-images/pkgs/container/oci-cli

Note that we don't use the installation script inside a container image. Rather, we use `pip` directly. You can review the official Dockerfile here: https://github.com/oracle/docker-images/blob/main/OracleCloudInfrastructure/oci-cli/Dockerfile
