### ISSUE TITLE
"oci ce cluster create --generate-param-json-input options" does not work

### ISSUE THREAD

**Issue by eshneken** [oracle/oci-cli#72]
The man pages indicate that this option is supported:

The --generate-param-json-input option can be used to generate an exam-
       ple of the JSON which must be provided. We recommend storing this exam-
       ple in a file, modifying it as needed and then passing it back  in  via
       the file:// syntax.

When attempting to run the command the output is:

oci ce cluster create --generate-param-json-input options
Option options is not a recognized complex type, so no example JSON can be produced. Invoke help for this command (--help/-h/-?) to see available documentation on this option

**Comment by vish1** [comment]
The option (--generate-param-json-input) is supported for complex type parameters. For the specific command: `oci ce cluster create`, there is only one complex parameter available - service-lb-subnet-ids. Below is an example run for that parameter: 

```
> oci ce cluster create --generate-param-json-input service-lb-subnet-ids
[
  "string",
  "string"
]
```

**Comment by vish1** [comment]
All oci commands have an option `--generate-full-command-json-input` (seen by running `oci -h`). This provides a template of the json input that can be filled up and provided as the input to the --from-json paramater.

```
--generate-full-command-json-input
                                  Prints out a JSON document which represents
                                  all possible options that can be provided to
                                  this command.

                                  This JSON document can be
                                  saved to a file, modified with the
                                  appropriate option values, and then passed
                                  back via the --from-json option. This
                                  provides an alternative to typing options
                                  out on the command line.
```

Example run for the `oci ce cluster create command`:
```
> oci ce cluster create --generate-full-command-json-input
{
  "compartmentId": "string",
  "dashboardEnabled": true,
  "kubernetesVersion": "string",
  "maxWaitSeconds": 0,
  "name": "string",
  "podsCidr": "string",
  "serviceLbSubnetIds": [
    "string",
    "string"
  ],
  "servicesCidr": "string",
  "tillerEnabled": true,
  "vcnId": "string",
  "waitForState": "ACCEPTED|IN_PROGRESS|FAILED|SUCCEEDED|CANCELING|CANCELED",
  "waitIntervalSeconds": 0
}
```

**Comment by eshneken** [comment]
Got it.  Thank you!
