### ISSUE TITLE
oci cli network-firewall bulk-upload doesn't read input from json file

### ISSUE THREAD

**Issue by xkoomy** [oracle/oci-cli#727]
Hello,
following command doesn't work:
oci network-firewall application bulk-upload --network-firewall-policy-id $network_firewall_policy_id --bulk-upload-applications-details file://application.json

The --bulk-upload-applications-details file://application.json does not read input from the specified json file. 
It doesnt work for all other components like application-group; service; service-list; url-list; address-list; mapped-secret; decryption-profile; decryption-rule; security-rule;
Example debug log: 
[example_execution_debug.txt](https://github.com/oracle/oci-cli/files/13289478/example_execution_debug.txt)

$ oci --version
3.35.0

Issue can be reproduced at will.

Reference:
https://docs.oracle.com/en-us/iaas/Content/network-firewall/bulk-import.htm

**Comment by xkoomy** [comment]
Most likely it works as designed. The --bulk-upload-applications-details is a string, not a Complex Input. JSON File can be used for Complex Input only. Not sure why examples in https://docs.oracle.com/en-us/iaas/Content/network-firewall/bulk-import.htm suggesting use the [file://](file://m/)<file.json> …. this makes a confusion.

**Comment by karthik-k-kamath** [comment]
Thanks @xkoomy for sharing the correct approach. Can you close this issue?
