### ISSUE TITLE
--query returns "Query returned empty result, no output to show." if result is 0

### ISSUE THREAD

**Issue by alfredkrohmer** [oracle/oci-cli#730]
```bash
$ oci ce node-pool get --node-pool-id ocid1.nodepool.oc1.eu-frankfurt-1.aaaaaaaa.... --query 'data."node-config-details".size'
Query returned empty result, no output to show.
```
This should just return `0` instead.

**Comment by karthik-k-kamath** [comment]
The CLI returns empty result when output has a no data, for all datatype: string, int
Closing as this is not an issue.
Feel free to share your view.

**Comment by alfredkrohmer** [comment]
0 is not "no data", it's "just" a number. I don't know why you would treat this as "no data". If I run the example command I provided for a node pool that has at least one instance, I will get back the number of instances. It makes zero sense that I get the message "Query returned empty result, no output to show." instead of 0.
