### ISSUE TITLE
Authorization failed or requested resource not found.

### ISSUE THREAD

**Issue by ghostreaper2341** [oracle/oci-cli#731]
Yesterday my instance was working, but today it is saying this can I get help.

**Comment by karthik-k-kamath** [comment]
Can you please share the CLI command executed and the whole error response returned?

**Comment by ghostreaper2341** [comment]
I didn't put any command, my instance just got erased, and I enter to my oracle cloud account, and it says "Authorization failed or requested resource not found." and i can't do nothing in the account.
