### ISSUE TITLE
Install script does not work on Linux with Python 3.12

### ISSUE THREAD

**Issue by thozza** [oracle/oci-cli#742]
Python 3.12 removed `distutils`  (https://docs.python.org/3/whatsnew/3.12.html).

Therefore, running the install script (https://github.com/oracle/oci-cli?tab=readme-ov-file#linux) on a Linux distribution with Python 3.12 (e.g. Fedora 39) results in failure to install the tool and ends up with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
Traceback (most recent call last):
  File "/tmp/oci_cli_install_tmp_oci0", line 722, in <module>
    main()
  File "/tmp/oci_cli_install_tmp_oci0", line 705, in main
    venv_site_packages_directory = subprocess.check_output([venv_python_executable, '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']).strip()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/root/lib/oracle-cli/bin/python', '-c', 'from distutils.sysconfig import get_python_lib; print(get_python_lib())']' returned non-zero exit status 1.
```

Steps to reproduce:

1. run `podman run -ti --rm registry.fedoraproject.org/fedora:latest bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults`

**Comment by karthik-k-kamath** [comment]
Hi Tomas
The OCLI-CLI is not **yet** officially supported on Python v3.12
You can can find here the list of OS and Python version supported til now for OCI CLI:
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm#Requirements
