### ISSUE TITLE
Cloud shell is not listing the compartments in Private Network Definition

### ISSUE THREAD

**Issue by muneeroracle** [oracle/oci-cli#768]
Hi,

My customer provisioned ADB in a Private endpoint. To access it, he is trying to create a Private Network Definition. However he is not able to list the compartments where the VCN is created.  The user user has all the privileges to view the VCNs. From Console UI he can access the VCNs and subnets.

Thanks
Muneer

**Comment by adizohar** [comment]
Can you please elaborate what the customer is trying to do, what commands is he running ?
to list vcns in specific compartment, he can use "oci network vcn list -c $compartment_id"
When you mentioned "he is trying to create a Private Network Definition" is it in cloud shell ?
Is the issue related to oci cli ?

**Comment by muneeroracle** [comment]
Customer is trying to connect to ADB from cloud shell. I will attach the screenshots what he is doing. step3.jpg it is not listing the compartments when clicked on "change compartment"

![step3](https://github.com/oracle/oci-cli/assets/167727670/a6fb6671-7955-4b0b-93ee-761b422bd5e1)

**Comment by adizohar** [comment]
The compartments list should appear, if not you are probably behind FW or Proxy that prevents it
It is not OCI-CLI issue, please close this issue and open Support Request at the support.oracle.com

**Comment by muneeroracle** [comment]
Hi,

I am from GCS.  Which team can help to assist on this.


Thanks
Muneer

From: Adi Zohar ***@***.***>
Sent: 22 April 2024 17:23
To: oracle/oci-cli ***@***.***>
Cc: Muneer Hassan ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle/oci-cli] Cloud shell is not listing the compartments in Private Network Definition (Issue #768)


The compartments list should appear, if not you are probably behind FW or Proxy that prevents it
It is not OCI-CLI issue, please close this issue and open Support Request at the support.oracle.com
