### ISSUE TITLE
FILE command when using CLI container fails

### ISSUE THREAD

**Issue by Ernst2020** [oracle/oci-cli#775]
L.S.

I run the CLI Docker container in Windows, works fine.

However, any command that is specified with the “file://“ parameter fails with an error that the specified file cannot be found.

If I open a shell in that container the file to be used (mapped from the Windows directory to the container) is there, can be opened and has access permissions for all users (777). I can open it, write to it etc.

In that same directory in Windows (and thus in the container) the config file and ssh key are there and those are correctly accessed by the CLI, thus the CLI container has correct access to that directory.

But for some reason file:// fails. I tried all sorts of combinations such as:

file:”//…”
file:”\\…”
file:…

Also changing the owner of the file from root to oci did not solve this.

Any clues?

Ernst

**Comment by Ernst2020** [comment]
In the meantime I found out that “file:///…” works, i.e. three forwards slashes. Weird.

**Comment by karthik-k-kamath** [comment]
Thanks Ernst for sharing.
Closing as parameter works with format “file:///…”
