### ISSUE TITLE
Get "RequestException: HTTPSConnectionPool" when call "oci os"

### ISSUE THREAD

**Issue by woworm** [oracle/oci-cli#82]
[oracle@infbjvm118 env]$ oci os ns get --config-file ./config --cli-rc-file ./oci-cli-file
RequestException: HTTPSConnectionPool(host='objectstorage.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /n/ (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f66678e8790>: Failed to establish a new connection: [Errno 113] No route to host',))

[oracle@infbjvm118 env]$ oci os bucket create --config-file ./config --cli-rc-file ./oci-cli-file --name adw-demo-oardc2 --namespace-name oraclekennguyen
RequestException: HTTPSConnectionPool(host='objectstorage.us-phoenix-1.oraclecloud.com', port=443): Max retries exceeded with url: /n/oraclekennguyen/b/ (Caused by NewConnectionError('<oci._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90f2093bd0>: Failed to establish a new connection: [Errno 113] No route to host',))

**Comment by vish1** [comment]
Can you check the network connectivity to oracle cloud servers - are you able to ping objectstorage.us-phoenix-1.oraclecloud.com?

**Comment by woworm** [comment]
oh, it's unreachable, does it means it's blocked by my side? But I can call other "oci" commands ...

**Comment by woworm** [comment]
and can create bucket on console

**Comment by woworm** [comment]
I can ping "objectstorage.us-ashburn-1.oraclecloud.com" , but I didn't find a option to specify the region or ad.

**Comment by viralmodi** [comment]
How did you get around it?

**Comment by woworm** [comment]
hi viralmodi, I put the env which run this command onto an oci compute instance, it can work now. Maybe can bypass it using a ssh tunnel, but I have no time to try it.
