### ISSUE TITLE
Please can an example be included for oci structured search

### ISSUE THREAD

**Issue by RomeshSharma** [oracle/oci-cli#83]
Request to provide an example of oci structured search with pagination option

**Comment by priteshkp** [comment]
Hey @RomeshSharma ,
   there are some examples here:
https://github.com/oracle/oci-cli/blob/master/scripts/examples/resource_search_example.sh

for pagination, you can just specify the `limit` arg, ex `--limit 10`.  For subsequent pages, take the returned `opc-next-page` value and pass it to the `page` param, ex `--limit 10 --page "<valueFromPreviousCall>"`.
