### ISSUE TITLE
oci-cli needs to stop depending on cryptography<43.0.0,>=3.2.1 because of a a security vulnerability

### ISSUE THREAD

**Issue by nidal123** [oracle/oci-cli#846]
When I try to fix it:
oci-cli 3.48.0 has requirement cryptography<43.0.0,>=3.2.1, but you'll have cryptography 43.0.1 which is incompatible.

https://github.com/advisories/GHSA-h4gh-qq45-vh27

**Comment by karthik-k-kamath** [comment]
Thanks for highliting
We (CLI team) are investigating this

**Comment by Kanvipasricha** [comment]
This issue is resolved in latest release. https://github.com/oracle/oci-cli/releases/tag/v3.49.0
