### ISSUE TITLE
Homebrew Install

### ISSUE THREAD

**Issue by jpoon** [oracle/oci-cli#85]
In case this is helpful for someone, I made a Homebrew formula to help with installing the cli on MacOS: 

https://github.com/jpoon/homebrew-oci-cli/

**Comment by paul-hummel-oracle** [comment]
Very cool!  I see you used virtual environments too.

**Comment by vish1** [comment]
Sure. We are exploring that and will update when we have more information.

**Comment by jpoon** [comment]
Should be fairly easy to add it to the official tap. I'm happy to submit a PR (https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request.md#formulae-related-pull-request), but have been hesitant to do so as I don't want to support it :)

**Comment by paul-hummel-oracle** [comment]
@jpoon, I am also hesitant to make it official as I don't have an automated test bed for MacOS -- just linux and windows.

**Comment by josephholsten** [comment]
@vish1 could you specify what more information you require?

@jpoon what would make you more comfortable with making it official? The readme explicitly gives an install process for Mac. Does the `curl|bash` is have more automated testing as this homebrew formula? Is there a reason we can't trust users to file a bug if things explode?

**Comment by paul-hummel-oracle** [comment]
@josephholsten I would be more comfortable if I could put in place some automated tests for this. We have such things for linux and windows -- over 20 OS platform regression tests. 
Although we have instructions for Mac, we do regularly encounter problems with Mac and sadly do not even have the developer resources to investigate something like Mojave.
Support ~ sustainability ~ commitment

**Comment by honzajavorek** [comment]
Would having macOS CI help? [CircleCI](https://circleci.com/) has macOS builds and is free for OSS, so it wouldn't probably need to go through much corporate hassle.

**Comment by jpoon** [comment]
I think there's a misunderstanding of @honzajavorek's suggestion. CircleCI hosts their own macOS builds and is free for OSS projects; there would be no need to maintain your own Mac servers.

**Comment by paul-hummel-oracle** [comment]
Note: We spoke to CircleCI last week.  They do not offer any free tier for MacOS servers.

**Comment by jpoon** [comment]
It turns out Travis has free MacOS builds and to test it out, here's a Travis build https://travis-ci.org/jpoon/homebrew-oci-cli.

Configuration: https://github.com/jpoon/homebrew-oci-cli/blob/master/.travis.yml

```
install:
  - brew install jpoon/homebrew-oci-cli/oci-cli

test:
  - brew test oci-cli
  - brew audit --strict --online oci-cli
```

The unfortunate part is that Homebrew doesn't make it easy to test a local package. There are a couple of SO posts with suggestions on how to do this, but I haven't tried it yet https://stackoverflow.com/questions/20396325/using-travis-ci-to-test-homebrew-tap.

**Comment by kernleee** [comment]
OCI CLI is now on Homebrew, closing this. https://formulae.brew.sh/formula/oci-cli
