### ISSUE TITLE
Oracle vcn dns entries

### ISSUE THREAD

**Issue by Erniemoore** [oracle/oci-cli#86]
I can't find a method via the cli to query to the VCN resolver DNs data for ocids that begin
ocid1.vcndnsrecord...

Is there a new method coming out to handle this
I assume it will mean being able to access dbaas vnic and VCN private Ip records

Regards
Ernie

**Comment by paul-hummel-oracle** [comment]
@Erniemoore I'm sorry for not quite understanding the ask.
I sometime use jq (https://stedolan.github.io/jq/) to parse the json results from oci commands.

oci network vcn list --compartment-id $COMPARTMENT_ID | jq -r '.data[] | select(.id | contains("ocid1.vcn.oc1.phx")) '

**Comment by Erniemoore** [comment]
Hi Paul

Its related to DBaaS on VM and the internal DNS domain

The said entries don't appear in the normal VCN list so i'm trying to track them down

Regards
Ernie

**Comment by paul-hummel-oracle** [comment]
Apologies Ernie for the late reply.
I have not tracked them down either.  I suspect I will need to create a feature request to have them exposed.  I still need to follow-up with some partner teams.

**Comment by paul-hummel-oracle** [comment]
There is some internal debate as to whether these should be exposed.  I'm sorry this is not work that is being planned.
