### ISSUE TITLE
Error: Failed to query available provider packages

### ISSUE THREAD

**Issue by bobwlawson** [oracle/oci-cli#862]
bob_w_laws@cloudshell:combined (us-ashburn-1)$ terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/oci...
- Finding latest version of hashicorp/local...
- Installing hashicorp/oci v6.13.0...
- Installed hashicorp/oci v6.13.0 (unauthenticated)
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/local: could not connect to registry.terraform.io: failed to request discovery document: Get
│ "https://registry.terraform.io/.well-known/terraform.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
╵

**Comment by karthik-k-kamath** [comment]
Sorry we dont support Terraform queries in this channel
