### ISSUE TITLE
Identity Domain addUserToGroup getting error as string exceeds max limit

### ISSUE THREAD

**Issue by veeravastavg** [oracle/oci-cli#865]
The code I wrote:
import oci

config = oci.config.from_file()
group_ocid = 'ocid1.group.oc1..xxxxxxxxb6tu4knxmw2xz3ewamcxvt652y5kfvs2ydly6lenjhiwzvf3ap3a'
user_ocid = 'ocid1.user.oc1..xxxxxxxx53pglzrxljx53u5x53wobwyqeed6lfbtxt34i36mrx4y4f3m2m4q'

identity_client = oci.identity.IdentityClient(config)
identity_domain = identity_client.list_domains(compartment_id=config['tenancy']).data
identity_domain_client = oci.identity_domains.IdentityDomainsClient(config,service_endpoint=identity_domain[0].url)
user_add_group = identity_domain_client.patch_group(
        group_id = group_ocid,
        patch_op = oci.identity_domains.models.PatchOp(
                schemas = ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
                operations=[
            {
                "op": "add",
                "path": "members",
                "value": [{"value": user_ocid, "type": "User"}]
            }
                ]
            )
        ).data
print(user_add_group)

Error i got:
Traceback (most recent call last):
  File "/workspaces/oci-python/test/test.py", line 10, in <module>
    user_add_group = identity_domain_client.patch_group(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/oci/identity_domains/identity_domains_client.py", line 28201, in patch_group
    return self.base_client.call_api(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/oci/base_client.py", line 535, in call_api
    response = self.request(request, allow_control_chars, operation_name, api_reference_link)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/circuitbreaker.py", line 159, in wrapper
    return call(function, *args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/circuitbreaker.py", line 170, in call
    return func(*args, **kwargs)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/oci/base_client.py", line 726, in request
    self.raise_service_error(request, response, service_code, message, operation_name, api_reference_link, target_service, request_endpoint, client_version, timestamp, deserialized_data)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/oci/base_client.py", line 891, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'target_service': 'identity_domains', 'status': 400, 'code': None, 'opc-request-id': 'C1A989FF8EC446A0864A8F3F5E45EBFD/br32g0pXR00000000', 'message': 'The service returned error code 400', 'operation_name': 'patch_group', 'timestamp': '2024-10-29T10:23:48.131984+00:00', 'client_version': 'Oracle-PythonSDK/2.137.1', 'request_endpoint': 'PATCH https://idcs-e1f86dee59474c078c92c491a9db6e2b.identity.oraclecloud.com:443/admin/v1/Groups/ocid1.group.oc1..aaaaaaaab6tu4knxmw2xz3ewamcxvt652y5kfvs2ydly6lenjhiwzvf3ap3a', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_none for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/identity-domains/v1/Group/PatchGroup for details on this operation's requirements. If you are unable to resolve this identity_domains issue, please contact Oracle support and provide them this full error message.", 'schemas': ['urn:ietf:params:scim:api:messages:2.0:Error', 'urn:ietf:params:scim:api:oracle:idcs:extension:messages:Error'], 'detail': 'The maximum characters allowed is 40 for attribute: members.value for value eq "ocid1.user.oc1..aaaaaaaa53pglzrxljx53u5x53wobwyqeed6lfbtxt34i36mrx4y4f3m2m4q".', 'urn:ietf:params:scim:api:oracle:idcs:extension:messages:_error': {'messageId': 'error.common.validation.stringExceedsMaxLimit'}}

**Comment by adizohar** [comment]
You are in the wrong project, please close and submit it at https://github.com/oracle/oci-python-sdk/issues

**Comment by veeravastavg** [comment]
Sure sorry for the inconvenience.

**Comment by veeravastavg** [comment]
Wrong project.
