### ISSUE TITLE
Error on query with an attribute avuth a "-" in the name

### ISSUE THREAD

**Issue by cpruvost** [oracle/oci-cli#90]
oci db system list --compartment-id="ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhcjs6c73ya2wl6vaxq" --query "data [?\"display-name\"=='MyTFDatabaseNode'].{Id:id}"

LexerError: Bad jmespath expression: Unclosed " delimiter:
data [?" display-name\=='MyTFDatabaseNode'].{Id:id}

Ty for all

PS : Another question
PS C:\Travail\Travail2019\Demos\InfraAsCode\DbSystem> oci db system list --compartment-id="ocid1.compartment.oc1..aaaaaaaa
ch4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhcjs6c73ya2wl6vaxq" --query "data [*].{Id:id}"
[
  {
    "Id": "ocid1.dbsystem.oc1.iad.abuwcljtxci4exlyiplphv5tl2457smpkrjqxsc6dmb3eygb4tsb4immn64q"
  }
]
Does I need jq to get Id in a variable ? or is there a more simple solution ?

**Comment by mross22** [comment]
For the first question, you need to escape the inner quotes, so like this:
`oci db system list -c $C --query "data[?\"display-name\"=='MyTFDatabaseNode'].{Id:id}"`

For the second example you can use the `--raw-output` option to get back just the string value unquoted, assuming your query narrows it down to one single response object, so for example:
`oci db system list -c $C --query "data[0].id" --raw-output`

**Comment by cpruvost** [comment]
Point 1 

- On Oracle Linux Dev CS

+ oci --version
2.4.10
+ oci db system list --compartment-id=ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhcjs6c73ya2wl6vaxq --query 'data[?"display-name"=='\''MyTFDatabaseNode'\''].{Id:id}'
[
  {
    "Id": "ocid1.dbsystem.oc1.iad.abuwcljtxci4exlyiplphv5tl2457smpkrjqxsc6dmb3eygb4tsb4immn64q"
  }
]

- On windows (my laptop)
PS C:\Users\chris> oci --version
2.4.31

PS C:\Users\chris> oci db system list --compartment-id=ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhc
js6c73ya2wl6vaxq --query 'data[?"display-name"=='\''MyTFDatabaseNode'\''].{Id:id}'
Usage: oci db system list [OPTIONS]

Error: Got unexpected extra argument (\MyTFDatabaseNode\'].{Id:id})

Point 2

- On windows on my laptop

PS C:\Users\chris> oci db system list --compartment-id="ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxh
cjs6c73ya2wl6vaxq" --raw-output --query "data [0].{Id:id}"
{
  "Id": "ocid1.dbsystem.oc1.iad.abuwcljtxci4exlyiplphv5tl2457smpkrjqxsc6dmb3eygb4tsb4immn64q"
}
PS C:\Users\chris> oci --version
2.4.31

- On Oracle Linux on DevCS

+ oci --version
2.4.10
+ oci db system list --compartment-id=ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhcjs6c73ya2wl6vaxq --raw-output --query 'data [*].{Id:id}'
Error: no such option: --raw-output

**Comment by paul-hummel-oracle** [comment]
@cpruvost thanks for including the version number -- 
The "--raw-output" option was added in 2.4.14 (2018-01-11).

**Comment by paul-hummel-oracle** [comment]
@cpruvost regarding  Error: Got unexpected extra argument (\MyTFDatabaseNode'].{Id:id})

Please try this:

oci db system list --compartment-id=ocid1.compartment.oc1..aaaaaaaach4c3i5kpecjfjqwp3wfjfmbbjniyzieaxhc
js6c73ya2wl6vaxq --query 'data[?"display-name"==\"MyTFDatabaseNode\"].{Id:id}'

Replaced triple single quotes with backslash double quotes

**Comment by viralmodi** [comment]
@cpruvost The below command should work for you in windows:
oci db system list --query "data[?\`"display-name\`"==\`"MyTFDatabaseNode\`"].{Id:id}"
Please note there is a backtick after the backslash above.

Also, I don't know why the help message did not get printed properly on your machine but on windows virtualbox I used, I see the below message on giving incorrect escaping in powershell:
If a key name has any characters besides [a-z, A-Z, 0-9, _], it needs to be escaped.
In bash or similar "NIX" based shells used in "NIX" environment, escaping can be done byusing double quotes inside single quotes.
e.g. --query 'data[*]."display-name"'
If using PowerShell in Windows environment, escaping can be done by using double quoteswith double escape character \`.
e.g. --query data[*].\`"display-name\`"
LexerError: Bad jmespath expression: Unknown token \:
data[?\`display-name\`==\`MyTFDatabaseNode\`].{Id:id}

The difference being, in windows power shell you escape using \` (backslash followed by backtick)

**Comment by paul-hummel-oracle** [comment]
Will close this issue if we do not get further feedback.  Thank you.

**Comment by cpruvost** [comment]
Sorry for delay..I tried again....

PS C:\Users\chris> oci db system list  --compartment-id="ocid1.compartment.oc1..aaaaaaaaskpievhn3ik3rlff2tlqpkbrinsht2e5kz
7z636cghpftpkqu6wq" --query "data[?`"display-name`"==`"MyTFDatabaseNode`"].{Id:id}"
If a key name has any characters besides [a-z, A-Z, 0-9, _], it needs to be escaped.
In bash or similar "NIX" based shells used in "NIX" environment, escaping can be done byusing double quotes inside single quotes.
e.g. --query 'data[*]."display-name"'
If using PowerShell in Windows environment, escaping can be done by using double quoteswith double escape character \`.
e.g. --query data[*].\`"display-name\`"
LexerError: Bad jmespath expression: Unknown token '-':
data[?display-name==MyTFDatabaseNode].{Id:id}

**Comment by cpruvost** [comment]
I tried a lot of different things...I got error or no result...if you succeed doing that on windows may be email me the order to run...it seems to be very complex on windows...and we need simple things to run....

**Comment by craigcarl-oracle** [comment]
@cpruvost this works for me on Windows Server 2016 - 
```oci compute instance-console-connection create \
--instance-id "$ocid" \
--ssh-public-key-file ~/keys/id_rsa.pub \
--wait-for-state ACTIVE \
--query 'data."connection-string"' \
--raw-output```

**Comment by viralmodi** [comment]
@cpruvost Please read my comment above for more details. In short, this works for me on windows:
oci db system list --query "data[?`"display-name`"==`"MyTFDatabaseNode`"].{Id:id}"

**Comment by viralmodi** [comment]
@cpruvost Please check my solution above. It works for me on windows. I will close this issue if I don't see any response for another week.

**Comment by viralmodi** [comment]
Closing the issue with the solution provided above.
