### ISSUE TITLE
Feature Request: get wallet from ATP database

### ISSUE THREAD

**Issue by schmidtp0740** [oracle/oci-cli#92]
could you add a command that grabs the wallet from autonomous transaction processing?

REST API for such: https://docs.cloud.oracle.com/iaas/api/#/en/database/20160918/AutonomousDatabase/GenerateAutonomousDatabaseWallet

**Comment by viralmodi** [comment]
@schmidtp0740 Thanks for your request. We will be adding a command for it and you will most likely see it in our next release. Stay tuned.

**Comment by paul-hummel-oracle** [comment]
@schmidtp0740 
We have released the following new commands:
  * (``oci db autonomous-data-warehouse generate-wallet``)
  * (``oci db autonomous-database generate-wallet``)
