### ISSUE TITLE
Error installing Python during CLI install

### ISSUE THREAD

**Issue by thuymy** [oracle/oci-cli#98]
Hi,
I'm running Windows 7 64-bit and am getting the following error in my attempt to install CLI.  (Using the same command syntax on Windows Server 2016 Standard 64-bit installs ok.)  Please advise.

Thanks,
Thuymy
 
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\windows\system32> Set-ExecutionPolicy RemoteSigned

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic. Do you want to change the execution
policy?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
PS C:\windows\system32> powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).D
ownloadString('https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1'))"

Python is required to run the CLI.
Install Python now? (Entering "n" will exit the installation script)
[Y] Yes  [N] No  [?] Help (default is "Y"):
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An unexpected error occur
red on a send."
At line:133 char:55
+         (New-Object System.Net.WebClient).DownloadFile <<<< ($Uri, $OutFile)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

**Comment by paul-hummel-oracle** [comment]
@thuymy 
Windows 7 doesn't have the necessary Powershell version to run the installation script properly.  I don't suppose upgrading to Windows 10 is an option for you.

You could try manually installing Python for Windows 3.6.5 64-bit and then afterwards retry the OCI CLI install. 
https://www.python.org/downloads/release/python-365/.  

thank you

**Comment by thuymy** [comment]
Thanks @paul-hummel-oracle for the help! I installed Python separately and the OCI CLI is now installed successfully.
